package devtools

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

var generatedPatterns = []string{
	"internal/db/*.sql.go",
	"internal/dxclient/models.gen.go",
	"ui/src/api.gen.ts",
	"schema/shipped.sql",
}

func isGenerated(path string) bool {
	for _, pattern := range generatedPatterns {
		matched, err := filepath.Match(pattern, path)
		if err == nil && matched {
			return true
		}
	}
	return false
}

func CommitCmd() *cobra.Command {
	return &cobra.Command{
		Use:                "commit",
		Short:              "Commit staged files, stripping generated files when --intent is set",
		DisableFlagParsing: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			intent := false
			var passArgs []string
			for _, a := range args {
				if a == "--intent" {
					intent = true
				} else {
					passArgs = append(passArgs, a)
				}
			}

			if !intent {
				c := exec.Command("git", append([]string{"commit"}, passArgs...)...)
				c.Stdout = os.Stdout
				c.Stderr = os.Stderr
				c.Stdin = os.Stdin
				return c.Run()
			}

			out, err := exec.Command("git", "diff", "--cached", "--name-only").Output()
			if err != nil {
				return fmt.Errorf("git diff --cached: %w", err)
			}

			var staged, toUnstage []string
			for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
				if line == "" {
					continue
				}
				if isGenerated(line) {
					toUnstage = append(toUnstage, line)
				} else {
					staged = append(staged, line)
				}
			}

			for _, path := range toUnstage {
				fmt.Fprintf(os.Stderr, "warning: unstaging generated file: %s (will be regenerated by merge-train)\n", path)
			}

			if len(toUnstage) > 0 {
				unstageArgs := append([]string{"restore", "--staged"}, toUnstage...)
				if err := exec.Command("git", unstageArgs...).Run(); err != nil {
					return fmt.Errorf("git restore --staged: %w", err)
				}
			}

			if len(staged) == 0 {
				return fmt.Errorf("nothing to commit after stripping generated files")
			}

			c := exec.Command("git", append([]string{"commit"}, passArgs...)...)
			c.Stdout = os.Stdout
			c.Stderr = os.Stderr
			c.Stdin = os.Stdin
			return c.Run()
		},
	}
}
