/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProjectSlugRouteImport } from './routes/project/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminLlmRouteImport } from './routes/admin/llm'
import { Route as AdminInvitesRouteImport } from './routes/admin/invites'
import { Route as ProjectSlugIndexRouteImport } from './routes/project/$slug/index'
import { Route as ProjectSlugWorklogRouteImport } from './routes/project/$slug/worklog'
import { Route as ProjectSlugTimingsRouteImport } from './routes/project/$slug/timings'
import { Route as ProjectSlugTestsRouteImport } from './routes/project/$slug/tests'
import { Route as ProjectSlugTasksRouteImport } from './routes/project/$slug/tasks'
import { Route as ProjectSlugSettingsRouteImport } from './routes/project/$slug/settings'
import { Route as ProjectSlugQueueRouteImport } from './routes/project/$slug/queue'
import { Route as ProjectSlugProfileRouteImport } from './routes/project/$slug/profile'
import { Route as ProjectSlugPatternsRouteImport } from './routes/project/$slug/patterns'
import { Route as ProjectSlugLogsRouteImport } from './routes/project/$slug/logs'
import { Route as ProjectSlugJournalRouteImport } from './routes/project/$slug/journal'
import { Route as ProjectSlugIssuesRouteImport } from './routes/project/$slug/issues'
import { Route as ProjectSlugGoalsRouteImport } from './routes/project/$slug/goals'
import { Route as ProjectSlugFeaturesRouteImport } from './routes/project/$slug/features'
import { Route as ProjectSlugErrorsRouteImport } from './routes/project/$slug/errors'
import { Route as ProjectSlugDemosRouteImport } from './routes/project/$slug/demos'
import { Route as ProjectSlugCountersRouteImport } from './routes/project/$slug/counters'
import { Route as ProjectSlugClaudeRouteImport } from './routes/project/$slug/claude'
import { Route as ProjectSlugBlockerQuestionsRouteImport } from './routes/project/$slug/blocker-questions'
import { Route as ProjectSlugThemesIndexRouteImport } from './routes/project/$slug/themes/index'
import { Route as ProjectSlugTestsIndexRouteImport } from './routes/project/$slug/tests/index'
import { Route as ProjectSlugTasksIndexRouteImport } from './routes/project/$slug/tasks/index'
import { Route as ProjectSlugQuestionsIndexRouteImport } from './routes/project/$slug/questions/index'
import { Route as ProjectSlugPatternsIndexRouteImport } from './routes/project/$slug/patterns/index'
import { Route as ProjectSlugIssuesIndexRouteImport } from './routes/project/$slug/issues/index'
import { Route as ProjectSlugGoalsIndexRouteImport } from './routes/project/$slug/goals/index'
import { Route as ProjectSlugFeaturesIndexRouteImport } from './routes/project/$slug/features/index'
import { Route as ProjectSlugClaudeIndexRouteImport } from './routes/project/$slug/claude/index'
import { Route as ProjectSlugThemesNameRouteImport } from './routes/project/$slug/themes/$name'
import { Route as ProjectSlugTestsIdRouteImport } from './routes/project/$slug/tests/$id'
import { Route as ProjectSlugTasksIdRouteImport } from './routes/project/$slug/tasks/$id'
import { Route as ProjectSlugQuestionsIdRouteImport } from './routes/project/$slug/questions/$id'
import { Route as ProjectSlugPatternsIdRouteImport } from './routes/project/$slug/patterns/$id'
import { Route as ProjectSlugIssuesIdRouteImport } from './routes/project/$slug/issues/$id'
import { Route as ProjectSlugFeaturesNameRouteImport } from './routes/project/$slug/features/$name'
import { Route as ProjectSlugClaudeSessionIdRouteImport } from './routes/project/$slug/claude/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugRoute = ProjectSlugRouteImport.update({
  id: '/project/$slug',
  path: '/project/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLlmRoute = AdminLlmRouteImport.update({
  id: '/admin/llm',
  path: '/admin/llm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectSlugIndexRoute = ProjectSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugWorklogRoute = ProjectSlugWorklogRouteImport.update({
  id: '/worklog',
  path: '/worklog',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugTimingsRoute = ProjectSlugTimingsRouteImport.update({
  id: '/timings',
  path: '/timings',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugTestsRoute = ProjectSlugTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugTasksRoute = ProjectSlugTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugSettingsRoute = ProjectSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugQueueRoute = ProjectSlugQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugProfileRoute = ProjectSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugPatternsRoute = ProjectSlugPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugLogsRoute = ProjectSlugLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugJournalRoute = ProjectSlugJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugIssuesRoute = ProjectSlugIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugGoalsRoute = ProjectSlugGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugFeaturesRoute = ProjectSlugFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugErrorsRoute = ProjectSlugErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugDemosRoute = ProjectSlugDemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugCountersRoute = ProjectSlugCountersRouteImport.update({
  id: '/counters',
  path: '/counters',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugClaudeRoute = ProjectSlugClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugBlockerQuestionsRoute =
  ProjectSlugBlockerQuestionsRouteImport.update({
    id: '/blocker-questions',
    path: '/blocker-questions',
    getParentRoute: () => ProjectSlugRoute,
  } as any)
const ProjectSlugThemesIndexRoute = ProjectSlugThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugTestsIndexRoute = ProjectSlugTestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugTestsRoute,
} as any)
const ProjectSlugTasksIndexRoute = ProjectSlugTasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugTasksRoute,
} as any)
const ProjectSlugQuestionsIndexRoute =
  ProjectSlugQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => ProjectSlugRoute,
  } as any)
const ProjectSlugPatternsIndexRoute =
  ProjectSlugPatternsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectSlugPatternsRoute,
  } as any)
const ProjectSlugIssuesIndexRoute = ProjectSlugIssuesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugIssuesRoute,
} as any)
const ProjectSlugGoalsIndexRoute = ProjectSlugGoalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugGoalsRoute,
} as any)
const ProjectSlugFeaturesIndexRoute =
  ProjectSlugFeaturesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectSlugFeaturesRoute,
  } as any)
const ProjectSlugClaudeIndexRoute = ProjectSlugClaudeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugClaudeRoute,
} as any)
const ProjectSlugThemesNameRoute = ProjectSlugThemesNameRouteImport.update({
  id: '/themes/$name',
  path: '/themes/$name',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugTestsIdRoute = ProjectSlugTestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectSlugTestsRoute,
} as any)
const ProjectSlugTasksIdRoute = ProjectSlugTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectSlugTasksRoute,
} as any)
const ProjectSlugQuestionsIdRoute = ProjectSlugQuestionsIdRouteImport.update({
  id: '/questions/$id',
  path: '/questions/$id',
  getParentRoute: () => ProjectSlugRoute,
} as any)
const ProjectSlugPatternsIdRoute = ProjectSlugPatternsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectSlugPatternsRoute,
} as any)
const ProjectSlugIssuesIdRoute = ProjectSlugIssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectSlugIssuesRoute,
} as any)
const ProjectSlugFeaturesNameRoute = ProjectSlugFeaturesNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ProjectSlugFeaturesRoute,
} as any)
const ProjectSlugClaudeSessionIdRoute =
  ProjectSlugClaudeSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ProjectSlugClaudeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/users': typeof AdminUsersRoute
  '/project/$slug': typeof ProjectSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/project/$slug/blocker-questions': typeof ProjectSlugBlockerQuestionsRoute
  '/project/$slug/claude': typeof ProjectSlugClaudeRouteWithChildren
  '/project/$slug/counters': typeof ProjectSlugCountersRoute
  '/project/$slug/demos': typeof ProjectSlugDemosRoute
  '/project/$slug/errors': typeof ProjectSlugErrorsRoute
  '/project/$slug/features': typeof ProjectSlugFeaturesRouteWithChildren
  '/project/$slug/goals': typeof ProjectSlugGoalsRouteWithChildren
  '/project/$slug/issues': typeof ProjectSlugIssuesRouteWithChildren
  '/project/$slug/journal': typeof ProjectSlugJournalRoute
  '/project/$slug/logs': typeof ProjectSlugLogsRoute
  '/project/$slug/patterns': typeof ProjectSlugPatternsRouteWithChildren
  '/project/$slug/profile': typeof ProjectSlugProfileRoute
  '/project/$slug/queue': typeof ProjectSlugQueueRoute
  '/project/$slug/settings': typeof ProjectSlugSettingsRoute
  '/project/$slug/tasks': typeof ProjectSlugTasksRouteWithChildren
  '/project/$slug/tests': typeof ProjectSlugTestsRouteWithChildren
  '/project/$slug/timings': typeof ProjectSlugTimingsRoute
  '/project/$slug/worklog': typeof ProjectSlugWorklogRoute
  '/project/$slug/': typeof ProjectSlugIndexRoute
  '/project/$slug/claude/$sessionId': typeof ProjectSlugClaudeSessionIdRoute
  '/project/$slug/features/$name': typeof ProjectSlugFeaturesNameRoute
  '/project/$slug/issues/$id': typeof ProjectSlugIssuesIdRoute
  '/project/$slug/patterns/$id': typeof ProjectSlugPatternsIdRoute
  '/project/$slug/questions/$id': typeof ProjectSlugQuestionsIdRoute
  '/project/$slug/tasks/$id': typeof ProjectSlugTasksIdRoute
  '/project/$slug/tests/$id': typeof ProjectSlugTestsIdRoute
  '/project/$slug/themes/$name': typeof ProjectSlugThemesNameRoute
  '/project/$slug/claude/': typeof ProjectSlugClaudeIndexRoute
  '/project/$slug/features/': typeof ProjectSlugFeaturesIndexRoute
  '/project/$slug/goals/': typeof ProjectSlugGoalsIndexRoute
  '/project/$slug/issues/': typeof ProjectSlugIssuesIndexRoute
  '/project/$slug/patterns/': typeof ProjectSlugPatternsIndexRoute
  '/project/$slug/questions/': typeof ProjectSlugQuestionsIndexRoute
  '/project/$slug/tasks/': typeof ProjectSlugTasksIndexRoute
  '/project/$slug/tests/': typeof ProjectSlugTestsIndexRoute
  '/project/$slug/themes/': typeof ProjectSlugThemesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/project/$slug/blocker-questions': typeof ProjectSlugBlockerQuestionsRoute
  '/project/$slug/counters': typeof ProjectSlugCountersRoute
  '/project/$slug/demos': typeof ProjectSlugDemosRoute
  '/project/$slug/errors': typeof ProjectSlugErrorsRoute
  '/project/$slug/journal': typeof ProjectSlugJournalRoute
  '/project/$slug/logs': typeof ProjectSlugLogsRoute
  '/project/$slug/profile': typeof ProjectSlugProfileRoute
  '/project/$slug/queue': typeof ProjectSlugQueueRoute
  '/project/$slug/settings': typeof ProjectSlugSettingsRoute
  '/project/$slug/timings': typeof ProjectSlugTimingsRoute
  '/project/$slug/worklog': typeof ProjectSlugWorklogRoute
  '/project/$slug': typeof ProjectSlugIndexRoute
  '/project/$slug/claude/$sessionId': typeof ProjectSlugClaudeSessionIdRoute
  '/project/$slug/features/$name': typeof ProjectSlugFeaturesNameRoute
  '/project/$slug/issues/$id': typeof ProjectSlugIssuesIdRoute
  '/project/$slug/patterns/$id': typeof ProjectSlugPatternsIdRoute
  '/project/$slug/questions/$id': typeof ProjectSlugQuestionsIdRoute
  '/project/$slug/tasks/$id': typeof ProjectSlugTasksIdRoute
  '/project/$slug/tests/$id': typeof ProjectSlugTestsIdRoute
  '/project/$slug/themes/$name': typeof ProjectSlugThemesNameRoute
  '/project/$slug/claude': typeof ProjectSlugClaudeIndexRoute
  '/project/$slug/features': typeof ProjectSlugFeaturesIndexRoute
  '/project/$slug/goals': typeof ProjectSlugGoalsIndexRoute
  '/project/$slug/issues': typeof ProjectSlugIssuesIndexRoute
  '/project/$slug/patterns': typeof ProjectSlugPatternsIndexRoute
  '/project/$slug/questions': typeof ProjectSlugQuestionsIndexRoute
  '/project/$slug/tasks': typeof ProjectSlugTasksIndexRoute
  '/project/$slug/tests': typeof ProjectSlugTestsIndexRoute
  '/project/$slug/themes': typeof ProjectSlugThemesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/llm': typeof AdminLlmRoute
  '/admin/users': typeof AdminUsersRoute
  '/project/$slug': typeof ProjectSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/project/$slug/blocker-questions': typeof ProjectSlugBlockerQuestionsRoute
  '/project/$slug/claude': typeof ProjectSlugClaudeRouteWithChildren
  '/project/$slug/counters': typeof ProjectSlugCountersRoute
  '/project/$slug/demos': typeof ProjectSlugDemosRoute
  '/project/$slug/errors': typeof ProjectSlugErrorsRoute
  '/project/$slug/features': typeof ProjectSlugFeaturesRouteWithChildren
  '/project/$slug/goals': typeof ProjectSlugGoalsRouteWithChildren
  '/project/$slug/issues': typeof ProjectSlugIssuesRouteWithChildren
  '/project/$slug/journal': typeof ProjectSlugJournalRoute
  '/project/$slug/logs': typeof ProjectSlugLogsRoute
  '/project/$slug/patterns': typeof ProjectSlugPatternsRouteWithChildren
  '/project/$slug/profile': typeof ProjectSlugProfileRoute
  '/project/$slug/queue': typeof ProjectSlugQueueRoute
  '/project/$slug/settings': typeof ProjectSlugSettingsRoute
  '/project/$slug/tasks': typeof ProjectSlugTasksRouteWithChildren
  '/project/$slug/tests': typeof ProjectSlugTestsRouteWithChildren
  '/project/$slug/timings': typeof ProjectSlugTimingsRoute
  '/project/$slug/worklog': typeof ProjectSlugWorklogRoute
  '/project/$slug/': typeof ProjectSlugIndexRoute
  '/project/$slug/claude/$sessionId': typeof ProjectSlugClaudeSessionIdRoute
  '/project/$slug/features/$name': typeof ProjectSlugFeaturesNameRoute
  '/project/$slug/issues/$id': typeof ProjectSlugIssuesIdRoute
  '/project/$slug/patterns/$id': typeof ProjectSlugPatternsIdRoute
  '/project/$slug/questions/$id': typeof ProjectSlugQuestionsIdRoute
  '/project/$slug/tasks/$id': typeof ProjectSlugTasksIdRoute
  '/project/$slug/tests/$id': typeof ProjectSlugTestsIdRoute
  '/project/$slug/themes/$name': typeof ProjectSlugThemesNameRoute
  '/project/$slug/claude/': typeof ProjectSlugClaudeIndexRoute
  '/project/$slug/features/': typeof ProjectSlugFeaturesIndexRoute
  '/project/$slug/goals/': typeof ProjectSlugGoalsIndexRoute
  '/project/$slug/issues/': typeof ProjectSlugIssuesIndexRoute
  '/project/$slug/patterns/': typeof ProjectSlugPatternsIndexRoute
  '/project/$slug/questions/': typeof ProjectSlugQuestionsIndexRoute
  '/project/$slug/tasks/': typeof ProjectSlugTasksIndexRoute
  '/project/$slug/tests/': typeof ProjectSlugTestsIndexRoute
  '/project/$slug/themes/': typeof ProjectSlugThemesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/invites'
    | '/admin/llm'
    | '/admin/users'
    | '/project/$slug'
    | '/admin/'
    | '/project/$slug/blocker-questions'
    | '/project/$slug/claude'
    | '/project/$slug/counters'
    | '/project/$slug/demos'
    | '/project/$slug/errors'
    | '/project/$slug/features'
    | '/project/$slug/goals'
    | '/project/$slug/issues'
    | '/project/$slug/journal'
    | '/project/$slug/logs'
    | '/project/$slug/patterns'
    | '/project/$slug/profile'
    | '/project/$slug/queue'
    | '/project/$slug/settings'
    | '/project/$slug/tasks'
    | '/project/$slug/tests'
    | '/project/$slug/timings'
    | '/project/$slug/worklog'
    | '/project/$slug/'
    | '/project/$slug/claude/$sessionId'
    | '/project/$slug/features/$name'
    | '/project/$slug/issues/$id'
    | '/project/$slug/patterns/$id'
    | '/project/$slug/questions/$id'
    | '/project/$slug/tasks/$id'
    | '/project/$slug/tests/$id'
    | '/project/$slug/themes/$name'
    | '/project/$slug/claude/'
    | '/project/$slug/features/'
    | '/project/$slug/goals/'
    | '/project/$slug/issues/'
    | '/project/$slug/patterns/'
    | '/project/$slug/questions/'
    | '/project/$slug/tasks/'
    | '/project/$slug/tests/'
    | '/project/$slug/themes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/invites'
    | '/admin/llm'
    | '/admin/users'
    | '/admin'
    | '/project/$slug/blocker-questions'
    | '/project/$slug/counters'
    | '/project/$slug/demos'
    | '/project/$slug/errors'
    | '/project/$slug/journal'
    | '/project/$slug/logs'
    | '/project/$slug/profile'
    | '/project/$slug/queue'
    | '/project/$slug/settings'
    | '/project/$slug/timings'
    | '/project/$slug/worklog'
    | '/project/$slug'
    | '/project/$slug/claude/$sessionId'
    | '/project/$slug/features/$name'
    | '/project/$slug/issues/$id'
    | '/project/$slug/patterns/$id'
    | '/project/$slug/questions/$id'
    | '/project/$slug/tasks/$id'
    | '/project/$slug/tests/$id'
    | '/project/$slug/themes/$name'
    | '/project/$slug/claude'
    | '/project/$slug/features'
    | '/project/$slug/goals'
    | '/project/$slug/issues'
    | '/project/$slug/patterns'
    | '/project/$slug/questions'
    | '/project/$slug/tasks'
    | '/project/$slug/tests'
    | '/project/$slug/themes'
  id:
    | '__root__'
    | '/'
    | '/admin/invites'
    | '/admin/llm'
    | '/admin/users'
    | '/project/$slug'
    | '/admin/'
    | '/project/$slug/blocker-questions'
    | '/project/$slug/claude'
    | '/project/$slug/counters'
    | '/project/$slug/demos'
    | '/project/$slug/errors'
    | '/project/$slug/features'
    | '/project/$slug/goals'
    | '/project/$slug/issues'
    | '/project/$slug/journal'
    | '/project/$slug/logs'
    | '/project/$slug/patterns'
    | '/project/$slug/profile'
    | '/project/$slug/queue'
    | '/project/$slug/settings'
    | '/project/$slug/tasks'
    | '/project/$slug/tests'
    | '/project/$slug/timings'
    | '/project/$slug/worklog'
    | '/project/$slug/'
    | '/project/$slug/claude/$sessionId'
    | '/project/$slug/features/$name'
    | '/project/$slug/issues/$id'
    | '/project/$slug/patterns/$id'
    | '/project/$slug/questions/$id'
    | '/project/$slug/tasks/$id'
    | '/project/$slug/tests/$id'
    | '/project/$slug/themes/$name'
    | '/project/$slug/claude/'
    | '/project/$slug/features/'
    | '/project/$slug/goals/'
    | '/project/$slug/issues/'
    | '/project/$slug/patterns/'
    | '/project/$slug/questions/'
    | '/project/$slug/tasks/'
    | '/project/$slug/tests/'
    | '/project/$slug/themes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminLlmRoute: typeof AdminLlmRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ProjectSlugRoute: typeof ProjectSlugRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug': {
      id: '/project/$slug'
      path: '/project/$slug'
      fullPath: '/project/$slug'
      preLoaderRoute: typeof ProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/llm': {
      id: '/admin/llm'
      path: '/admin/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AdminLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$slug/': {
      id: '/project/$slug/'
      path: '/'
      fullPath: '/project/$slug/'
      preLoaderRoute: typeof ProjectSlugIndexRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/worklog': {
      id: '/project/$slug/worklog'
      path: '/worklog'
      fullPath: '/project/$slug/worklog'
      preLoaderRoute: typeof ProjectSlugWorklogRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/timings': {
      id: '/project/$slug/timings'
      path: '/timings'
      fullPath: '/project/$slug/timings'
      preLoaderRoute: typeof ProjectSlugTimingsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/tests': {
      id: '/project/$slug/tests'
      path: '/tests'
      fullPath: '/project/$slug/tests'
      preLoaderRoute: typeof ProjectSlugTestsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/tasks': {
      id: '/project/$slug/tasks'
      path: '/tasks'
      fullPath: '/project/$slug/tasks'
      preLoaderRoute: typeof ProjectSlugTasksRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/settings': {
      id: '/project/$slug/settings'
      path: '/settings'
      fullPath: '/project/$slug/settings'
      preLoaderRoute: typeof ProjectSlugSettingsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/queue': {
      id: '/project/$slug/queue'
      path: '/queue'
      fullPath: '/project/$slug/queue'
      preLoaderRoute: typeof ProjectSlugQueueRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/profile': {
      id: '/project/$slug/profile'
      path: '/profile'
      fullPath: '/project/$slug/profile'
      preLoaderRoute: typeof ProjectSlugProfileRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/patterns': {
      id: '/project/$slug/patterns'
      path: '/patterns'
      fullPath: '/project/$slug/patterns'
      preLoaderRoute: typeof ProjectSlugPatternsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/logs': {
      id: '/project/$slug/logs'
      path: '/logs'
      fullPath: '/project/$slug/logs'
      preLoaderRoute: typeof ProjectSlugLogsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/journal': {
      id: '/project/$slug/journal'
      path: '/journal'
      fullPath: '/project/$slug/journal'
      preLoaderRoute: typeof ProjectSlugJournalRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/issues': {
      id: '/project/$slug/issues'
      path: '/issues'
      fullPath: '/project/$slug/issues'
      preLoaderRoute: typeof ProjectSlugIssuesRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/goals': {
      id: '/project/$slug/goals'
      path: '/goals'
      fullPath: '/project/$slug/goals'
      preLoaderRoute: typeof ProjectSlugGoalsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/features': {
      id: '/project/$slug/features'
      path: '/features'
      fullPath: '/project/$slug/features'
      preLoaderRoute: typeof ProjectSlugFeaturesRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/errors': {
      id: '/project/$slug/errors'
      path: '/errors'
      fullPath: '/project/$slug/errors'
      preLoaderRoute: typeof ProjectSlugErrorsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/demos': {
      id: '/project/$slug/demos'
      path: '/demos'
      fullPath: '/project/$slug/demos'
      preLoaderRoute: typeof ProjectSlugDemosRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/counters': {
      id: '/project/$slug/counters'
      path: '/counters'
      fullPath: '/project/$slug/counters'
      preLoaderRoute: typeof ProjectSlugCountersRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/claude': {
      id: '/project/$slug/claude'
      path: '/claude'
      fullPath: '/project/$slug/claude'
      preLoaderRoute: typeof ProjectSlugClaudeRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/blocker-questions': {
      id: '/project/$slug/blocker-questions'
      path: '/blocker-questions'
      fullPath: '/project/$slug/blocker-questions'
      preLoaderRoute: typeof ProjectSlugBlockerQuestionsRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/themes/': {
      id: '/project/$slug/themes/'
      path: '/themes'
      fullPath: '/project/$slug/themes/'
      preLoaderRoute: typeof ProjectSlugThemesIndexRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/tests/': {
      id: '/project/$slug/tests/'
      path: '/'
      fullPath: '/project/$slug/tests/'
      preLoaderRoute: typeof ProjectSlugTestsIndexRouteImport
      parentRoute: typeof ProjectSlugTestsRoute
    }
    '/project/$slug/tasks/': {
      id: '/project/$slug/tasks/'
      path: '/'
      fullPath: '/project/$slug/tasks/'
      preLoaderRoute: typeof ProjectSlugTasksIndexRouteImport
      parentRoute: typeof ProjectSlugTasksRoute
    }
    '/project/$slug/questions/': {
      id: '/project/$slug/questions/'
      path: '/questions'
      fullPath: '/project/$slug/questions/'
      preLoaderRoute: typeof ProjectSlugQuestionsIndexRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/patterns/': {
      id: '/project/$slug/patterns/'
      path: '/'
      fullPath: '/project/$slug/patterns/'
      preLoaderRoute: typeof ProjectSlugPatternsIndexRouteImport
      parentRoute: typeof ProjectSlugPatternsRoute
    }
    '/project/$slug/issues/': {
      id: '/project/$slug/issues/'
      path: '/'
      fullPath: '/project/$slug/issues/'
      preLoaderRoute: typeof ProjectSlugIssuesIndexRouteImport
      parentRoute: typeof ProjectSlugIssuesRoute
    }
    '/project/$slug/goals/': {
      id: '/project/$slug/goals/'
      path: '/'
      fullPath: '/project/$slug/goals/'
      preLoaderRoute: typeof ProjectSlugGoalsIndexRouteImport
      parentRoute: typeof ProjectSlugGoalsRoute
    }
    '/project/$slug/features/': {
      id: '/project/$slug/features/'
      path: '/'
      fullPath: '/project/$slug/features/'
      preLoaderRoute: typeof ProjectSlugFeaturesIndexRouteImport
      parentRoute: typeof ProjectSlugFeaturesRoute
    }
    '/project/$slug/claude/': {
      id: '/project/$slug/claude/'
      path: '/'
      fullPath: '/project/$slug/claude/'
      preLoaderRoute: typeof ProjectSlugClaudeIndexRouteImport
      parentRoute: typeof ProjectSlugClaudeRoute
    }
    '/project/$slug/themes/$name': {
      id: '/project/$slug/themes/$name'
      path: '/themes/$name'
      fullPath: '/project/$slug/themes/$name'
      preLoaderRoute: typeof ProjectSlugThemesNameRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/tests/$id': {
      id: '/project/$slug/tests/$id'
      path: '/$id'
      fullPath: '/project/$slug/tests/$id'
      preLoaderRoute: typeof ProjectSlugTestsIdRouteImport
      parentRoute: typeof ProjectSlugTestsRoute
    }
    '/project/$slug/tasks/$id': {
      id: '/project/$slug/tasks/$id'
      path: '/$id'
      fullPath: '/project/$slug/tasks/$id'
      preLoaderRoute: typeof ProjectSlugTasksIdRouteImport
      parentRoute: typeof ProjectSlugTasksRoute
    }
    '/project/$slug/questions/$id': {
      id: '/project/$slug/questions/$id'
      path: '/questions/$id'
      fullPath: '/project/$slug/questions/$id'
      preLoaderRoute: typeof ProjectSlugQuestionsIdRouteImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/project/$slug/patterns/$id': {
      id: '/project/$slug/patterns/$id'
      path: '/$id'
      fullPath: '/project/$slug/patterns/$id'
      preLoaderRoute: typeof ProjectSlugPatternsIdRouteImport
      parentRoute: typeof ProjectSlugPatternsRoute
    }
    '/project/$slug/issues/$id': {
      id: '/project/$slug/issues/$id'
      path: '/$id'
      fullPath: '/project/$slug/issues/$id'
      preLoaderRoute: typeof ProjectSlugIssuesIdRouteImport
      parentRoute: typeof ProjectSlugIssuesRoute
    }
    '/project/$slug/features/$name': {
      id: '/project/$slug/features/$name'
      path: '/$name'
      fullPath: '/project/$slug/features/$name'
      preLoaderRoute: typeof ProjectSlugFeaturesNameRouteImport
      parentRoute: typeof ProjectSlugFeaturesRoute
    }
    '/project/$slug/claude/$sessionId': {
      id: '/project/$slug/claude/$sessionId'
      path: '/$sessionId'
      fullPath: '/project/$slug/claude/$sessionId'
      preLoaderRoute: typeof ProjectSlugClaudeSessionIdRouteImport
      parentRoute: typeof ProjectSlugClaudeRoute
    }
  }
}

interface ProjectSlugClaudeRouteChildren {
  ProjectSlugClaudeSessionIdRoute: typeof ProjectSlugClaudeSessionIdRoute
  ProjectSlugClaudeIndexRoute: typeof ProjectSlugClaudeIndexRoute
}

const ProjectSlugClaudeRouteChildren: ProjectSlugClaudeRouteChildren = {
  ProjectSlugClaudeSessionIdRoute: ProjectSlugClaudeSessionIdRoute,
  ProjectSlugClaudeIndexRoute: ProjectSlugClaudeIndexRoute,
}

const ProjectSlugClaudeRouteWithChildren =
  ProjectSlugClaudeRoute._addFileChildren(ProjectSlugClaudeRouteChildren)

interface ProjectSlugFeaturesRouteChildren {
  ProjectSlugFeaturesNameRoute: typeof ProjectSlugFeaturesNameRoute
  ProjectSlugFeaturesIndexRoute: typeof ProjectSlugFeaturesIndexRoute
}

const ProjectSlugFeaturesRouteChildren: ProjectSlugFeaturesRouteChildren = {
  ProjectSlugFeaturesNameRoute: ProjectSlugFeaturesNameRoute,
  ProjectSlugFeaturesIndexRoute: ProjectSlugFeaturesIndexRoute,
}

const ProjectSlugFeaturesRouteWithChildren =
  ProjectSlugFeaturesRoute._addFileChildren(ProjectSlugFeaturesRouteChildren)

interface ProjectSlugGoalsRouteChildren {
  ProjectSlugGoalsIndexRoute: typeof ProjectSlugGoalsIndexRoute
}

const ProjectSlugGoalsRouteChildren: ProjectSlugGoalsRouteChildren = {
  ProjectSlugGoalsIndexRoute: ProjectSlugGoalsIndexRoute,
}

const ProjectSlugGoalsRouteWithChildren =
  ProjectSlugGoalsRoute._addFileChildren(ProjectSlugGoalsRouteChildren)

interface ProjectSlugIssuesRouteChildren {
  ProjectSlugIssuesIdRoute: typeof ProjectSlugIssuesIdRoute
  ProjectSlugIssuesIndexRoute: typeof ProjectSlugIssuesIndexRoute
}

const ProjectSlugIssuesRouteChildren: ProjectSlugIssuesRouteChildren = {
  ProjectSlugIssuesIdRoute: ProjectSlugIssuesIdRoute,
  ProjectSlugIssuesIndexRoute: ProjectSlugIssuesIndexRoute,
}

const ProjectSlugIssuesRouteWithChildren =
  ProjectSlugIssuesRoute._addFileChildren(ProjectSlugIssuesRouteChildren)

interface ProjectSlugPatternsRouteChildren {
  ProjectSlugPatternsIdRoute: typeof ProjectSlugPatternsIdRoute
  ProjectSlugPatternsIndexRoute: typeof ProjectSlugPatternsIndexRoute
}

const ProjectSlugPatternsRouteChildren: ProjectSlugPatternsRouteChildren = {
  ProjectSlugPatternsIdRoute: ProjectSlugPatternsIdRoute,
  ProjectSlugPatternsIndexRoute: ProjectSlugPatternsIndexRoute,
}

const ProjectSlugPatternsRouteWithChildren =
  ProjectSlugPatternsRoute._addFileChildren(ProjectSlugPatternsRouteChildren)

interface ProjectSlugTasksRouteChildren {
  ProjectSlugTasksIdRoute: typeof ProjectSlugTasksIdRoute
  ProjectSlugTasksIndexRoute: typeof ProjectSlugTasksIndexRoute
}

const ProjectSlugTasksRouteChildren: ProjectSlugTasksRouteChildren = {
  ProjectSlugTasksIdRoute: ProjectSlugTasksIdRoute,
  ProjectSlugTasksIndexRoute: ProjectSlugTasksIndexRoute,
}

const ProjectSlugTasksRouteWithChildren =
  ProjectSlugTasksRoute._addFileChildren(ProjectSlugTasksRouteChildren)

interface ProjectSlugTestsRouteChildren {
  ProjectSlugTestsIdRoute: typeof ProjectSlugTestsIdRoute
  ProjectSlugTestsIndexRoute: typeof ProjectSlugTestsIndexRoute
}

const ProjectSlugTestsRouteChildren: ProjectSlugTestsRouteChildren = {
  ProjectSlugTestsIdRoute: ProjectSlugTestsIdRoute,
  ProjectSlugTestsIndexRoute: ProjectSlugTestsIndexRoute,
}

const ProjectSlugTestsRouteWithChildren =
  ProjectSlugTestsRoute._addFileChildren(ProjectSlugTestsRouteChildren)

interface ProjectSlugRouteChildren {
  ProjectSlugBlockerQuestionsRoute: typeof ProjectSlugBlockerQuestionsRoute
  ProjectSlugClaudeRoute: typeof ProjectSlugClaudeRouteWithChildren
  ProjectSlugCountersRoute: typeof ProjectSlugCountersRoute
  ProjectSlugDemosRoute: typeof ProjectSlugDemosRoute
  ProjectSlugErrorsRoute: typeof ProjectSlugErrorsRoute
  ProjectSlugFeaturesRoute: typeof ProjectSlugFeaturesRouteWithChildren
  ProjectSlugGoalsRoute: typeof ProjectSlugGoalsRouteWithChildren
  ProjectSlugIssuesRoute: typeof ProjectSlugIssuesRouteWithChildren
  ProjectSlugJournalRoute: typeof ProjectSlugJournalRoute
  ProjectSlugLogsRoute: typeof ProjectSlugLogsRoute
  ProjectSlugPatternsRoute: typeof ProjectSlugPatternsRouteWithChildren
  ProjectSlugProfileRoute: typeof ProjectSlugProfileRoute
  ProjectSlugQueueRoute: typeof ProjectSlugQueueRoute
  ProjectSlugSettingsRoute: typeof ProjectSlugSettingsRoute
  ProjectSlugTasksRoute: typeof ProjectSlugTasksRouteWithChildren
  ProjectSlugTestsRoute: typeof ProjectSlugTestsRouteWithChildren
  ProjectSlugTimingsRoute: typeof ProjectSlugTimingsRoute
  ProjectSlugWorklogRoute: typeof ProjectSlugWorklogRoute
  ProjectSlugIndexRoute: typeof ProjectSlugIndexRoute
  ProjectSlugQuestionsIdRoute: typeof ProjectSlugQuestionsIdRoute
  ProjectSlugThemesNameRoute: typeof ProjectSlugThemesNameRoute
  ProjectSlugQuestionsIndexRoute: typeof ProjectSlugQuestionsIndexRoute
  ProjectSlugThemesIndexRoute: typeof ProjectSlugThemesIndexRoute
}

const ProjectSlugRouteChildren: ProjectSlugRouteChildren = {
  ProjectSlugBlockerQuestionsRoute: ProjectSlugBlockerQuestionsRoute,
  ProjectSlugClaudeRoute: ProjectSlugClaudeRouteWithChildren,
  ProjectSlugCountersRoute: ProjectSlugCountersRoute,
  ProjectSlugDemosRoute: ProjectSlugDemosRoute,
  ProjectSlugErrorsRoute: ProjectSlugErrorsRoute,
  ProjectSlugFeaturesRoute: ProjectSlugFeaturesRouteWithChildren,
  ProjectSlugGoalsRoute: ProjectSlugGoalsRouteWithChildren,
  ProjectSlugIssuesRoute: ProjectSlugIssuesRouteWithChildren,
  ProjectSlugJournalRoute: ProjectSlugJournalRoute,
  ProjectSlugLogsRoute: ProjectSlugLogsRoute,
  ProjectSlugPatternsRoute: ProjectSlugPatternsRouteWithChildren,
  ProjectSlugProfileRoute: ProjectSlugProfileRoute,
  ProjectSlugQueueRoute: ProjectSlugQueueRoute,
  ProjectSlugSettingsRoute: ProjectSlugSettingsRoute,
  ProjectSlugTasksRoute: ProjectSlugTasksRouteWithChildren,
  ProjectSlugTestsRoute: ProjectSlugTestsRouteWithChildren,
  ProjectSlugTimingsRoute: ProjectSlugTimingsRoute,
  ProjectSlugWorklogRoute: ProjectSlugWorklogRoute,
  ProjectSlugIndexRoute: ProjectSlugIndexRoute,
  ProjectSlugQuestionsIdRoute: ProjectSlugQuestionsIdRoute,
  ProjectSlugThemesNameRoute: ProjectSlugThemesNameRoute,
  ProjectSlugQuestionsIndexRoute: ProjectSlugQuestionsIndexRoute,
  ProjectSlugThemesIndexRoute: ProjectSlugThemesIndexRoute,
}

const ProjectSlugRouteWithChildren = ProjectSlugRoute._addFileChildren(
  ProjectSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminLlmRoute: AdminLlmRoute,
  AdminUsersRoute: AdminUsersRoute,
  ProjectSlugRoute: ProjectSlugRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
