package agent

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"time"

	"github.com/iodesystems/zdx-go/internal/cli"
)

// claimedTodo is the wire shape returned by POST /api/dx/solo/claim (or
// /claim-any for global agents) and used by every code path that walks the
// claim/renew/release lifecycle. Lives in its own file rather than next to
// one provider so all providers can adopt atomic claims without an import
// cycle through claude.go.
type claimedTodo struct {
	ID              int32  `json:"id"`
	Text            string `json:"text"`
	Key             string `json:"key"`
	Kind            string `json:"kind"`
	TargetType      string `json:"target_type"`
	TargetID        string `json:"target_id"`
	IssueRef        string `json:"issue_ref"`
	TargetBranch    string `json:"target_branch,omitempty"`
	Priority        int32  `json:"priority"`
	ClaimedBy       string `json:"claimed_by"`
	ProjectSlug     string `json:"project_slug,omitempty"`
	ClaimBaseSha    string `json:"claim_base_sha,omitempty"`
	ClaimBaseBranch string `json:"claim_base_branch,omitempty"`
}

// claimNextTodo atomically reserves the next available todo for agentID via
// the server's solo claim endpoint (FOR UPDATE SKIP LOCKED on the DB side).
// Returns nil + nil error when no work is available so callers can sleep
// and retry without distinguishing "transport error" from "idle".
//
// Routing: when rc.slug is empty (global agent: srcless or DX_GLOBAL=1) the
// daemon hits /api/dx/solo/claim-any, which picks across every project
// ordered by project.priority then todo.priority. When rc.slug is set the
// daemon stays on the project-scoped /claim path. The wire response shape
// is identical (claim-any populates project_slug; /claim leaves it blank).
func claimNextTodo(rc remoteConfig, agentID string, leaseMinutes int32) (*claimedTodo, error) {
	var (
		path    string
		payload map[string]any
	)
	if rc.slug == "" {
		path = "/api/dx/solo/claim-any"
		payload = map[string]any{
			"agent_id":      agentID,
			"lease_minutes": leaseMinutes,
			"mode":          "autonomous",
		}
	} else {
		path = "/api/dx/solo/claim"
		payload = map[string]any{
			"slug":          rc.slug,
			"agent_id":      agentID,
			"lease_minutes": leaseMinutes,
			"mode":          "autonomous",
		}
	}
	body, _ := json.Marshal(payload)
	req, _ := http.NewRequest("POST", rc.url+path, bytes.NewReader(body))
	req.Header.Set("X-Api-Key", rc.key)
	req.Header.Set("Content-Type", "application/json")
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("claim HTTP %d", resp.StatusCode)
	}
	var todo claimedTodo
	if err := json.NewDecoder(resp.Body).Decode(&todo); err != nil {
		return nil, err
	}
	return &todo, nil
}

// renewTodoLease pushes the lease deadline forward so a long-running session
// retains its claim. Best-effort — failures are silent because the next tick
// will retry, and a single missed renewal won't break the session.
func renewTodoLease(rc remoteConfig, todoID int32, agentID string, leaseMinutes int32) {
	body, _ := json.Marshal(map[string]any{
		"id":            todoID,
		"agent_id":      agentID,
		"lease_minutes": leaseMinutes,
	})
	req, _ := http.NewRequest("POST", rc.url+"/api/dx/solo/renew", bytes.NewReader(body))
	req.Header.Set("X-Api-Key", rc.key)
	req.Header.Set("Content-Type", "application/json")
	resp, err := (&http.Client{Timeout: 10 * time.Second}).Do(req)
	if err == nil {
		resp.Body.Close()
	}
}

type releaseResult struct {
	ChurnDowngraded bool
	CycleDetected   bool
}

// releaseTodo posts the release/resolve call. The server may report:
//   - churn_downgraded: session had no mutations, resolve was downgraded to release
//   - cycle_detected: the resolved todo would be immediately regenerated by the queue,
//     indicating the agent cannot actually fix the underlying condition. Server auto-blocks.
func releaseTodo(rc remoteConfig, todoID int32, agentID, sessionID, claimBaseSHA, todoKind, claimBaseBranch string, resolve bool) releaseResult {
	body := map[string]any{
		"id":         todoID,
		"agent_id":   agentID,
		"resolve":    resolve,
		"session_id": sessionID,
	}
	if bs := cli.CollectBranchState(claimBaseSHA); bs != nil {
		body["branch_state"] = bs
		if resolve {
			if err := cli.ValidateBranchState(todoKind, bs, claimBaseSHA, claimBaseBranch); err != nil {
				fmt.Fprintf(os.Stderr, "branch contract violation: %v\ndowngrading resolve to release\n", err)
				body["resolve"] = false
			}
		}
	}
	encoded, _ := json.Marshal(body)
	req, _ := http.NewRequest("POST", rc.url+"/api/dx/solo/release", bytes.NewReader(encoded))
	req.Header.Set("X-Api-Key", rc.key)
	req.Header.Set("Content-Type", "application/json")
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil || resp == nil {
		return releaseResult{}
	}
	defer resp.Body.Close()
	var r struct {
		ChurnDowngraded bool `json:"churn_downgraded"`
		CycleDetected   bool `json:"cycle_detected"`
	}
	_ = json.NewDecoder(resp.Body).Decode(&r)
	return releaseResult{ChurnDowngraded: r.ChurnDowngraded, CycleDetected: r.CycleDetected}
}
