package doctor

import (
	"fmt"
	"strings"
)

// RenderDevCompose emits a starter docker-compose.dev.yml for the given stack.
// The output is opinionated — tweak after generation.
func RenderDevCompose(s Stack) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by `dx doctor --fix`. Tweak to taste.\n")
	b.WriteString("services:\n")
	b.WriteString("  dev:\n")
	b.WriteString("    build:\n")
	b.WriteString("      context: .\n")
	b.WriteString("      dockerfile: dev.Dockerfile\n")
	b.WriteString("    volumes:\n")
	b.WriteString("      - .:/workspace\n")

	var envVars []string
	var deps []string

	if s.HasPostgres {
		envVars = append(envVars, "DATABASE_URL=postgres://dev:dev@db:5432/dev")
		deps = append(deps, "db")
	}
	if s.HasValkey {
		envVars = append(envVars, "REDIS_URL=redis://valkey:6379")
		deps = append(deps, "valkey")
	}

	if len(envVars) > 0 {
		b.WriteString("    environment:\n")
		for _, e := range envVars {
			fmt.Fprintf(&b, "      - %s\n", e)
		}
	}

	if len(deps) > 0 {
		b.WriteString("    depends_on:\n")
		for _, d := range deps {
			fmt.Fprintf(&b, "      - %s\n", d)
		}
	}

	if s.HasPostgres {
		b.WriteString("  db:\n")
		b.WriteString("    image: pgvector/pgvector:pg16\n")
		b.WriteString("    environment:\n")
		b.WriteString("      - POSTGRES_USER=dev\n")
		b.WriteString("      - POSTGRES_PASSWORD=dev\n")
		b.WriteString("      - POSTGRES_DB=dev\n")
	}

	if s.HasValkey {
		b.WriteString("  valkey:\n")
		b.WriteString("    image: valkey/valkey:8\n")
	}

	return b.String()
}
