// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveBudgetPause = `-- name: GetActiveBudgetPause :one
SELECT id, agent_id, project_id, reason, paused_at, lifted_at, lifted_by FROM zdx_budget_pauses
WHERE agent_id = $1 AND lifted_at IS NULL
ORDER BY paused_at DESC
LIMIT 1
`

func (q *Queries) GetActiveBudgetPause(ctx context.Context, agentID string) (ZdxBudgetPause, error) {
	row := q.db.QueryRow(ctx, getActiveBudgetPause, agentID)
	var i ZdxBudgetPause
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ProjectID,
		&i.Reason,
		&i.PausedAt,
		&i.LiftedAt,
		&i.LiftedBy,
	)
	return i, err
}

const getAgentBudget = `-- name: GetAgentBudget :one
SELECT id, project_id, agent_id, token_ceiling, cost_ceiling, created_at, updated_at FROM zdx_agent_budgets WHERE agent_id = $1
`

func (q *Queries) GetAgentBudget(ctx context.Context, agentID pgtype.Text) (ZdxAgentBudget, error) {
	row := q.db.QueryRow(ctx, getAgentBudget, agentID)
	var i ZdxAgentBudget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TokenCeiling,
		&i.CostCeiling,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTokenUsage = `-- name: GetAgentTokenUsage :one
SELECT
  coalesce(sum((event_json->'message'->'usage'->>'input_tokens')::bigint), 0)::bigint           AS input_tokens,
  coalesce(sum((event_json->'message'->'usage'->>'output_tokens')::bigint), 0)::bigint          AS output_tokens,
  coalesce(sum((event_json->'message'->'usage'->>'cache_read_input_tokens')::bigint), 0)::bigint AS cache_read_input_tokens,
  coalesce(sum((event_json->'message'->'usage'->>'cache_creation_input_tokens')::bigint), 0)::bigint AS cache_creation_input_tokens
FROM zdx_claude_events
WHERE agent_id = $1
  AND event_type = 'assistant'
  AND event_json->'message'->'usage' IS NOT NULL
`

type GetAgentTokenUsageRow struct {
	InputTokens              int64 `db:"input_tokens" json:"input_tokens"`
	OutputTokens             int64 `db:"output_tokens" json:"output_tokens"`
	CacheReadInputTokens     int64 `db:"cache_read_input_tokens" json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64 `db:"cache_creation_input_tokens" json:"cache_creation_input_tokens"`
}

func (q *Queries) GetAgentTokenUsage(ctx context.Context, agentID string) (GetAgentTokenUsageRow, error) {
	row := q.db.QueryRow(ctx, getAgentTokenUsage, agentID)
	var i GetAgentTokenUsageRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadInputTokens,
		&i.CacheCreationInputTokens,
	)
	return i, err
}

const getProjectBudget = `-- name: GetProjectBudget :one
SELECT id, project_id, agent_id, token_ceiling, cost_ceiling, created_at, updated_at FROM zdx_agent_budgets WHERE project_id = $1 AND agent_id IS NULL
`

func (q *Queries) GetProjectBudget(ctx context.Context, projectID pgtype.Int4) (ZdxAgentBudget, error) {
	row := q.db.QueryRow(ctx, getProjectBudget, projectID)
	var i ZdxAgentBudget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TokenCeiling,
		&i.CostCeiling,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const liftBudgetPause = `-- name: LiftBudgetPause :exec
UPDATE zdx_budget_pauses
SET lifted_at = NOW(), lifted_by = $1
WHERE agent_id = $2 AND lifted_at IS NULL
`

type LiftBudgetPauseParams struct {
	LiftedBy pgtype.Text `db:"lifted_by" json:"lifted_by"`
	AgentID  string      `db:"agent_id" json:"agent_id"`
}

func (q *Queries) LiftBudgetPause(ctx context.Context, arg LiftBudgetPauseParams) error {
	_, err := q.db.Exec(ctx, liftBudgetPause, arg.LiftedBy, arg.AgentID)
	return err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, project_id, agent_id, token_ceiling, cost_ceiling, created_at, updated_at FROM zdx_agent_budgets ORDER BY id
`

func (q *Queries) ListBudgets(ctx context.Context) ([]ZdxAgentBudget, error) {
	rows, err := q.db.Query(ctx, listBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxAgentBudget
	for rows.Next() {
		var i ZdxAgentBudget
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.TokenCeiling,
			&i.CostCeiling,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBudgetPause = `-- name: RecordBudgetPause :one
INSERT INTO zdx_budget_pauses (agent_id, project_id, reason)
VALUES ($1, $2, $3)
RETURNING id, agent_id, project_id, reason, paused_at, lifted_at, lifted_by
`

type RecordBudgetPauseParams struct {
	AgentID   string      `db:"agent_id" json:"agent_id"`
	ProjectID pgtype.Int4 `db:"project_id" json:"project_id"`
	Reason    string      `db:"reason" json:"reason"`
}

func (q *Queries) RecordBudgetPause(ctx context.Context, arg RecordBudgetPauseParams) (ZdxBudgetPause, error) {
	row := q.db.QueryRow(ctx, recordBudgetPause, arg.AgentID, arg.ProjectID, arg.Reason)
	var i ZdxBudgetPause
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.ProjectID,
		&i.Reason,
		&i.PausedAt,
		&i.LiftedAt,
		&i.LiftedBy,
	)
	return i, err
}

const upsertAgentBudget = `-- name: UpsertAgentBudget :one
INSERT INTO zdx_agent_budgets (agent_id, token_ceiling, cost_ceiling)
VALUES ($1, $2, $3)
ON CONFLICT (agent_id) WHERE agent_id IS NOT NULL
DO UPDATE SET token_ceiling = EXCLUDED.token_ceiling,
             cost_ceiling   = EXCLUDED.cost_ceiling,
             updated_at     = NOW()
RETURNING id, project_id, agent_id, token_ceiling, cost_ceiling, created_at, updated_at
`

type UpsertAgentBudgetParams struct {
	AgentID      pgtype.Text   `db:"agent_id" json:"agent_id"`
	TokenCeiling pgtype.Int8   `db:"token_ceiling" json:"token_ceiling"`
	CostCeiling  pgtype.Float8 `db:"cost_ceiling" json:"cost_ceiling"`
}

func (q *Queries) UpsertAgentBudget(ctx context.Context, arg UpsertAgentBudgetParams) (ZdxAgentBudget, error) {
	row := q.db.QueryRow(ctx, upsertAgentBudget, arg.AgentID, arg.TokenCeiling, arg.CostCeiling)
	var i ZdxAgentBudget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TokenCeiling,
		&i.CostCeiling,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectBudget = `-- name: UpsertProjectBudget :one
INSERT INTO zdx_agent_budgets (project_id, token_ceiling, cost_ceiling)
VALUES ($1, $2, $3)
ON CONFLICT (project_id) WHERE project_id IS NOT NULL AND agent_id IS NULL
DO UPDATE SET token_ceiling = EXCLUDED.token_ceiling,
             cost_ceiling   = EXCLUDED.cost_ceiling,
             updated_at     = NOW()
RETURNING id, project_id, agent_id, token_ceiling, cost_ceiling, created_at, updated_at
`

type UpsertProjectBudgetParams struct {
	ProjectID    pgtype.Int4   `db:"project_id" json:"project_id"`
	TokenCeiling pgtype.Int8   `db:"token_ceiling" json:"token_ceiling"`
	CostCeiling  pgtype.Float8 `db:"cost_ceiling" json:"cost_ceiling"`
}

func (q *Queries) UpsertProjectBudget(ctx context.Context, arg UpsertProjectBudgetParams) (ZdxAgentBudget, error) {
	row := q.db.QueryRow(ctx, upsertProjectBudget, arg.ProjectID, arg.TokenCeiling, arg.CostCeiling)
	var i ZdxAgentBudget
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.TokenCeiling,
		&i.CostCeiling,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
