// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: atlas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAtlasChunk = `-- name: CreateAtlasChunk :one
INSERT INTO zdx_narrative_chunks (project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at
`

type CreateAtlasChunkParams struct {
	ProjectID    int32       `db:"project_id" json:"project_id"`
	NodeID       int64       `db:"node_id" json:"node_id"`
	CoderefID    pgtype.Int8 `db:"coderef_id" json:"coderef_id"`
	Title        string      `db:"title" json:"title"`
	Body         string      `db:"body" json:"body"`
	ShaAtWrite   string      `db:"sha_at_write" json:"sha_at_write"`
	VerifierKind string      `db:"verifier_kind" json:"verifier_kind"`
}

func (q *Queries) CreateAtlasChunk(ctx context.Context, arg CreateAtlasChunkParams) (ZdxNarrativeChunk, error) {
	row := q.db.QueryRow(ctx, createAtlasChunk,
		arg.ProjectID,
		arg.NodeID,
		arg.CoderefID,
		arg.Title,
		arg.Body,
		arg.ShaAtWrite,
		arg.VerifierKind,
	)
	var i ZdxNarrativeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NodeID,
		&i.CoderefID,
		&i.Title,
		&i.Body,
		&i.ShaAtWrite,
		&i.VerifierKind,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAtlasCoderef = `-- name: CreateAtlasCoderef :one
INSERT INTO zdx_coderefs (project_id, file, start_line, end_line, symbol, sha)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, file, start_line, end_line, symbol, sha, created_at
`

type CreateAtlasCoderefParams struct {
	ProjectID int32       `db:"project_id" json:"project_id"`
	File      string      `db:"file" json:"file"`
	StartLine pgtype.Int4 `db:"start_line" json:"start_line"`
	EndLine   pgtype.Int4 `db:"end_line" json:"end_line"`
	Symbol    string      `db:"symbol" json:"symbol"`
	Sha       string      `db:"sha" json:"sha"`
}

func (q *Queries) CreateAtlasCoderef(ctx context.Context, arg CreateAtlasCoderefParams) (ZdxCoderef, error) {
	row := q.db.QueryRow(ctx, createAtlasCoderef,
		arg.ProjectID,
		arg.File,
		arg.StartLine,
		arg.EndLine,
		arg.Symbol,
		arg.Sha,
	)
	var i ZdxCoderef
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.File,
		&i.StartLine,
		&i.EndLine,
		&i.Symbol,
		&i.Sha,
		&i.CreatedAt,
	)
	return i, err
}

const createAtlasEdge = `-- name: CreateAtlasEdge :one
INSERT INTO zdx_edges (project_id, from_node_id, to_node_id, edge_type, label, weight)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, from_node_id, to_node_id, edge_type, label, weight, created_at
`

type CreateAtlasEdgeParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	FromNodeID int64  `db:"from_node_id" json:"from_node_id"`
	ToNodeID   int64  `db:"to_node_id" json:"to_node_id"`
	EdgeType   string `db:"edge_type" json:"edge_type"`
	Label      string `db:"label" json:"label"`
	Weight     int32  `db:"weight" json:"weight"`
}

func (q *Queries) CreateAtlasEdge(ctx context.Context, arg CreateAtlasEdgeParams) (ZdxEdge, error) {
	row := q.db.QueryRow(ctx, createAtlasEdge,
		arg.ProjectID,
		arg.FromNodeID,
		arg.ToNodeID,
		arg.EdgeType,
		arg.Label,
		arg.Weight,
	)
	var i ZdxEdge
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromNodeID,
		&i.ToNodeID,
		&i.EdgeType,
		&i.Label,
		&i.Weight,
		&i.CreatedAt,
	)
	return i, err
}

const createAtlasNode = `-- name: CreateAtlasNode :one
INSERT INTO zdx_nodes (project_id, kind, slug, title, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, kind, slug, title, description, created_at, updated_at
`

type CreateAtlasNodeParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	Kind        string `db:"kind" json:"kind"`
	Slug        string `db:"slug" json:"slug"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateAtlasNode(ctx context.Context, arg CreateAtlasNodeParams) (ZdxNode, error) {
	row := q.db.QueryRow(ctx, createAtlasNode,
		arg.ProjectID,
		arg.Kind,
		arg.Slug,
		arg.Title,
		arg.Description,
	)
	var i ZdxNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAtlasChunk = `-- name: DeleteAtlasChunk :exec
DELETE FROM zdx_narrative_chunks WHERE project_id = $1 AND id = $2
`

type DeleteAtlasChunkParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteAtlasChunk(ctx context.Context, arg DeleteAtlasChunkParams) error {
	_, err := q.db.Exec(ctx, deleteAtlasChunk, arg.ProjectID, arg.ID)
	return err
}

const deleteAtlasEdge = `-- name: DeleteAtlasEdge :exec
DELETE FROM zdx_edges WHERE project_id = $1 AND id = $2
`

type DeleteAtlasEdgeParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteAtlasEdge(ctx context.Context, arg DeleteAtlasEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteAtlasEdge, arg.ProjectID, arg.ID)
	return err
}

const deleteAtlasNode = `-- name: DeleteAtlasNode :exec
DELETE FROM zdx_nodes WHERE project_id = $1 AND id = $2
`

type DeleteAtlasNodeParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteAtlasNode(ctx context.Context, arg DeleteAtlasNodeParams) error {
	_, err := q.db.Exec(ctx, deleteAtlasNode, arg.ProjectID, arg.ID)
	return err
}

const getAtlasChunk = `-- name: GetAtlasChunk :one
SELECT id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at FROM zdx_narrative_chunks WHERE project_id = $1 AND id = $2
`

type GetAtlasChunkParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetAtlasChunk(ctx context.Context, arg GetAtlasChunkParams) (ZdxNarrativeChunk, error) {
	row := q.db.QueryRow(ctx, getAtlasChunk, arg.ProjectID, arg.ID)
	var i ZdxNarrativeChunk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.NodeID,
		&i.CoderefID,
		&i.Title,
		&i.Body,
		&i.ShaAtWrite,
		&i.VerifierKind,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAtlasCoderef = `-- name: GetAtlasCoderef :one
SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 AND id = $2
`

type GetAtlasCoderefParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetAtlasCoderef(ctx context.Context, arg GetAtlasCoderefParams) (ZdxCoderef, error) {
	row := q.db.QueryRow(ctx, getAtlasCoderef, arg.ProjectID, arg.ID)
	var i ZdxCoderef
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.File,
		&i.StartLine,
		&i.EndLine,
		&i.Symbol,
		&i.Sha,
		&i.CreatedAt,
	)
	return i, err
}

const getAtlasNode = `-- name: GetAtlasNode :one
SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes WHERE project_id = $1 AND kind = $2 AND slug = $3
`

type GetAtlasNodeParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Kind      string `db:"kind" json:"kind"`
	Slug      string `db:"slug" json:"slug"`
}

func (q *Queries) GetAtlasNode(ctx context.Context, arg GetAtlasNodeParams) (ZdxNode, error) {
	row := q.db.QueryRow(ctx, getAtlasNode, arg.ProjectID, arg.Kind, arg.Slug)
	var i ZdxNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAtlasNodeByID = `-- name: GetAtlasNodeByID :one
SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes WHERE project_id = $1 AND id = $2
`

type GetAtlasNodeByIDParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int64 `db:"id" json:"id"`
}

func (q *Queries) GetAtlasNodeByID(ctx context.Context, arg GetAtlasNodeByIDParams) (ZdxNode, error) {
	row := q.db.QueryRow(ctx, getAtlasNodeByID, arg.ProjectID, arg.ID)
	var i ZdxNode
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAtlasChunks = `-- name: ListAtlasChunks :many
SELECT id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at FROM zdx_narrative_chunks WHERE node_id = $1 ORDER BY id
`

func (q *Queries) ListAtlasChunks(ctx context.Context, nodeID int64) ([]ZdxNarrativeChunk, error) {
	rows, err := q.db.Query(ctx, listAtlasChunks, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxNarrativeChunk
	for rows.Next() {
		var i ZdxNarrativeChunk
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.NodeID,
			&i.CoderefID,
			&i.Title,
			&i.Body,
			&i.ShaAtWrite,
			&i.VerifierKind,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtlasCoderefs = `-- name: ListAtlasCoderefs :many
SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 ORDER BY id DESC
`

func (q *Queries) ListAtlasCoderefs(ctx context.Context, projectID int32) ([]ZdxCoderef, error) {
	rows, err := q.db.Query(ctx, listAtlasCoderefs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxCoderef
	for rows.Next() {
		var i ZdxCoderef
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Sha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtlasCoderefsByFile = `-- name: ListAtlasCoderefsByFile :many
SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 AND file = $2 ORDER BY id DESC
`

type ListAtlasCoderefsByFileParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	File      string `db:"file" json:"file"`
}

func (q *Queries) ListAtlasCoderefsByFile(ctx context.Context, arg ListAtlasCoderefsByFileParams) ([]ZdxCoderef, error) {
	rows, err := q.db.Query(ctx, listAtlasCoderefsByFile, arg.ProjectID, arg.File)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxCoderef
	for rows.Next() {
		var i ZdxCoderef
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.File,
			&i.StartLine,
			&i.EndLine,
			&i.Symbol,
			&i.Sha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtlasEdgesFrom = `-- name: ListAtlasEdgesFrom :many
SELECT e.id, e.project_id, e.from_node_id, e.to_node_id, e.edge_type, e.label, e.weight, e.created_at, n.kind AS to_kind, n.slug AS to_slug
FROM zdx_edges e
JOIN zdx_nodes n ON n.id = e.to_node_id
WHERE e.from_node_id = $1
ORDER BY e.id
`

type ListAtlasEdgesFromRow struct {
	ID         int64              `db:"id" json:"id"`
	ProjectID  int32              `db:"project_id" json:"project_id"`
	FromNodeID int64              `db:"from_node_id" json:"from_node_id"`
	ToNodeID   int64              `db:"to_node_id" json:"to_node_id"`
	EdgeType   string             `db:"edge_type" json:"edge_type"`
	Label      string             `db:"label" json:"label"`
	Weight     int32              `db:"weight" json:"weight"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ToKind     string             `db:"to_kind" json:"to_kind"`
	ToSlug     string             `db:"to_slug" json:"to_slug"`
}

func (q *Queries) ListAtlasEdgesFrom(ctx context.Context, fromNodeID int64) ([]ListAtlasEdgesFromRow, error) {
	rows, err := q.db.Query(ctx, listAtlasEdgesFrom, fromNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAtlasEdgesFromRow
	for rows.Next() {
		var i ListAtlasEdgesFromRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.Label,
			&i.Weight,
			&i.CreatedAt,
			&i.ToKind,
			&i.ToSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtlasEdgesTo = `-- name: ListAtlasEdgesTo :many
SELECT id, project_id, from_node_id, to_node_id, edge_type, label, weight, created_at FROM zdx_edges WHERE to_node_id = $1 ORDER BY id
`

func (q *Queries) ListAtlasEdgesTo(ctx context.Context, toNodeID int64) ([]ZdxEdge, error) {
	rows, err := q.db.Query(ctx, listAtlasEdgesTo, toNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxEdge
	for rows.Next() {
		var i ZdxEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.FromNodeID,
			&i.ToNodeID,
			&i.EdgeType,
			&i.Label,
			&i.Weight,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAtlasNodes = `-- name: ListAtlasNodes :many
SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes
WHERE project_id = $1
  AND ($2::text = '' OR kind = $2)
ORDER BY kind, slug
`

type ListAtlasNodesParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Kind      string `db:"kind" json:"kind"`
}

func (q *Queries) ListAtlasNodes(ctx context.Context, arg ListAtlasNodesParams) ([]ZdxNode, error) {
	rows, err := q.db.Query(ctx, listAtlasNodes, arg.ProjectID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxNode
	for rows.Next() {
		var i ZdxNode
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAtlasChunk = `-- name: UpdateAtlasChunk :exec
UPDATE zdx_narrative_chunks
SET title        = COALESCE(NULLIF($1, ''), title),
    body         = COALESCE(NULLIF($2, ''), body),
    sha_at_write = COALESCE(NULLIF($3, ''), sha_at_write),
    updated_at   = NOW()
WHERE project_id = $4 AND id = $5
`

type UpdateAtlasChunkParams struct {
	Title      interface{} `db:"title" json:"title"`
	Body       interface{} `db:"body" json:"body"`
	ShaAtWrite interface{} `db:"sha_at_write" json:"sha_at_write"`
	ProjectID  int32       `db:"project_id" json:"project_id"`
	ID         int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateAtlasChunk(ctx context.Context, arg UpdateAtlasChunkParams) error {
	_, err := q.db.Exec(ctx, updateAtlasChunk,
		arg.Title,
		arg.Body,
		arg.ShaAtWrite,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const updateAtlasNode = `-- name: UpdateAtlasNode :exec
UPDATE zdx_nodes
SET title       = COALESCE(NULLIF($1, ''), title),
    description = COALESCE(NULLIF($2, ''), description),
    updated_at  = NOW()
WHERE project_id = $3 AND id = $4
`

type UpdateAtlasNodeParams struct {
	Title       interface{} `db:"title" json:"title"`
	Description interface{} `db:"description" json:"description"`
	ProjectID   int32       `db:"project_id" json:"project_id"`
	ID          int64       `db:"id" json:"id"`
}

func (q *Queries) UpdateAtlasNode(ctx context.Context, arg UpdateAtlasNodeParams) error {
	_, err := q.db.Exec(ctx, updateAtlasNode,
		arg.Title,
		arg.Description,
		arg.ProjectID,
		arg.ID,
	)
	return err
}
