// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: atlas.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCreateAtlasChunk = metaquery.Query{
	Name:   "CreateAtlasChunk",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL: `INSERT INTO zdx_narrative_chunks (project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "node_id", OriginalName: "node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "coderef_id", OriginalName: "coderef_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_narrative_chunks"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "body", OriginalName: "body", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "sha_at_write", OriginalName: "sha_at_write", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verifier_kind", OriginalName: "verifier_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verified_at", OriginalName: "verified_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_narrative_chunks"},
		{Name: "verified_by", OriginalName: "verified_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
		{Position: 3, Name: "coderef_id", GoType: "pgtype.Int8", DBType: "pg_catalog.int8"},
		{Position: 4, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "body", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "sha_at_write", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "verifier_kind", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_narrative_chunks"},
}

// WrapCreateAtlasChunk returns a metaquery.Builder over MetaCreateAtlasChunk, pre-bound with typed arguments.
func WrapCreateAtlasChunk(arg CreateAtlasChunkParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateAtlasChunk, arg.ProjectID, arg.NodeID, arg.CoderefID, arg.Title, arg.Body, arg.ShaAtWrite, arg.VerifierKind)
}

// CreateAtlasChunkCols gives typed, name-safe access to CreateAtlasChunk's output columns.
var CreateAtlasChunkCols = struct {
	ID           metaquery.IntCol
	ProjectID    metaquery.IntCol
	NodeID       metaquery.IntCol
	CoderefID    metaquery.IntCol
	Title        metaquery.TextCol
	Body         metaquery.TextCol
	ShaAtWrite   metaquery.TextCol
	VerifierKind metaquery.TextCol
	VerifiedAt   metaquery.TimeCol
	VerifiedBy   metaquery.TextCol
	CreatedAt    metaquery.TimeCol
	UpdatedAt    metaquery.TimeCol
}{
	ID:           metaquery.NewIntCol("id"),
	ProjectID:    metaquery.NewIntCol("project_id"),
	NodeID:       metaquery.NewIntCol("node_id"),
	CoderefID:    metaquery.NewIntCol("coderef_id"),
	Title:        metaquery.NewTextCol("title"),
	Body:         metaquery.NewTextCol("body"),
	ShaAtWrite:   metaquery.NewTextCol("sha_at_write"),
	VerifierKind: metaquery.NewTextCol("verifier_kind"),
	VerifiedAt:   metaquery.NewTimeCol("verified_at"),
	VerifiedBy:   metaquery.NewTextCol("verified_by"),
	CreatedAt:    metaquery.NewTimeCol("created_at"),
	UpdatedAt:    metaquery.NewTimeCol("updated_at"),
}

var MetaCreateAtlasCoderef = metaquery.Query{
	Name:   "CreateAtlasCoderef",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL: `INSERT INTO zdx_coderefs (project_id, file, start_line, end_line, symbol, sha)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, file, start_line, end_line, symbol, sha, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_coderefs"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_coderefs"},
		{Name: "file", OriginalName: "file", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "start_line", OriginalName: "start_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "end_line", OriginalName: "end_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "symbol", OriginalName: "symbol", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "sha", OriginalName: "sha", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_coderefs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "file", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "start_line", GoType: "pgtype.Int4", DBType: "pg_catalog.int4"},
		{Position: 4, Name: "end_line", GoType: "pgtype.Int4", DBType: "pg_catalog.int4"},
		{Position: 5, Name: "symbol", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "sha", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_coderefs"},
}

// WrapCreateAtlasCoderef returns a metaquery.Builder over MetaCreateAtlasCoderef, pre-bound with typed arguments.
func WrapCreateAtlasCoderef(arg CreateAtlasCoderefParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateAtlasCoderef, arg.ProjectID, arg.File, arg.StartLine, arg.EndLine, arg.Symbol, arg.Sha)
}

// CreateAtlasCoderefCols gives typed, name-safe access to CreateAtlasCoderef's output columns.
var CreateAtlasCoderefCols = struct {
	ID        metaquery.IntCol
	ProjectID metaquery.IntCol
	File      metaquery.TextCol
	StartLine metaquery.IntCol
	EndLine   metaquery.IntCol
	Symbol    metaquery.TextCol
	Sha       metaquery.TextCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	ProjectID: metaquery.NewIntCol("project_id"),
	File:      metaquery.NewTextCol("file"),
	StartLine: metaquery.NewIntCol("start_line"),
	EndLine:   metaquery.NewIntCol("end_line"),
	Symbol:    metaquery.NewTextCol("symbol"),
	Sha:       metaquery.NewTextCol("sha"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaCreateAtlasEdge = metaquery.Query{
	Name:   "CreateAtlasEdge",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL: `INSERT INTO zdx_edges (project_id, from_node_id, to_node_id, edge_type, label, weight)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, from_node_id, to_node_id, edge_type, label, weight, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "from_node_id", OriginalName: "from_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "to_node_id", OriginalName: "to_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "edge_type", OriginalName: "edge_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "label", OriginalName: "label", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "weight", OriginalName: "weight", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_edges"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "from_node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
		{Position: 3, Name: "to_node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
		{Position: 4, Name: "edge_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "label", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "weight", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_edges"},
}

// WrapCreateAtlasEdge returns a metaquery.Builder over MetaCreateAtlasEdge, pre-bound with typed arguments.
func WrapCreateAtlasEdge(arg CreateAtlasEdgeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateAtlasEdge, arg.ProjectID, arg.FromNodeID, arg.ToNodeID, arg.EdgeType, arg.Label, arg.Weight)
}

// CreateAtlasEdgeCols gives typed, name-safe access to CreateAtlasEdge's output columns.
var CreateAtlasEdgeCols = struct {
	ID         metaquery.IntCol
	ProjectID  metaquery.IntCol
	FromNodeID metaquery.IntCol
	ToNodeID   metaquery.IntCol
	EdgeType   metaquery.TextCol
	Label      metaquery.TextCol
	Weight     metaquery.IntCol
	CreatedAt  metaquery.TimeCol
}{
	ID:         metaquery.NewIntCol("id"),
	ProjectID:  metaquery.NewIntCol("project_id"),
	FromNodeID: metaquery.NewIntCol("from_node_id"),
	ToNodeID:   metaquery.NewIntCol("to_node_id"),
	EdgeType:   metaquery.NewTextCol("edge_type"),
	Label:      metaquery.NewTextCol("label"),
	Weight:     metaquery.NewIntCol("weight"),
	CreatedAt:  metaquery.NewTimeCol("created_at"),
}

var MetaCreateAtlasNode = metaquery.Query{
	Name:   "CreateAtlasNode",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL: `INSERT INTO zdx_nodes (project_id, kind, slug, title, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, kind, slug, title, description, created_at, updated_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_nodes"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_nodes"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "slug", OriginalName: "slug", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "kind", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "slug", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "description", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_nodes"},
}

// WrapCreateAtlasNode returns a metaquery.Builder over MetaCreateAtlasNode, pre-bound with typed arguments.
func WrapCreateAtlasNode(arg CreateAtlasNodeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateAtlasNode, arg.ProjectID, arg.Kind, arg.Slug, arg.Title, arg.Description)
}

// CreateAtlasNodeCols gives typed, name-safe access to CreateAtlasNode's output columns.
var CreateAtlasNodeCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Kind        metaquery.TextCol
	Slug        metaquery.TextCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Kind:        metaquery.NewTextCol("kind"),
	Slug:        metaquery.NewTextCol("slug"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaDeleteAtlasChunk = metaquery.Query{
	Name:   "DeleteAtlasChunk",
	Cmd:    ":exec",
	Source: "atlas.sql",
	SQL:    `DELETE FROM zdx_narrative_chunks WHERE project_id = $1 AND id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapDeleteAtlasChunk returns a metaquery.Builder over MetaDeleteAtlasChunk, pre-bound with typed arguments.
func WrapDeleteAtlasChunk(arg DeleteAtlasChunkParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteAtlasChunk, arg.ProjectID, arg.ID)
}

var MetaDeleteAtlasEdge = metaquery.Query{
	Name:   "DeleteAtlasEdge",
	Cmd:    ":exec",
	Source: "atlas.sql",
	SQL:    `DELETE FROM zdx_edges WHERE project_id = $1 AND id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapDeleteAtlasEdge returns a metaquery.Builder over MetaDeleteAtlasEdge, pre-bound with typed arguments.
func WrapDeleteAtlasEdge(arg DeleteAtlasEdgeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteAtlasEdge, arg.ProjectID, arg.ID)
}

var MetaDeleteAtlasNode = metaquery.Query{
	Name:   "DeleteAtlasNode",
	Cmd:    ":exec",
	Source: "atlas.sql",
	SQL:    `DELETE FROM zdx_nodes WHERE project_id = $1 AND id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapDeleteAtlasNode returns a metaquery.Builder over MetaDeleteAtlasNode, pre-bound with typed arguments.
func WrapDeleteAtlasNode(arg DeleteAtlasNodeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteAtlasNode, arg.ProjectID, arg.ID)
}

var MetaGetAtlasChunk = metaquery.Query{
	Name:   "GetAtlasChunk",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at FROM zdx_narrative_chunks WHERE project_id = $1 AND id = $2`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "node_id", OriginalName: "node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "coderef_id", OriginalName: "coderef_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_narrative_chunks"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "body", OriginalName: "body", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "sha_at_write", OriginalName: "sha_at_write", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verifier_kind", OriginalName: "verifier_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verified_at", OriginalName: "verified_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_narrative_chunks"},
		{Name: "verified_by", OriginalName: "verified_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapGetAtlasChunk returns a metaquery.Builder over MetaGetAtlasChunk, pre-bound with typed arguments.
func WrapGetAtlasChunk(arg GetAtlasChunkParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetAtlasChunk, arg.ProjectID, arg.ID)
}

// GetAtlasChunkCols gives typed, name-safe access to GetAtlasChunk's output columns.
var GetAtlasChunkCols = struct {
	ID           metaquery.IntCol
	ProjectID    metaquery.IntCol
	NodeID       metaquery.IntCol
	CoderefID    metaquery.IntCol
	Title        metaquery.TextCol
	Body         metaquery.TextCol
	ShaAtWrite   metaquery.TextCol
	VerifierKind metaquery.TextCol
	VerifiedAt   metaquery.TimeCol
	VerifiedBy   metaquery.TextCol
	CreatedAt    metaquery.TimeCol
	UpdatedAt    metaquery.TimeCol
}{
	ID:           metaquery.NewIntCol("id"),
	ProjectID:    metaquery.NewIntCol("project_id"),
	NodeID:       metaquery.NewIntCol("node_id"),
	CoderefID:    metaquery.NewIntCol("coderef_id"),
	Title:        metaquery.NewTextCol("title"),
	Body:         metaquery.NewTextCol("body"),
	ShaAtWrite:   metaquery.NewTextCol("sha_at_write"),
	VerifierKind: metaquery.NewTextCol("verifier_kind"),
	VerifiedAt:   metaquery.NewTimeCol("verified_at"),
	VerifiedBy:   metaquery.NewTextCol("verified_by"),
	CreatedAt:    metaquery.NewTimeCol("created_at"),
	UpdatedAt:    metaquery.NewTimeCol("updated_at"),
}

var MetaGetAtlasCoderef = metaquery.Query{
	Name:   "GetAtlasCoderef",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 AND id = $2`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_coderefs"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_coderefs"},
		{Name: "file", OriginalName: "file", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "start_line", OriginalName: "start_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "end_line", OriginalName: "end_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "symbol", OriginalName: "symbol", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "sha", OriginalName: "sha", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_coderefs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapGetAtlasCoderef returns a metaquery.Builder over MetaGetAtlasCoderef, pre-bound with typed arguments.
func WrapGetAtlasCoderef(arg GetAtlasCoderefParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetAtlasCoderef, arg.ProjectID, arg.ID)
}

// GetAtlasCoderefCols gives typed, name-safe access to GetAtlasCoderef's output columns.
var GetAtlasCoderefCols = struct {
	ID        metaquery.IntCol
	ProjectID metaquery.IntCol
	File      metaquery.TextCol
	StartLine metaquery.IntCol
	EndLine   metaquery.IntCol
	Symbol    metaquery.TextCol
	Sha       metaquery.TextCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	ProjectID: metaquery.NewIntCol("project_id"),
	File:      metaquery.NewTextCol("file"),
	StartLine: metaquery.NewIntCol("start_line"),
	EndLine:   metaquery.NewIntCol("end_line"),
	Symbol:    metaquery.NewTextCol("symbol"),
	Sha:       metaquery.NewTextCol("sha"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaGetAtlasNode = metaquery.Query{
	Name:   "GetAtlasNode",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes WHERE project_id = $1 AND kind = $2 AND slug = $3`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_nodes"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_nodes"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "slug", OriginalName: "slug", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "kind", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "slug", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapGetAtlasNode returns a metaquery.Builder over MetaGetAtlasNode, pre-bound with typed arguments.
func WrapGetAtlasNode(arg GetAtlasNodeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetAtlasNode, arg.ProjectID, arg.Kind, arg.Slug)
}

// GetAtlasNodeCols gives typed, name-safe access to GetAtlasNode's output columns.
var GetAtlasNodeCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Kind        metaquery.TextCol
	Slug        metaquery.TextCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Kind:        metaquery.NewTextCol("kind"),
	Slug:        metaquery.NewTextCol("slug"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaGetAtlasNodeByID = metaquery.Query{
	Name:   "GetAtlasNodeByID",
	Cmd:    ":one",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes WHERE project_id = $1 AND id = $2`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_nodes"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_nodes"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "slug", OriginalName: "slug", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapGetAtlasNodeByID returns a metaquery.Builder over MetaGetAtlasNodeByID, pre-bound with typed arguments.
func WrapGetAtlasNodeByID(arg GetAtlasNodeByIDParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetAtlasNodeByID, arg.ProjectID, arg.ID)
}

// GetAtlasNodeByIDCols gives typed, name-safe access to GetAtlasNodeByID's output columns.
var GetAtlasNodeByIDCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Kind        metaquery.TextCol
	Slug        metaquery.TextCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Kind:        metaquery.NewTextCol("kind"),
	Slug:        metaquery.NewTextCol("slug"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaListAtlasChunks = metaquery.Query{
	Name:   "ListAtlasChunks",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, node_id, coderef_id, title, body, sha_at_write, verifier_kind, verified_at, verified_by, created_at, updated_at FROM zdx_narrative_chunks WHERE node_id = $1 ORDER BY id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "node_id", OriginalName: "node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "coderef_id", OriginalName: "coderef_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_narrative_chunks"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "body", OriginalName: "body", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "sha_at_write", OriginalName: "sha_at_write", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verifier_kind", OriginalName: "verifier_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "verified_at", OriginalName: "verified_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_narrative_chunks"},
		{Name: "verified_by", OriginalName: "verified_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_narrative_chunks"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapListAtlasChunks returns a metaquery.Builder over MetaListAtlasChunks, pre-bound with typed arguments.
func WrapListAtlasChunks(nodeID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasChunks, nodeID)
}

// ListAtlasChunksCols gives typed, name-safe access to ListAtlasChunks's output columns.
var ListAtlasChunksCols = struct {
	ID           metaquery.IntCol
	ProjectID    metaquery.IntCol
	NodeID       metaquery.IntCol
	CoderefID    metaquery.IntCol
	Title        metaquery.TextCol
	Body         metaquery.TextCol
	ShaAtWrite   metaquery.TextCol
	VerifierKind metaquery.TextCol
	VerifiedAt   metaquery.TimeCol
	VerifiedBy   metaquery.TextCol
	CreatedAt    metaquery.TimeCol
	UpdatedAt    metaquery.TimeCol
}{
	ID:           metaquery.NewIntCol("id"),
	ProjectID:    metaquery.NewIntCol("project_id"),
	NodeID:       metaquery.NewIntCol("node_id"),
	CoderefID:    metaquery.NewIntCol("coderef_id"),
	Title:        metaquery.NewTextCol("title"),
	Body:         metaquery.NewTextCol("body"),
	ShaAtWrite:   metaquery.NewTextCol("sha_at_write"),
	VerifierKind: metaquery.NewTextCol("verifier_kind"),
	VerifiedAt:   metaquery.NewTimeCol("verified_at"),
	VerifiedBy:   metaquery.NewTextCol("verified_by"),
	CreatedAt:    metaquery.NewTimeCol("created_at"),
	UpdatedAt:    metaquery.NewTimeCol("updated_at"),
}

var MetaListAtlasCoderefs = metaquery.Query{
	Name:   "ListAtlasCoderefs",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 ORDER BY id DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_coderefs"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_coderefs"},
		{Name: "file", OriginalName: "file", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "start_line", OriginalName: "start_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "end_line", OriginalName: "end_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "symbol", OriginalName: "symbol", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "sha", OriginalName: "sha", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_coderefs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapListAtlasCoderefs returns a metaquery.Builder over MetaListAtlasCoderefs, pre-bound with typed arguments.
func WrapListAtlasCoderefs(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasCoderefs, projectID)
}

// ListAtlasCoderefsCols gives typed, name-safe access to ListAtlasCoderefs's output columns.
var ListAtlasCoderefsCols = struct {
	ID        metaquery.IntCol
	ProjectID metaquery.IntCol
	File      metaquery.TextCol
	StartLine metaquery.IntCol
	EndLine   metaquery.IntCol
	Symbol    metaquery.TextCol
	Sha       metaquery.TextCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	ProjectID: metaquery.NewIntCol("project_id"),
	File:      metaquery.NewTextCol("file"),
	StartLine: metaquery.NewIntCol("start_line"),
	EndLine:   metaquery.NewIntCol("end_line"),
	Symbol:    metaquery.NewTextCol("symbol"),
	Sha:       metaquery.NewTextCol("sha"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaListAtlasCoderefsByFile = metaquery.Query{
	Name:   "ListAtlasCoderefsByFile",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, file, start_line, end_line, symbol, sha, created_at FROM zdx_coderefs WHERE project_id = $1 AND file = $2 ORDER BY id DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_coderefs"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_coderefs"},
		{Name: "file", OriginalName: "file", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "start_line", OriginalName: "start_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "end_line", OriginalName: "end_line", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_coderefs"},
		{Name: "symbol", OriginalName: "symbol", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "sha", OriginalName: "sha", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_coderefs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_coderefs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "file", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListAtlasCoderefsByFile returns a metaquery.Builder over MetaListAtlasCoderefsByFile, pre-bound with typed arguments.
func WrapListAtlasCoderefsByFile(arg ListAtlasCoderefsByFileParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasCoderefsByFile, arg.ProjectID, arg.File)
}

// ListAtlasCoderefsByFileCols gives typed, name-safe access to ListAtlasCoderefsByFile's output columns.
var ListAtlasCoderefsByFileCols = struct {
	ID        metaquery.IntCol
	ProjectID metaquery.IntCol
	File      metaquery.TextCol
	StartLine metaquery.IntCol
	EndLine   metaquery.IntCol
	Symbol    metaquery.TextCol
	Sha       metaquery.TextCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	ProjectID: metaquery.NewIntCol("project_id"),
	File:      metaquery.NewTextCol("file"),
	StartLine: metaquery.NewIntCol("start_line"),
	EndLine:   metaquery.NewIntCol("end_line"),
	Symbol:    metaquery.NewTextCol("symbol"),
	Sha:       metaquery.NewTextCol("sha"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaListAtlasEdgesFrom = metaquery.Query{
	Name:   "ListAtlasEdgesFrom",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL: `SELECT e.id, e.project_id, e.from_node_id, e.to_node_id, e.edge_type, e.label, e.weight, e.created_at, n.kind AS to_kind, n.slug AS to_slug
FROM zdx_edges e
JOIN zdx_nodes n ON n.id = e.to_node_id
WHERE e.from_node_id = $1
ORDER BY e.id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "from_node_id", OriginalName: "from_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "to_node_id", OriginalName: "to_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "edge_type", OriginalName: "edge_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "label", OriginalName: "label", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "weight", OriginalName: "weight", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_edges"},
		{Name: "to_kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "to_slug", OriginalName: "slug", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "from_node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapListAtlasEdgesFrom returns a metaquery.Builder over MetaListAtlasEdgesFrom, pre-bound with typed arguments.
func WrapListAtlasEdgesFrom(fromNodeID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasEdgesFrom, fromNodeID)
}

// ListAtlasEdgesFromCols gives typed, name-safe access to ListAtlasEdgesFrom's output columns.
var ListAtlasEdgesFromCols = struct {
	ID         metaquery.IntCol
	ProjectID  metaquery.IntCol
	FromNodeID metaquery.IntCol
	ToNodeID   metaquery.IntCol
	EdgeType   metaquery.TextCol
	Label      metaquery.TextCol
	Weight     metaquery.IntCol
	CreatedAt  metaquery.TimeCol
	ToKind     metaquery.TextCol
	ToSlug     metaquery.TextCol
}{
	ID:         metaquery.NewIntCol("id"),
	ProjectID:  metaquery.NewIntCol("project_id"),
	FromNodeID: metaquery.NewIntCol("from_node_id"),
	ToNodeID:   metaquery.NewIntCol("to_node_id"),
	EdgeType:   metaquery.NewTextCol("edge_type"),
	Label:      metaquery.NewTextCol("label"),
	Weight:     metaquery.NewIntCol("weight"),
	CreatedAt:  metaquery.NewTimeCol("created_at"),
	ToKind:     metaquery.NewTextCol("kind"),
	ToSlug:     metaquery.NewTextCol("slug"),
}

var MetaListAtlasEdgesTo = metaquery.Query{
	Name:   "ListAtlasEdgesTo",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL:    `SELECT id, project_id, from_node_id, to_node_id, edge_type, label, weight, created_at FROM zdx_edges WHERE to_node_id = $1 ORDER BY id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "from_node_id", OriginalName: "from_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "to_node_id", OriginalName: "to_node_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_edges"},
		{Name: "edge_type", OriginalName: "edge_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "label", OriginalName: "label", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_edges"},
		{Name: "weight", OriginalName: "weight", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_edges"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_edges"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "to_node_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapListAtlasEdgesTo returns a metaquery.Builder over MetaListAtlasEdgesTo, pre-bound with typed arguments.
func WrapListAtlasEdgesTo(toNodeID int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasEdgesTo, toNodeID)
}

// ListAtlasEdgesToCols gives typed, name-safe access to ListAtlasEdgesTo's output columns.
var ListAtlasEdgesToCols = struct {
	ID         metaquery.IntCol
	ProjectID  metaquery.IntCol
	FromNodeID metaquery.IntCol
	ToNodeID   metaquery.IntCol
	EdgeType   metaquery.TextCol
	Label      metaquery.TextCol
	Weight     metaquery.IntCol
	CreatedAt  metaquery.TimeCol
}{
	ID:         metaquery.NewIntCol("id"),
	ProjectID:  metaquery.NewIntCol("project_id"),
	FromNodeID: metaquery.NewIntCol("from_node_id"),
	ToNodeID:   metaquery.NewIntCol("to_node_id"),
	EdgeType:   metaquery.NewTextCol("edge_type"),
	Label:      metaquery.NewTextCol("label"),
	Weight:     metaquery.NewIntCol("weight"),
	CreatedAt:  metaquery.NewTimeCol("created_at"),
}

var MetaListAtlasNodes = metaquery.Query{
	Name:   "ListAtlasNodes",
	Cmd:    ":many",
	Source: "atlas.sql",
	SQL: `SELECT id, project_id, kind, slug, title, description, created_at, updated_at FROM zdx_nodes
WHERE project_id = $1
  AND ($2::text = '' OR kind = $2)
ORDER BY kind, slug`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_nodes"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_nodes"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "slug", OriginalName: "slug", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_nodes"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_nodes"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "kind", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListAtlasNodes returns a metaquery.Builder over MetaListAtlasNodes, pre-bound with typed arguments.
func WrapListAtlasNodes(arg ListAtlasNodesParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAtlasNodes, arg.ProjectID, arg.Kind)
}

// ListAtlasNodesCols gives typed, name-safe access to ListAtlasNodes's output columns.
var ListAtlasNodesCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Kind        metaquery.TextCol
	Slug        metaquery.TextCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Kind:        metaquery.NewTextCol("kind"),
	Slug:        metaquery.NewTextCol("slug"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaUpdateAtlasChunk = metaquery.Query{
	Name:   "UpdateAtlasChunk",
	Cmd:    ":exec",
	Source: "atlas.sql",
	SQL: `UPDATE zdx_narrative_chunks
SET title        = COALESCE(NULLIF($1, ''), title),
    body         = COALESCE(NULLIF($2, ''), body),
    sha_at_write = COALESCE(NULLIF($3, ''), sha_at_write),
    updated_at   = NOW()
WHERE project_id = $4 AND id = $5`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "title", GoType: "interface{}", DBType: "any"},
		{Position: 2, Name: "body", GoType: "interface{}", DBType: "any"},
		{Position: 3, Name: "sha_at_write", GoType: "interface{}", DBType: "any"},
		{Position: 4, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 5, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapUpdateAtlasChunk returns a metaquery.Builder over MetaUpdateAtlasChunk, pre-bound with typed arguments.
func WrapUpdateAtlasChunk(arg UpdateAtlasChunkParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateAtlasChunk, arg.Title, arg.Body, arg.ShaAtWrite, arg.ProjectID, arg.ID)
}

var MetaUpdateAtlasNode = metaquery.Query{
	Name:   "UpdateAtlasNode",
	Cmd:    ":exec",
	Source: "atlas.sql",
	SQL: `UPDATE zdx_nodes
SET title       = COALESCE(NULLIF($1, ''), title),
    description = COALESCE(NULLIF($2, ''), description),
    updated_at  = NOW()
WHERE project_id = $3 AND id = $4`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "title", GoType: "interface{}", DBType: "any"},
		{Position: 2, Name: "description", GoType: "interface{}", DBType: "any"},
		{Position: 3, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 4, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapUpdateAtlasNode returns a metaquery.Builder over MetaUpdateAtlasNode, pre-bound with typed arguments.
func WrapUpdateAtlasNode(arg UpdateAtlasNodeParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateAtlasNode, arg.Title, arg.Description, arg.ProjectID, arg.ID)
}
