// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addComment = `-- name: AddComment :one
INSERT INTO zdx_comments (project_id, target_type, target_id, author, body, parent_id, author_alias)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, target_type, target_id, author, body, created_at, parent_id, author_alias
`

type AddCommentParams struct {
	ProjectID   int32       `db:"project_id" json:"project_id"`
	TargetType  string      `db:"target_type" json:"target_type"`
	TargetID    string      `db:"target_id" json:"target_id"`
	Author      string      `db:"author" json:"author"`
	Body        string      `db:"body" json:"body"`
	ParentID    pgtype.Int4 `db:"parent_id" json:"parent_id"`
	AuthorAlias string      `db:"author_alias" json:"author_alias"`
}

type AddCommentRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	TargetType  string             `db:"target_type" json:"target_type"`
	TargetID    string             `db:"target_id" json:"target_id"`
	Author      string             `db:"author" json:"author"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID    pgtype.Int4        `db:"parent_id" json:"parent_id"`
	AuthorAlias string             `db:"author_alias" json:"author_alias"`
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (AddCommentRow, error) {
	row := q.db.QueryRow(ctx, addComment,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.Author,
		arg.Body,
		arg.ParentID,
		arg.AuthorAlias,
	)
	var i AddCommentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetType,
		&i.TargetID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.ParentID,
		&i.AuthorAlias,
	)
	return i, err
}

const addRevision = `-- name: AddRevision :exec
INSERT INTO zdx_revisions (project_id, target_type, target_id, field, old_val, new_val, agent, session_id, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AddRevisionParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	Field      string `db:"field" json:"field"`
	OldVal     string `db:"old_val" json:"old_val"`
	NewVal     string `db:"new_val" json:"new_val"`
	Agent      string `db:"agent" json:"agent"`
	SessionID  string `db:"session_id" json:"session_id"`
	UserID     string `db:"user_id" json:"user_id"`
}

func (q *Queries) AddRevision(ctx context.Context, arg AddRevisionParams) error {
	_, err := q.db.Exec(ctx, addRevision,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.Field,
		arg.OldVal,
		arg.NewVal,
		arg.Agent,
		arg.SessionID,
		arg.UserID,
	)
	return err
}

const countRevisionsBySession = `-- name: CountRevisionsBySession :one
SELECT count(*) FROM zdx_revisions WHERE project_id = $1 AND session_id = $2
`

type CountRevisionsBySessionParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	SessionID string `db:"session_id" json:"session_id"`
}

// Count how many revisions were recorded by a given agent session.
// Used by /api/dx/solo/release to detect sessions that exited cleanly but
// didn't apply any durable mutation — those release without marking resolved.
func (q *Queries) CountRevisionsBySession(ctx context.Context, arg CountRevisionsBySessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRevisionsBySession, arg.ProjectID, arg.SessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, project_id, target_type, target_id, author, body, created_at, parent_id, author_alias
FROM zdx_comments WHERE id = $1
`

type GetCommentByIDRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	TargetType  string             `db:"target_type" json:"target_type"`
	TargetID    string             `db:"target_id" json:"target_id"`
	Author      string             `db:"author" json:"author"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID    pgtype.Int4        `db:"parent_id" json:"parent_id"`
	AuthorAlias string             `db:"author_alias" json:"author_alias"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id int32) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TargetType,
		&i.TargetID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
		&i.ParentID,
		&i.AuthorAlias,
	)
	return i, err
}

const getCommentsByIDs = `-- name: GetCommentsByIDs :many
SELECT id, project_id, target_type, target_id, author, body, created_at, parent_id, author_alias
FROM zdx_comments WHERE id = ANY($1::int[])
`

type GetCommentsByIDsRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	TargetType  string             `db:"target_type" json:"target_type"`
	TargetID    string             `db:"target_id" json:"target_id"`
	Author      string             `db:"author" json:"author"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID    pgtype.Int4        `db:"parent_id" json:"parent_id"`
	AuthorAlias string             `db:"author_alias" json:"author_alias"`
}

func (q *Queries) GetCommentsByIDs(ctx context.Context, dollar_1 []int32) ([]GetCommentsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByIDsRow
	for rows.Next() {
		var i GetCommentsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.ParentID,
			&i.AuthorAlias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComments = `-- name: ListComments :many
SELECT id, project_id, target_type, target_id, author, body, created_at, parent_id, author_alias
FROM zdx_comments WHERE project_id = $1 AND target_type = $2 AND target_id = $3
ORDER BY created_at
`

type ListCommentsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

type ListCommentsRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	TargetType  string             `db:"target_type" json:"target_type"`
	TargetID    string             `db:"target_id" json:"target_id"`
	Author      string             `db:"author" json:"author"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID    pgtype.Int4        `db:"parent_id" json:"parent_id"`
	AuthorAlias string             `db:"author_alias" json:"author_alias"`
}

func (q *Queries) ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, arg.ProjectID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.ParentID,
			&i.AuthorAlias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, project_id, target_type, target_id, author, body, created_at, parent_id, author_alias
FROM zdx_comments WHERE project_id = $1 AND author = $2
ORDER BY created_at DESC
`

type ListCommentsByAuthorParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Author    string `db:"author" json:"author"`
}

type ListCommentsByAuthorRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	TargetType  string             `db:"target_type" json:"target_type"`
	TargetID    string             `db:"target_id" json:"target_id"`
	Author      string             `db:"author" json:"author"`
	Body        string             `db:"body" json:"body"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ParentID    pgtype.Int4        `db:"parent_id" json:"parent_id"`
	AuthorAlias string             `db:"author_alias" json:"author_alias"`
}

func (q *Queries) ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]ListCommentsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByAuthor, arg.ProjectID, arg.Author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByAuthorRow
	for rows.Next() {
		var i ListCommentsByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
			&i.ParentID,
			&i.AuthorAlias,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturesWithPendingComments = `-- name: ListFeaturesWithPendingComments :many
WITH last_comment AS (
    SELECT DISTINCT ON (target_id) target_id, author_alias
    FROM zdx_comments
    WHERE project_id = $1 AND target_type = 'feature'
    ORDER BY target_id, created_at DESC
)
SELECT target_id FROM last_comment WHERE author_alias = ''
`

// Returns feature target_ids where the most-recent comment has no author_alias
// (human posted last and the agent has not yet replied).
func (q *Queries) ListFeaturesWithPendingComments(ctx context.Context, projectID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, listFeaturesWithPendingComments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var target_id string
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, project_id, target_type, target_id, field, old_val, new_val, agent, session_id, user_id, created_at
FROM zdx_revisions WHERE project_id = $1 AND target_type = $2 AND target_id = $3
ORDER BY created_at
`

type ListRevisionsParams struct {
	ProjectID  int32  `db:"project_id" json:"project_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

type ListRevisionsRow struct {
	ID         int32              `db:"id" json:"id"`
	ProjectID  int32              `db:"project_id" json:"project_id"`
	TargetType string             `db:"target_type" json:"target_type"`
	TargetID   string             `db:"target_id" json:"target_id"`
	Field      string             `db:"field" json:"field"`
	OldVal     string             `db:"old_val" json:"old_val"`
	NewVal     string             `db:"new_val" json:"new_val"`
	Agent      string             `db:"agent" json:"agent"`
	SessionID  string             `db:"session_id" json:"session_id"`
	UserID     string             `db:"user_id" json:"user_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, arg.ProjectID, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsRow
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.Field,
			&i.OldVal,
			&i.NewVal,
			&i.Agent,
			&i.SessionID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisionsByTarget = `-- name: ListRevisionsByTarget :many
SELECT id, project_id, target_type, target_id, field, old_val, new_val, agent, session_id, user_id, created_at
FROM zdx_revisions WHERE target_type = $1 AND target_id = $2
ORDER BY created_at DESC
`

type ListRevisionsByTargetParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

type ListRevisionsByTargetRow struct {
	ID         int32              `db:"id" json:"id"`
	ProjectID  int32              `db:"project_id" json:"project_id"`
	TargetType string             `db:"target_type" json:"target_type"`
	TargetID   string             `db:"target_id" json:"target_id"`
	Field      string             `db:"field" json:"field"`
	OldVal     string             `db:"old_val" json:"old_val"`
	NewVal     string             `db:"new_val" json:"new_val"`
	Agent      string             `db:"agent" json:"agent"`
	SessionID  string             `db:"session_id" json:"session_id"`
	UserID     string             `db:"user_id" json:"user_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListRevisionsByTarget(ctx context.Context, arg ListRevisionsByTargetParams) ([]ListRevisionsByTargetRow, error) {
	rows, err := q.db.Query(ctx, listRevisionsByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevisionsByTargetRow
	for rows.Next() {
		var i ListRevisionsByTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.Field,
			&i.OldVal,
			&i.NewVal,
			&i.Agent,
			&i.SessionID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargetsWithComments = `-- name: ListTargetsWithComments :many
SELECT DISTINCT target_type, target_id
FROM zdx_comments
WHERE project_id = $1
ORDER BY target_type, target_id
`

type ListTargetsWithCommentsRow struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

func (q *Queries) ListTargetsWithComments(ctx context.Context, projectID int32) ([]ListTargetsWithCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTargetsWithComments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTargetsWithCommentsRow
	for rows.Next() {
		var i ListTargetsWithCommentsRow
		if err := rows.Scan(&i.TargetType, &i.TargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
