// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: counters.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
	"github.com/jackc/pgx/v5/pgtype"
)

var _ = metaquery.Query{}

var MetaDeleteCounterEventsOlderThan = metaquery.Query{
	Name:   "DeleteCounterEventsOlderThan",
	Cmd:    ":execrows",
	Source: "counters.sql",
	SQL: `DELETE FROM zdx_counter_events
WHERE created_at < $1::timestamptz`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "cutoff", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true},
	},
}

// WrapDeleteCounterEventsOlderThan returns a metaquery.Builder over MetaDeleteCounterEventsOlderThan, pre-bound with typed arguments.
func WrapDeleteCounterEventsOlderThan(cutoff pgtype.Timestamptz) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteCounterEventsOlderThan, cutoff)
}

var MetaInsertCounterEvent = metaquery.Query{
	Name:   "InsertCounterEvent",
	Cmd:    ":exec",
	Source: "counters.sql",
	SQL: `INSERT INTO zdx_counter_events (project_id, component, environment, name, value, source, context_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "pg_catalog.int4"},
		{Position: 2, Name: "component", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "environment", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "value", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 6, Name: "source", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_counter_events"},
}

// WrapInsertCounterEvent returns a metaquery.Builder over MetaInsertCounterEvent, pre-bound with typed arguments.
func WrapInsertCounterEvent(arg InsertCounterEventParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaInsertCounterEvent, arg.ProjectID, arg.Component, arg.Environment, arg.Name, arg.Value, arg.Source, arg.ContextJson)
}

var MetaListCounted = metaquery.Query{
	Name:   "ListCounted",
	Cmd:    ":many",
	Source: "counters.sql",
	SQL: `SELECT id, project_id, component, environment, name, value, count, total_value, source, context_json, created_at
FROM zdx_counted
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
ORDER BY total_value DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_counted"},
		{Name: "project_id", OriginalName: "project_id", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_counted"},
		{Name: "component", OriginalName: "component", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counted"},
		{Name: "environment", OriginalName: "environment", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counted"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counted"},
		{Name: "value", OriginalName: "value", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_counted"},
		{Name: "count", OriginalName: "count", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_counted"},
		{Name: "total_value", OriginalName: "total_value", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_counted"},
		{Name: "source", OriginalName: "source", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counted"},
		{Name: "context_json", OriginalName: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_counted"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_counted"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
		{Position: 2, Name: "tag_filter", GoType: "[]byte", DBType: "jsonb"},
	},
}

// WrapListCounted returns a metaquery.Builder over MetaListCounted, pre-bound with typed arguments.
func WrapListCounted(arg ListCountedParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListCounted, arg.ProjectID, arg.TagFilter)
}

// ListCountedCols gives typed, name-safe access to ListCounted's output columns.
var ListCountedCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Component   metaquery.TextCol
	Environment metaquery.TextCol
	Name        metaquery.TextCol
	Value       metaquery.IntCol
	Count       metaquery.IntCol
	TotalValue  metaquery.IntCol
	Source      metaquery.TextCol
	ContextJson metaquery.BytesCol
	CreatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Component:   metaquery.NewTextCol("component"),
	Environment: metaquery.NewTextCol("environment"),
	Name:        metaquery.NewTextCol("name"),
	Value:       metaquery.NewIntCol("value"),
	Count:       metaquery.NewIntCol("count"),
	TotalValue:  metaquery.NewIntCol("total_value"),
	Source:      metaquery.NewTextCol("source"),
	ContextJson: metaquery.NewBytesCol("context_json"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
}

// ListCountedGroupedRow is the scan target for Grouped aggregation on ListCounted.
type ListCountedGroupedRow struct {
	GroupValue    string `db:"group_value" json:"group_value"`
	EntryCount    int64  `db:"entry_count" json:"entry_count"`
	MaxValue      int32  `db:"max_value" json:"max_value"`
	SumTotalValue int64  `db:"sum_total_value" json:"sum_total_value"`
	SumCount      int64  `db:"sum_count" json:"sum_count"`
}

// WrapListCountedGrouped returns a Builder pre-configured with Grouped aggregation over ListCounted.
func WrapListCountedGrouped(arg ListCountedParams, groupKey string) *metaquery.Builder {
	b := WrapListCounted(arg)
	b.GroupByExpr("group_value", "context_json->>?", "string", groupKey)
	b.Count("entry_count")
	b.Max("max_value", "value")
	b.Sum("sum_total_value", "total_value")
	b.Sum("sum_count", "count")
	return b
}

var MetaListCountedDistinctTagKeys = metaquery.Query{
	Name:   "ListCountedDistinctTagKeys",
	Cmd:    ":many",
	Source: "counters.sql",
	SQL: `SELECT DISTINCT k AS tag_key
FROM zdx_counted, jsonb_object_keys(context_json) AS k
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY tag_key`,
	Columns: []metaquery.Column{
		{Name: "tag_key", OriginalName: "tag_key", GoType: "pgtype.Text"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
	},
}

// WrapListCountedDistinctTagKeys returns a metaquery.Builder over MetaListCountedDistinctTagKeys, pre-bound with typed arguments.
func WrapListCountedDistinctTagKeys(projectID pgtype.Int4) *metaquery.Builder {
	return metaquery.Wrap(&MetaListCountedDistinctTagKeys, projectID)
}

// ListCountedDistinctTagKeysCols gives typed, name-safe access to ListCountedDistinctTagKeys's output columns.
var ListCountedDistinctTagKeysCols = struct {
	TagKey metaquery.TextCol
}{
	TagKey: metaquery.NewTextCol("tag_key"),
}

var MetaListCountedDistinctTagValues = metaquery.Query{
	Name:   "ListCountedDistinctTagValues",
	Cmd:    ":many",
	Source: "counters.sql",
	SQL: `SELECT DISTINCT context_json->>@tag_key::text AS tag_value
FROM zdx_counted
WHERE ($1::int IS NULL OR project_id = $1)
  AND context_json ? $2::text
  AND context_json->>@tag_key::text IS NOT NULL
ORDER BY tag_value`,
	Columns: []metaquery.Column{
		{Name: "tag_value", OriginalName: "tag_value", GoType: "interface{}"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
		{Position: 2, Name: "tag_key", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListCountedDistinctTagValues returns a metaquery.Builder over MetaListCountedDistinctTagValues, pre-bound with typed arguments.
func WrapListCountedDistinctTagValues(arg ListCountedDistinctTagValuesParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListCountedDistinctTagValues, arg.ProjectID, arg.TagKey)
}

// ListCountedDistinctTagValuesCols gives typed, name-safe access to ListCountedDistinctTagValues's output columns.
var ListCountedDistinctTagValuesCols = struct {
	TagValue metaquery.AnyCol
}{
	TagValue: metaquery.NewAnyCol("tag_value"),
}

var MetaListCounterEvents = metaquery.Query{
	Name:   "ListCounterEvents",
	Cmd:    ":many",
	Source: "counters.sql",
	SQL: `SELECT id, project_id, component, environment, name, value, source, context_json, created_at
FROM zdx_counter_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_counter_events"},
		{Name: "project_id", OriginalName: "project_id", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_counter_events"},
		{Name: "component", OriginalName: "component", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counter_events"},
		{Name: "environment", OriginalName: "environment", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counter_events"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counter_events"},
		{Name: "value", OriginalName: "value", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_counter_events"},
		{Name: "source", OriginalName: "source", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_counter_events"},
		{Name: "context_json", OriginalName: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_counter_events"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_counter_events"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
		{Position: 2, Name: "tag_filter", GoType: "[]byte", DBType: "jsonb"},
		{Position: 3, Name: "since", GoType: "pgtype.Timestamptz", DBType: "timestamptz"},
		{Position: 4, Name: "until", GoType: "pgtype.Timestamptz", DBType: "timestamptz"},
	},
}

// WrapListCounterEvents returns a metaquery.Builder over MetaListCounterEvents, pre-bound with typed arguments.
func WrapListCounterEvents(arg ListCounterEventsParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListCounterEvents, arg.ProjectID, arg.TagFilter, arg.Since, arg.Until)
}

// ListCounterEventsCols gives typed, name-safe access to ListCounterEvents's output columns.
var ListCounterEventsCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Component   metaquery.TextCol
	Environment metaquery.TextCol
	Name        metaquery.TextCol
	Value       metaquery.IntCol
	Source      metaquery.TextCol
	ContextJson metaquery.BytesCol
	CreatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Component:   metaquery.NewTextCol("component"),
	Environment: metaquery.NewTextCol("environment"),
	Name:        metaquery.NewTextCol("name"),
	Value:       metaquery.NewIntCol("value"),
	Source:      metaquery.NewTextCol("source"),
	ContextJson: metaquery.NewBytesCol("context_json"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
}

// ListCounterEventsGroupedRow is the scan target for Grouped aggregation on ListCounterEvents.
type ListCounterEventsGroupedRow struct {
	GroupValue string             `db:"group_value" json:"group_value"`
	EntryCount int64              `db:"entry_count" json:"entry_count"`
	MaxValue   int32              `db:"max_value" json:"max_value"`
	SumValue   int64              `db:"sum_value" json:"sum_value"`
	FirstSeen  pgtype.Timestamptz `db:"first_seen" json:"first_seen"`
	LastSeen   pgtype.Timestamptz `db:"last_seen" json:"last_seen"`
}

// WrapListCounterEventsGrouped returns a Builder pre-configured with Grouped aggregation over ListCounterEvents.
func WrapListCounterEventsGrouped(arg ListCounterEventsParams, groupKey string) *metaquery.Builder {
	b := WrapListCounterEvents(arg)
	b.GroupByExpr("group_value", "context_json->>?", "string", groupKey)
	b.Count("entry_count")
	b.Max("max_value", "value")
	b.Sum("sum_value", "value")
	b.Min("first_seen", "created_at")
	b.Max("last_seen", "created_at")
	return b
}

var MetaUpsertCounted = metaquery.Query{
	Name:   "UpsertCounted",
	Cmd:    ":exec",
	Source: "counters.sql",
	SQL: `INSERT INTO zdx_counted (project_id, component, environment, name, value, source, context_json, count, total_value)
VALUES ($1, $2, $3, $4, $5, $6, $7, 1, $8)
ON CONFLICT (COALESCE(project_id, 0), component, environment, name)
DO UPDATE SET
  value        = GREATEST(zdx_counted.value, EXCLUDED.value),
  source       = CASE WHEN EXCLUDED.value > zdx_counted.value THEN EXCLUDED.source ELSE zdx_counted.source END,
  context_json = CASE WHEN EXCLUDED.value > zdx_counted.value THEN EXCLUDED.context_json ELSE zdx_counted.context_json END,
  count        = zdx_counted.count + 1,
  total_value  = zdx_counted.total_value + EXCLUDED.value,
  created_at   = NOW()`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "pg_catalog.int4"},
		{Position: 2, Name: "component", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "environment", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "value", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 6, Name: "source", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true},
		{Position: 8, Name: "total_value", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_counted"},
}

// WrapUpsertCounted returns a metaquery.Builder over MetaUpsertCounted, pre-bound with typed arguments.
func WrapUpsertCounted(arg UpsertCountedParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertCounted, arg.ProjectID, arg.Component, arg.Environment, arg.Name, arg.Value, arg.Source, arg.ContextJson, arg.TotalValue)
}
