// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: error_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countErrorEvents = `-- name: CountErrorEvents :one
SELECT count(*) FROM zdx_error_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
`

type CountErrorEventsParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
}

func (q *Queries) CountErrorEvents(ctx context.Context, arg CountErrorEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorEvents,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteErrorEventsOlderThan = `-- name: DeleteErrorEventsOlderThan :execrows
DELETE FROM zdx_error_events
WHERE created_at < $1::timestamptz
`

func (q *Queries) DeleteErrorEventsOlderThan(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteErrorEventsOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getErrorEventByID = `-- name: GetErrorEventByID :one
SELECT id, project_id, component, environment, name, message, stack_trace, source, context_json, created_at
FROM zdx_error_events
WHERE id = $1
`

func (q *Queries) GetErrorEventByID(ctx context.Context, id int64) (ZdxErrorEvent, error) {
	row := q.db.QueryRow(ctx, getErrorEventByID, id)
	var i ZdxErrorEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Component,
		&i.Environment,
		&i.Name,
		&i.Message,
		&i.StackTrace,
		&i.Source,
		&i.ContextJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertErrorEvent = `-- name: InsertErrorEvent :exec
INSERT INTO zdx_error_events (project_id, component, environment, name, message, stack_trace, source, context_json)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertErrorEventParams struct {
	ProjectID   pgtype.Int4 `db:"project_id" json:"project_id"`
	Component   string      `db:"component" json:"component"`
	Environment string      `db:"environment" json:"environment"`
	Name        string      `db:"name" json:"name"`
	Message     string      `db:"message" json:"message"`
	StackTrace  string      `db:"stack_trace" json:"stack_trace"`
	Source      string      `db:"source" json:"source"`
	ContextJson []byte      `db:"context_json" json:"context_json"`
}

func (q *Queries) InsertErrorEvent(ctx context.Context, arg InsertErrorEventParams) error {
	_, err := q.db.Exec(ctx, insertErrorEvent,
		arg.ProjectID,
		arg.Component,
		arg.Environment,
		arg.Name,
		arg.Message,
		arg.StackTrace,
		arg.Source,
		arg.ContextJson,
	)
	return err
}

const listErrorEvents = `-- name: ListErrorEvents :many
SELECT id, project_id, component, environment, name, message, stack_trace, source, context_json, created_at
FROM zdx_error_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListErrorEventsParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
	Off       int32              `db:"off" json:"off"`
	Lim       int32              `db:"lim" json:"lim"`
}

func (q *Queries) ListErrorEvents(ctx context.Context, arg ListErrorEventsParams) ([]ZdxErrorEvent, error) {
	rows, err := q.db.Query(ctx, listErrorEvents,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxErrorEvent
	for rows.Next() {
		var i ZdxErrorEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Component,
			&i.Environment,
			&i.Name,
			&i.Message,
			&i.StackTrace,
			&i.Source,
			&i.ContextJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorEventsDistinctTagKeys = `-- name: ListErrorEventsDistinctTagKeys :many
SELECT DISTINCT k AS tag_key
FROM zdx_error_events, jsonb_object_keys(context_json) AS k
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY tag_key
`

func (q *Queries) ListErrorEventsDistinctTagKeys(ctx context.Context, projectID pgtype.Int4) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listErrorEventsDistinctTagKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var tag_key pgtype.Text
		if err := rows.Scan(&tag_key); err != nil {
			return nil, err
		}
		items = append(items, tag_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorEventsDistinctTagValues = `-- name: ListErrorEventsDistinctTagValues :many
SELECT DISTINCT context_json->>@tag_key::text AS tag_value
FROM zdx_error_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND context_json ? $2::text
  AND context_json->>@tag_key::text IS NOT NULL
ORDER BY tag_value
`

type ListErrorEventsDistinctTagValuesParams struct {
	ProjectID pgtype.Int4 `db:"project_id" json:"project_id"`
	TagKey    string      `db:"tag_key" json:"tag_key"`
}

func (q *Queries) ListErrorEventsDistinctTagValues(ctx context.Context, arg ListErrorEventsDistinctTagValuesParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listErrorEventsDistinctTagValues, arg.ProjectID, arg.TagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var tag_value interface{}
		if err := rows.Scan(&tag_value); err != nil {
			return nil, err
		}
		items = append(items, tag_value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorEventsGrouped = `-- name: ListErrorEventsGrouped :many
SELECT
  context_json->>@group_key::text AS group_value,
  count(*)::int AS entry_count,
  min(created_at) AS first_seen,
  max(created_at) AS last_seen
FROM zdx_error_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
  AND context_json ? $5::text
GROUP BY group_value
ORDER BY entry_count DESC
`

type ListErrorEventsGroupedParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
	GroupKey  string             `db:"group_key" json:"group_key"`
}

type ListErrorEventsGroupedRow struct {
	GroupValue interface{} `db:"group_value" json:"group_value"`
	EntryCount int32       `db:"entry_count" json:"entry_count"`
	FirstSeen  interface{} `db:"first_seen" json:"first_seen"`
	LastSeen   interface{} `db:"last_seen" json:"last_seen"`
}

func (q *Queries) ListErrorEventsGrouped(ctx context.Context, arg ListErrorEventsGroupedParams) ([]ListErrorEventsGroupedRow, error) {
	rows, err := q.db.Query(ctx, listErrorEventsGrouped,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
		arg.GroupKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListErrorEventsGroupedRow
	for rows.Next() {
		var i ListErrorEventsGroupedRow
		if err := rows.Scan(
			&i.GroupValue,
			&i.EntryCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
