// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCreateThread = metaquery.Query{
	Name:   "CreateThread",
	Cmd:    ":one",
	Source: "events.sql",
	SQL: `INSERT INTO zdx_event_threads (
  project_id, target_type, target_id, root_event_id, title
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, target_type, target_id, root_event_id, title, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_threads"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_event_threads"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_threads"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_threads"},
		{Name: "root_event_id", OriginalName: "root_event_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_threads"},
		{Name: "title", OriginalName: "title", GoType: "pgtype.Text", DBType: "text", Table: "zdx_event_threads"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_event_threads"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "root_event_id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
		{Position: 5, Name: "title", GoType: "pgtype.Text", DBType: "text"},
	},
	Table: &metaquery.Table{Name: "zdx_event_threads"},
}

// WrapCreateThread returns a metaquery.Builder over MetaCreateThread, pre-bound with typed arguments.
func WrapCreateThread(arg CreateThreadParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateThread, arg.ProjectID, arg.TargetType, arg.TargetID, arg.RootEventID, arg.Title)
}

// CreateThreadCols gives typed, name-safe access to CreateThread's output columns.
var CreateThreadCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	TargetType  metaquery.TextCol
	TargetID    metaquery.TextCol
	RootEventID metaquery.IntCol
	Title       metaquery.TextCol
	CreatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	TargetType:  metaquery.NewTextCol("target_type"),
	TargetID:    metaquery.NewTextCol("target_id"),
	RootEventID: metaquery.NewIntCol("root_event_id"),
	Title:       metaquery.NewTextCol("title"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
}

var MetaGetStreamByTarget = metaquery.Query{
	Name:   "GetStreamByTarget",
	Cmd:    ":one",
	Source: "events.sql",
	SQL: `SELECT id, project_id, target_type, target_id,
       last_evaluated_at, last_evaluated_by
FROM zdx_event_streams
WHERE project_id = $1
  AND target_type = $2
  AND target_id = $3`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_streams"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_event_streams"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_streams"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_streams"},
		{Name: "last_evaluated_at", OriginalName: "last_evaluated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_event_streams"},
		{Name: "last_evaluated_by", OriginalName: "last_evaluated_by", GoType: "pgtype.Text", DBType: "text", Table: "zdx_event_streams"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapGetStreamByTarget returns a metaquery.Builder over MetaGetStreamByTarget, pre-bound with typed arguments.
func WrapGetStreamByTarget(arg GetStreamByTargetParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetStreamByTarget, arg.ProjectID, arg.TargetType, arg.TargetID)
}

// GetStreamByTargetCols gives typed, name-safe access to GetStreamByTarget's output columns.
var GetStreamByTargetCols = struct {
	ID              metaquery.IntCol
	ProjectID       metaquery.IntCol
	TargetType      metaquery.TextCol
	TargetID        metaquery.TextCol
	LastEvaluatedAt metaquery.TimeCol
	LastEvaluatedBy metaquery.TextCol
}{
	ID:              metaquery.NewIntCol("id"),
	ProjectID:       metaquery.NewIntCol("project_id"),
	TargetType:      metaquery.NewTextCol("target_type"),
	TargetID:        metaquery.NewTextCol("target_id"),
	LastEvaluatedAt: metaquery.NewTimeCol("last_evaluated_at"),
	LastEvaluatedBy: metaquery.NewTextCol("last_evaluated_by"),
}

var MetaInsertEvent = metaquery.Query{
	Name:   "InsertEvent",
	Cmd:    ":one",
	Source: "events.sql",
	SQL: `INSERT INTO zdx_events (
  project_id, target_type, target_id, thread_id, event_type,
  author, author_kind, summary_json, detail_json, agent_process_result
)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8, $9, $10
)
RETURNING id, project_id, target_type, target_id, thread_id, event_type,
          author, author_kind, summary_json, detail_json,
          agent_process_result, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_events"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_events"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "thread_id", OriginalName: "thread_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_events"},
		{Name: "event_type", OriginalName: "event_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author", OriginalName: "author", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author_kind", OriginalName: "author_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "summary_json", OriginalName: "summary_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "detail_json", OriginalName: "detail_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "agent_process_result", OriginalName: "agent_process_result", GoType: "[]byte", DBType: "jsonb", Table: "zdx_events"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_events"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "thread_id", GoType: "pgtype.Int8", DBType: "pg_catalog.int8"},
		{Position: 5, Name: "event_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "author", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "author_kind", GoType: "string", DBType: "text", NotNull: true},
		{Position: 8, Name: "summary_json", GoType: "[]byte", DBType: "jsonb", NotNull: true},
		{Position: 9, Name: "detail_json", GoType: "[]byte", DBType: "jsonb", NotNull: true},
		{Position: 10, Name: "agent_process_result", GoType: "[]byte", DBType: "jsonb"},
	},
	Table: &metaquery.Table{Name: "zdx_events"},
}

// WrapInsertEvent returns a metaquery.Builder over MetaInsertEvent, pre-bound with typed arguments.
func WrapInsertEvent(arg InsertEventParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaInsertEvent, arg.ProjectID, arg.TargetType, arg.TargetID, arg.ThreadID, arg.EventType, arg.Author, arg.AuthorKind, arg.SummaryJson, arg.DetailJson, arg.AgentProcessResult)
}

// InsertEventCols gives typed, name-safe access to InsertEvent's output columns.
var InsertEventCols = struct {
	ID                 metaquery.IntCol
	ProjectID          metaquery.IntCol
	TargetType         metaquery.TextCol
	TargetID           metaquery.TextCol
	ThreadID           metaquery.IntCol
	EventType          metaquery.TextCol
	Author             metaquery.TextCol
	AuthorKind         metaquery.TextCol
	SummaryJson        metaquery.BytesCol
	DetailJson         metaquery.BytesCol
	AgentProcessResult metaquery.BytesCol
	CreatedAt          metaquery.TimeCol
}{
	ID:                 metaquery.NewIntCol("id"),
	ProjectID:          metaquery.NewIntCol("project_id"),
	TargetType:         metaquery.NewTextCol("target_type"),
	TargetID:           metaquery.NewTextCol("target_id"),
	ThreadID:           metaquery.NewIntCol("thread_id"),
	EventType:          metaquery.NewTextCol("event_type"),
	Author:             metaquery.NewTextCol("author"),
	AuthorKind:         metaquery.NewTextCol("author_kind"),
	SummaryJson:        metaquery.NewBytesCol("summary_json"),
	DetailJson:         metaquery.NewBytesCol("detail_json"),
	AgentProcessResult: metaquery.NewBytesCol("agent_process_result"),
	CreatedAt:          metaquery.NewTimeCol("created_at"),
}

var MetaListEventsByTarget = metaquery.Query{
	Name:   "ListEventsByTarget",
	Cmd:    ":many",
	Source: "events.sql",
	SQL: `SELECT id, project_id, target_type, target_id, thread_id, event_type,
       author, author_kind, summary_json, detail_json,
       agent_process_result, created_at
FROM zdx_events
WHERE project_id = $1
  AND target_type = $2
  AND target_id = $3
ORDER BY created_at, id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_events"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_events"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "thread_id", OriginalName: "thread_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_events"},
		{Name: "event_type", OriginalName: "event_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author", OriginalName: "author", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author_kind", OriginalName: "author_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "summary_json", OriginalName: "summary_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "detail_json", OriginalName: "detail_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "agent_process_result", OriginalName: "agent_process_result", GoType: "[]byte", DBType: "jsonb", Table: "zdx_events"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_events"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListEventsByTarget returns a metaquery.Builder over MetaListEventsByTarget, pre-bound with typed arguments.
func WrapListEventsByTarget(arg ListEventsByTargetParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListEventsByTarget, arg.ProjectID, arg.TargetType, arg.TargetID)
}

// ListEventsByTargetCols gives typed, name-safe access to ListEventsByTarget's output columns.
var ListEventsByTargetCols = struct {
	ID                 metaquery.IntCol
	ProjectID          metaquery.IntCol
	TargetType         metaquery.TextCol
	TargetID           metaquery.TextCol
	ThreadID           metaquery.IntCol
	EventType          metaquery.TextCol
	Author             metaquery.TextCol
	AuthorKind         metaquery.TextCol
	SummaryJson        metaquery.BytesCol
	DetailJson         metaquery.BytesCol
	AgentProcessResult metaquery.BytesCol
	CreatedAt          metaquery.TimeCol
}{
	ID:                 metaquery.NewIntCol("id"),
	ProjectID:          metaquery.NewIntCol("project_id"),
	TargetType:         metaquery.NewTextCol("target_type"),
	TargetID:           metaquery.NewTextCol("target_id"),
	ThreadID:           metaquery.NewIntCol("thread_id"),
	EventType:          metaquery.NewTextCol("event_type"),
	Author:             metaquery.NewTextCol("author"),
	AuthorKind:         metaquery.NewTextCol("author_kind"),
	SummaryJson:        metaquery.NewBytesCol("summary_json"),
	DetailJson:         metaquery.NewBytesCol("detail_json"),
	AgentProcessResult: metaquery.NewBytesCol("agent_process_result"),
	CreatedAt:          metaquery.NewTimeCol("created_at"),
}

var MetaListEventsByThread = metaquery.Query{
	Name:   "ListEventsByThread",
	Cmd:    ":many",
	Source: "events.sql",
	SQL: `SELECT id, project_id, target_type, target_id, thread_id, event_type,
       author, author_kind, summary_json, detail_json,
       agent_process_result, created_at
FROM zdx_events
WHERE project_id = $1
  AND target_type = $2
  AND target_id = $3
  AND thread_id = $4
ORDER BY created_at, id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_events"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_events"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "thread_id", OriginalName: "thread_id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_events"},
		{Name: "event_type", OriginalName: "event_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author", OriginalName: "author", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "author_kind", OriginalName: "author_kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_events"},
		{Name: "summary_json", OriginalName: "summary_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "detail_json", OriginalName: "detail_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_events"},
		{Name: "agent_process_result", OriginalName: "agent_process_result", GoType: "[]byte", DBType: "jsonb", Table: "zdx_events"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_events"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "thread_id", GoType: "pgtype.Int8", DBType: "pg_catalog.int8"},
	},
}

// WrapListEventsByThread returns a metaquery.Builder over MetaListEventsByThread, pre-bound with typed arguments.
func WrapListEventsByThread(arg ListEventsByThreadParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListEventsByThread, arg.ProjectID, arg.TargetType, arg.TargetID, arg.ThreadID)
}

// ListEventsByThreadCols gives typed, name-safe access to ListEventsByThread's output columns.
var ListEventsByThreadCols = struct {
	ID                 metaquery.IntCol
	ProjectID          metaquery.IntCol
	TargetType         metaquery.TextCol
	TargetID           metaquery.TextCol
	ThreadID           metaquery.IntCol
	EventType          metaquery.TextCol
	Author             metaquery.TextCol
	AuthorKind         metaquery.TextCol
	SummaryJson        metaquery.BytesCol
	DetailJson         metaquery.BytesCol
	AgentProcessResult metaquery.BytesCol
	CreatedAt          metaquery.TimeCol
}{
	ID:                 metaquery.NewIntCol("id"),
	ProjectID:          metaquery.NewIntCol("project_id"),
	TargetType:         metaquery.NewTextCol("target_type"),
	TargetID:           metaquery.NewTextCol("target_id"),
	ThreadID:           metaquery.NewIntCol("thread_id"),
	EventType:          metaquery.NewTextCol("event_type"),
	Author:             metaquery.NewTextCol("author"),
	AuthorKind:         metaquery.NewTextCol("author_kind"),
	SummaryJson:        metaquery.NewBytesCol("summary_json"),
	DetailJson:         metaquery.NewBytesCol("detail_json"),
	AgentProcessResult: metaquery.NewBytesCol("agent_process_result"),
	CreatedAt:          metaquery.NewTimeCol("created_at"),
}

var MetaListThreadsByTarget = metaquery.Query{
	Name:   "ListThreadsByTarget",
	Cmd:    ":many",
	Source: "events.sql",
	SQL: `SELECT id, project_id, target_type, target_id, root_event_id, title, created_at
FROM zdx_event_threads
WHERE project_id = $1
  AND target_type = $2
  AND target_id = $3
ORDER BY created_at, id`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_threads"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_event_threads"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_threads"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_threads"},
		{Name: "root_event_id", OriginalName: "root_event_id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_threads"},
		{Name: "title", OriginalName: "title", GoType: "pgtype.Text", DBType: "text", Table: "zdx_event_threads"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_event_threads"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListThreadsByTarget returns a metaquery.Builder over MetaListThreadsByTarget, pre-bound with typed arguments.
func WrapListThreadsByTarget(arg ListThreadsByTargetParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListThreadsByTarget, arg.ProjectID, arg.TargetType, arg.TargetID)
}

// ListThreadsByTargetCols gives typed, name-safe access to ListThreadsByTarget's output columns.
var ListThreadsByTargetCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	TargetType  metaquery.TextCol
	TargetID    metaquery.TextCol
	RootEventID metaquery.IntCol
	Title       metaquery.TextCol
	CreatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	TargetType:  metaquery.NewTextCol("target_type"),
	TargetID:    metaquery.NewTextCol("target_id"),
	RootEventID: metaquery.NewIntCol("root_event_id"),
	Title:       metaquery.NewTextCol("title"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
}

var MetaUpsertStream = metaquery.Query{
	Name:   "UpsertStream",
	Cmd:    ":one",
	Source: "events.sql",
	SQL: `INSERT INTO zdx_event_streams (
  project_id, target_type, target_id, last_evaluated_at, last_evaluated_by
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, target_type, target_id)
DO UPDATE SET last_evaluated_at = EXCLUDED.last_evaluated_at,
              last_evaluated_by = EXCLUDED.last_evaluated_by
RETURNING id, project_id, target_type, target_id,
          last_evaluated_at, last_evaluated_by`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_event_streams"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_event_streams"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_streams"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_event_streams"},
		{Name: "last_evaluated_at", OriginalName: "last_evaluated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_event_streams"},
		{Name: "last_evaluated_by", OriginalName: "last_evaluated_by", GoType: "pgtype.Text", DBType: "text", Table: "zdx_event_streams"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "last_evaluated_at", GoType: "pgtype.Timestamptz", DBType: "pg_catalog.timestamptz"},
		{Position: 5, Name: "last_evaluated_by", GoType: "pgtype.Text", DBType: "text"},
	},
	Table: &metaquery.Table{Name: "zdx_event_streams"},
}

// WrapUpsertStream returns a metaquery.Builder over MetaUpsertStream, pre-bound with typed arguments.
func WrapUpsertStream(arg UpsertStreamParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpsertStream, arg.ProjectID, arg.TargetType, arg.TargetID, arg.LastEvaluatedAt, arg.LastEvaluatedBy)
}

// UpsertStreamCols gives typed, name-safe access to UpsertStream's output columns.
var UpsertStreamCols = struct {
	ID              metaquery.IntCol
	ProjectID       metaquery.IntCol
	TargetType      metaquery.TextCol
	TargetID        metaquery.TextCol
	LastEvaluatedAt metaquery.TimeCol
	LastEvaluatedBy metaquery.TextCol
}{
	ID:              metaquery.NewIntCol("id"),
	ProjectID:       metaquery.NewIntCol("project_id"),
	TargetType:      metaquery.NewTextCol("target_type"),
	TargetID:        metaquery.NewTextCol("target_id"),
	LastEvaluatedAt: metaquery.NewTimeCol("last_evaluated_at"),
	LastEvaluatedBy: metaquery.NewTextCol("last_evaluated_by"),
}
