// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package db

import (
	"context"
)

const addSpec = `-- name: AddSpec :one
INSERT INTO zdx_specs (feature_id, description, kind) VALUES ($1, $2, $3)
RETURNING id, feature_id, description, kind
`

type AddSpecParams struct {
	FeatureID   int32  `db:"feature_id" json:"feature_id"`
	Description string `db:"description" json:"description"`
	Kind        string `db:"kind" json:"kind"`
}

func (q *Queries) AddSpec(ctx context.Context, arg AddSpecParams) (ZdxSpec, error) {
	row := q.db.QueryRow(ctx, addSpec, arg.FeatureID, arg.Description, arg.Kind)
	var i ZdxSpec
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.Description,
		&i.Kind,
	)
	return i, err
}

const deleteFeature = `-- name: DeleteFeature :exec
DELETE FROM zdx_features WHERE id = $1
`

func (q *Queries) DeleteFeature(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFeature, id)
	return err
}

const getFeature = `-- name: GetFeature :one
SELECT id, project_id, name, description, what, why, done_when, component, category
FROM zdx_features WHERE project_id = $1 AND name = $2
`

type GetFeatureParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) GetFeature(ctx context.Context, arg GetFeatureParams) (ZdxFeature, error) {
	row := q.db.QueryRow(ctx, getFeature, arg.ProjectID, arg.Name)
	var i ZdxFeature
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.What,
		&i.Why,
		&i.DoneWhen,
		&i.Component,
		&i.Category,
	)
	return i, err
}

const getPlanByFeature = `-- name: GetPlanByFeature :one
SELECT id, feature_id, plan_type, status, complexity, approach, last_reviewed_at
FROM zdx_plans WHERE feature_id = $1
`

func (q *Queries) GetPlanByFeature(ctx context.Context, featureID int32) (ZdxPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByFeature, featureID)
	var i ZdxPlan
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.PlanType,
		&i.Status,
		&i.Complexity,
		&i.Approach,
		&i.LastReviewedAt,
	)
	return i, err
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, project_id, name, description, what, why, done_when, component, category
FROM zdx_features WHERE project_id = $1 ORDER BY category, name
`

func (q *Queries) ListFeatures(ctx context.Context, projectID int32) ([]ZdxFeature, error) {
	rows, err := q.db.Query(ctx, listFeatures, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxFeature
	for rows.Next() {
		var i ZdxFeature
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.What,
			&i.Why,
			&i.DoneWhen,
			&i.Component,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecs = `-- name: ListSpecs :many
SELECT id, feature_id, description, kind FROM zdx_specs WHERE feature_id = $1 ORDER BY id
`

func (q *Queries) ListSpecs(ctx context.Context, featureID int32) ([]ZdxSpec, error) {
	rows, err := q.db.Query(ctx, listSpecs, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxSpec
	for rows.Next() {
		var i ZdxSpec
		if err := rows.Scan(
			&i.ID,
			&i.FeatureID,
			&i.Description,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureField = `-- name: UpdateFeatureField :exec
UPDATE zdx_features
SET description = CASE WHEN $1::text = 'description' THEN $2::text ELSE description END,
    what        = CASE WHEN $1::text = 'what'        THEN $2::text ELSE what        END,
    why         = CASE WHEN $1::text = 'why'         THEN $2::text ELSE why         END,
    done_when   = CASE WHEN $1::text = 'done_when'   THEN $2::text ELSE done_when   END,
    component   = CASE WHEN $1::text = 'component'   THEN $2::text ELSE component   END,
    category    = CASE WHEN $1::text = 'category'    THEN $2::text ELSE category    END
WHERE project_id = $3 AND name = $4
`

type UpdateFeatureFieldParams struct {
	Field     string `db:"field" json:"field"`
	Value     string `db:"value" json:"value"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) UpdateFeatureField(ctx context.Context, arg UpdateFeatureFieldParams) error {
	_, err := q.db.Exec(ctx, updateFeatureField,
		arg.Field,
		arg.Value,
		arg.ProjectID,
		arg.Name,
	)
	return err
}

const upsertFeature = `-- name: UpsertFeature :one
INSERT INTO zdx_features (project_id, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, name) DO UPDATE SET description = EXCLUDED.description
RETURNING id, project_id, name, description, what, why, done_when, component, category
`

type UpsertFeatureParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) UpsertFeature(ctx context.Context, arg UpsertFeatureParams) (ZdxFeature, error) {
	row := q.db.QueryRow(ctx, upsertFeature, arg.ProjectID, arg.Name, arg.Description)
	var i ZdxFeature
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.What,
		&i.Why,
		&i.DoneWhen,
		&i.Component,
		&i.Category,
	)
	return i, err
}

const upsertPlan = `-- name: UpsertPlan :one
INSERT INTO zdx_plans (feature_id, plan_type, complexity, approach, status)
VALUES ($1, $2, $3, $4, 'pending')
ON CONFLICT (feature_id) DO UPDATE
SET plan_type = EXCLUDED.plan_type,
    complexity = EXCLUDED.complexity,
    approach = EXCLUDED.approach,
    last_reviewed_at = NOW()
RETURNING id, feature_id, plan_type, status, complexity, approach, last_reviewed_at
`

type UpsertPlanParams struct {
	FeatureID  int32  `db:"feature_id" json:"feature_id"`
	PlanType   string `db:"plan_type" json:"plan_type"`
	Complexity string `db:"complexity" json:"complexity"`
	Approach   string `db:"approach" json:"approach"`
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) (ZdxPlan, error) {
	row := q.db.QueryRow(ctx, upsertPlan,
		arg.FeatureID,
		arg.PlanType,
		arg.Complexity,
		arg.Approach,
	)
	var i ZdxPlan
	err := row.Scan(
		&i.ID,
		&i.FeatureID,
		&i.PlanType,
		&i.Status,
		&i.Complexity,
		&i.Approach,
		&i.LastReviewedAt,
	)
	return i, err
}
