// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaAttachFileToIssue = metaquery.Query{
	Name:   "AttachFileToIssue",
	Cmd:    ":exec",
	Source: "files.sql",
	SQL: `INSERT INTO zdx_issue_files (issue_id, file_id, kind)
VALUES ($1, $2, $3)
ON CONFLICT (issue_id, file_id) DO NOTHING`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "file_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 3, Name: "kind", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_issue_files"},
}

// WrapAttachFileToIssue returns a metaquery.Builder over MetaAttachFileToIssue, pre-bound with typed arguments.
func WrapAttachFileToIssue(arg AttachFileToIssueParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaAttachFileToIssue, arg.IssueID, arg.FileID, arg.Kind)
}

var MetaCreateFile = metaquery.Query{
	Name:   "CreateFile",
	Cmd:    ":one",
	Source: "files.sql",
	SQL: `INSERT INTO zdx_files (provider, path, mime_type, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, provider, path, mime_type, size_bytes, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_files"},
		{Name: "provider", OriginalName: "provider", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "path", OriginalName: "path", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "mime_type", OriginalName: "mime_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "size_bytes", OriginalName: "size_bytes", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_files"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_files"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "provider", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "path", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "mime_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "size_bytes", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_files"},
}

// WrapCreateFile returns a metaquery.Builder over MetaCreateFile, pre-bound with typed arguments.
func WrapCreateFile(arg CreateFileParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateFile, arg.Provider, arg.Path, arg.MimeType, arg.SizeBytes)
}

// CreateFileCols gives typed, name-safe access to CreateFile's output columns.
var CreateFileCols = struct {
	ID        metaquery.IntCol
	Provider  metaquery.TextCol
	Path      metaquery.TextCol
	MimeType  metaquery.TextCol
	SizeBytes metaquery.IntCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	Provider:  metaquery.NewTextCol("provider"),
	Path:      metaquery.NewTextCol("path"),
	MimeType:  metaquery.NewTextCol("mime_type"),
	SizeBytes: metaquery.NewIntCol("size_bytes"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaGetFile = metaquery.Query{
	Name:   "GetFile",
	Cmd:    ":one",
	Source: "files.sql",
	SQL:    `SELECT id, provider, path, mime_type, size_bytes, created_at FROM zdx_files WHERE id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_files"},
		{Name: "provider", OriginalName: "provider", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "path", OriginalName: "path", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "mime_type", OriginalName: "mime_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "size_bytes", OriginalName: "size_bytes", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_files"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_files"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapGetFile returns a metaquery.Builder over MetaGetFile, pre-bound with typed arguments.
func WrapGetFile(id int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetFile, id)
}

// GetFileCols gives typed, name-safe access to GetFile's output columns.
var GetFileCols = struct {
	ID        metaquery.IntCol
	Provider  metaquery.TextCol
	Path      metaquery.TextCol
	MimeType  metaquery.TextCol
	SizeBytes metaquery.IntCol
	CreatedAt metaquery.TimeCol
}{
	ID:        metaquery.NewIntCol("id"),
	Provider:  metaquery.NewTextCol("provider"),
	Path:      metaquery.NewTextCol("path"),
	MimeType:  metaquery.NewTextCol("mime_type"),
	SizeBytes: metaquery.NewIntCol("size_bytes"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
}

var MetaGetIssueFiles = metaquery.Query{
	Name:   "GetIssueFiles",
	Cmd:    ":many",
	Source: "files.sql",
	SQL: `SELECT f.id, f.provider, f.path, f.mime_type, f.size_bytes, f.created_at, isf.kind
FROM zdx_files f
JOIN zdx_issue_files isf ON isf.file_id = f.id
WHERE isf.issue_id = $1
ORDER BY f.created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_files"},
		{Name: "provider", OriginalName: "provider", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "path", OriginalName: "path", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "mime_type", OriginalName: "mime_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_files"},
		{Name: "size_bytes", OriginalName: "size_bytes", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_files"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_files"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_files"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapGetIssueFiles returns a metaquery.Builder over MetaGetIssueFiles, pre-bound with typed arguments.
func WrapGetIssueFiles(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetIssueFiles, issueID)
}

// GetIssueFilesCols gives typed, name-safe access to GetIssueFiles's output columns.
var GetIssueFilesCols = struct {
	ID        metaquery.IntCol
	Provider  metaquery.TextCol
	Path      metaquery.TextCol
	MimeType  metaquery.TextCol
	SizeBytes metaquery.IntCol
	CreatedAt metaquery.TimeCol
	Kind      metaquery.TextCol
}{
	ID:        metaquery.NewIntCol("id"),
	Provider:  metaquery.NewTextCol("provider"),
	Path:      metaquery.NewTextCol("path"),
	MimeType:  metaquery.NewTextCol("mime_type"),
	SizeBytes: metaquery.NewIntCol("size_bytes"),
	CreatedAt: metaquery.NewTimeCol("created_at"),
	Kind:      metaquery.NewTextCol("kind"),
}
