// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: focuses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFocusBlocker = `-- name: AddFocusBlocker :exec
INSERT INTO zdx_focus_blockers (focus_id, issue_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFocusBlockerParams struct {
	FocusID int32  `db:"focus_id" json:"focus_id"`
	IssueID string `db:"issue_id" json:"issue_id"`
}

func (q *Queries) AddFocusBlocker(ctx context.Context, arg AddFocusBlockerParams) error {
	_, err := q.db.Exec(ctx, addFocusBlocker, arg.FocusID, arg.IssueID)
	return err
}

const addFocusFeature = `-- name: AddFocusFeature :exec
INSERT INTO zdx_focus_features (focus_id, feature_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFocusFeatureParams struct {
	FocusID   int32 `db:"focus_id" json:"focus_id"`
	FeatureID int32 `db:"feature_id" json:"feature_id"`
}

func (q *Queries) AddFocusFeature(ctx context.Context, arg AddFocusFeatureParams) error {
	_, err := q.db.Exec(ctx, addFocusFeature, arg.FocusID, arg.FeatureID)
	return err
}

const createFocus = `-- name: CreateFocus :one
INSERT INTO zdx_focuses (project_id, name, description, priority)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, priority, status, created_at, started_at, ended_at
`

type CreateFocusParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Priority    int32  `db:"priority" json:"priority"`
}

func (q *Queries) CreateFocus(ctx context.Context, arg CreateFocusParams) (ZdxFocuse, error) {
	row := q.db.QueryRow(ctx, createFocus,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Priority,
	)
	var i ZdxFocuse
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getFocusByID = `-- name: GetFocusByID :one
SELECT id, project_id, name, description, priority, status, created_at, started_at, ended_at
FROM zdx_focuses WHERE project_id = $1 AND id = $2
`

type GetFocusByIDParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int32 `db:"id" json:"id"`
}

func (q *Queries) GetFocusByID(ctx context.Context, arg GetFocusByIDParams) (ZdxFocuse, error) {
	row := q.db.QueryRow(ctx, getFocusByID, arg.ProjectID, arg.ID)
	var i ZdxFocuse
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getFocusByName = `-- name: GetFocusByName :one
SELECT id, project_id, name, description, priority, status, created_at, started_at, ended_at
FROM zdx_focuses WHERE project_id = $1 AND name = $2
`

type GetFocusByNameParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Name      string `db:"name" json:"name"`
}

func (q *Queries) GetFocusByName(ctx context.Context, arg GetFocusByNameParams) (ZdxFocuse, error) {
	row := q.db.QueryRow(ctx, getFocusByName, arg.ProjectID, arg.Name)
	var i ZdxFocuse
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const listFeatureFocuses = `-- name: ListFeatureFocuses :many
SELECT fo.id, fo.name, fo.priority, fo.status
FROM zdx_focus_features ff
JOIN zdx_focuses fo ON fo.id = ff.focus_id
WHERE ff.feature_id = $1
ORDER BY fo.priority, fo.name
`

type ListFeatureFocusesRow struct {
	ID       int32  `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Priority int32  `db:"priority" json:"priority"`
	Status   string `db:"status" json:"status"`
}

func (q *Queries) ListFeatureFocuses(ctx context.Context, featureID int32) ([]ListFeatureFocusesRow, error) {
	rows, err := q.db.Query(ctx, listFeatureFocuses, featureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureFocusesRow
	for rows.Next() {
		var i ListFeatureFocusesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFocusFeatures = `-- name: ListFocusFeatures :many
SELECT ff.feature_id, f.name, f.description, f.kind, f.goal_id, f.component
FROM zdx_focus_features ff
JOIN zdx_features f ON f.id = ff.feature_id
WHERE ff.focus_id = $1
ORDER BY f.name
`

type ListFocusFeaturesRow struct {
	FeatureID   int32       `db:"feature_id" json:"feature_id"`
	Name        string      `db:"name" json:"name"`
	Description string      `db:"description" json:"description"`
	Kind        string      `db:"kind" json:"kind"`
	GoalID      pgtype.Int4 `db:"goal_id" json:"goal_id"`
	Component   string      `db:"component" json:"component"`
}

func (q *Queries) ListFocusFeatures(ctx context.Context, focusID int32) ([]ListFocusFeaturesRow, error) {
	rows, err := q.db.Query(ctx, listFocusFeatures, focusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFocusFeaturesRow
	for rows.Next() {
		var i ListFocusFeaturesRow
		if err := rows.Scan(
			&i.FeatureID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.GoalID,
			&i.Component,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFocuses = `-- name: ListFocuses :many
SELECT f.id, f.name, f.description, f.priority, f.status, f.created_at,
       f.started_at, f.ended_at,
       COALESCE(STRING_AGG(fb.issue_id, ','), '') AS blockers
FROM zdx_focuses f
LEFT JOIN zdx_focus_blockers fb ON fb.focus_id = f.id
WHERE f.project_id = $1
GROUP BY f.id ORDER BY f.priority, f.name
`

type ListFocusesRow struct {
	ID          int32              `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Priority    int32              `db:"priority" json:"priority"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt   pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt     pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	Blockers    interface{}        `db:"blockers" json:"blockers"`
}

func (q *Queries) ListFocuses(ctx context.Context, projectID int32) ([]ListFocusesRow, error) {
	rows, err := q.db.Query(ctx, listFocuses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFocusesRow
	for rows.Next() {
		var i ListFocusesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Blockers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFocusBlocker = `-- name: RemoveFocusBlocker :exec
DELETE FROM zdx_focus_blockers WHERE focus_id = $1 AND issue_id = $2
`

type RemoveFocusBlockerParams struct {
	FocusID int32  `db:"focus_id" json:"focus_id"`
	IssueID string `db:"issue_id" json:"issue_id"`
}

func (q *Queries) RemoveFocusBlocker(ctx context.Context, arg RemoveFocusBlockerParams) error {
	_, err := q.db.Exec(ctx, removeFocusBlocker, arg.FocusID, arg.IssueID)
	return err
}

const removeFocusFeature = `-- name: RemoveFocusFeature :exec
DELETE FROM zdx_focus_features WHERE focus_id = $1 AND feature_id = $2
`

type RemoveFocusFeatureParams struct {
	FocusID   int32 `db:"focus_id" json:"focus_id"`
	FeatureID int32 `db:"feature_id" json:"feature_id"`
}

func (q *Queries) RemoveFocusFeature(ctx context.Context, arg RemoveFocusFeatureParams) error {
	_, err := q.db.Exec(ctx, removeFocusFeature, arg.FocusID, arg.FeatureID)
	return err
}

const updateFocusDates = `-- name: UpdateFocusDates :exec
UPDATE zdx_focuses SET started_at = $1, ended_at = $2
WHERE project_id = $3 AND id = $4
`

type UpdateFocusDatesParams struct {
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
	EndedAt   pgtype.Timestamptz `db:"ended_at" json:"ended_at"`
	ProjectID int32              `db:"project_id" json:"project_id"`
	ID        int32              `db:"id" json:"id"`
}

func (q *Queries) UpdateFocusDates(ctx context.Context, arg UpdateFocusDatesParams) error {
	_, err := q.db.Exec(ctx, updateFocusDates,
		arg.StartedAt,
		arg.EndedAt,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const updateFocusStatus = `-- name: UpdateFocusStatus :exec
UPDATE zdx_focuses SET status = $1 WHERE project_id = $2 AND id = $3
`

type UpdateFocusStatusParams struct {
	Status    string `db:"status" json:"status"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        int32  `db:"id" json:"id"`
}

func (q *Queries) UpdateFocusStatus(ctx context.Context, arg UpdateFocusStatusParams) error {
	_, err := q.db.Exec(ctx, updateFocusStatus, arg.Status, arg.ProjectID, arg.ID)
	return err
}
