// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCountProjectConstraints = metaquery.Query{
	Name:   "CountProjectConstraints",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL:    `SELECT count(*) FROM zdx_project_constraints WHERE project_id = $1`,
	Columns: []metaquery.Column{
		{Name: "count", OriginalName: "count", GoType: "int64"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapCountProjectConstraints returns a metaquery.Builder over MetaCountProjectConstraints, pre-bound with typed arguments.
func WrapCountProjectConstraints(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaCountProjectConstraints, projectID)
}

// CountProjectConstraintsCols gives typed, name-safe access to CountProjectConstraints's output columns.
var CountProjectConstraintsCols = struct {
	Count metaquery.IntCol
}{
	Count: metaquery.NewIntCol("count"),
}

var MetaCountProjectGoals = metaquery.Query{
	Name:   "CountProjectGoals",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL:    `SELECT count(*) FROM zdx_project_goals WHERE project_id = $1`,
	Columns: []metaquery.Column{
		{Name: "count", OriginalName: "count", GoType: "int64"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapCountProjectGoals returns a metaquery.Builder over MetaCountProjectGoals, pre-bound with typed arguments.
func WrapCountProjectGoals(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaCountProjectGoals, projectID)
}

// CountProjectGoalsCols gives typed, name-safe access to CountProjectGoals's output columns.
var CountProjectGoalsCols = struct {
	Count metaquery.IntCol
}{
	Count: metaquery.NewIntCol("count"),
}

var MetaCreateProjectConstraint = metaquery.Query{
	Name:   "CreateProjectConstraint",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL: `INSERT INTO zdx_project_constraints (project_id, title, description, priority, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, title, description, priority, status, created_at, updated_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "description", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 5, Name: "status", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_project_constraints"},
}

// WrapCreateProjectConstraint returns a metaquery.Builder over MetaCreateProjectConstraint, pre-bound with typed arguments.
func WrapCreateProjectConstraint(arg CreateProjectConstraintParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateProjectConstraint, arg.ProjectID, arg.Title, arg.Description, arg.Priority, arg.Status)
}

// CreateProjectConstraintCols gives typed, name-safe access to CreateProjectConstraint's output columns.
var CreateProjectConstraintCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaCreateProjectGoal = metaquery.Query{
	Name:   "CreateProjectGoal",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL: `INSERT INTO zdx_project_goals (project_id, title, description, priority, status, metric_name, metric_unit)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, title, description, priority, status, metric_name, metric_unit, created_at, updated_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_name", OriginalName: "metric_name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_unit", OriginalName: "metric_unit", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "description", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 5, Name: "status", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "metric_name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "metric_unit", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_project_goals"},
}

// WrapCreateProjectGoal returns a metaquery.Builder over MetaCreateProjectGoal, pre-bound with typed arguments.
func WrapCreateProjectGoal(arg CreateProjectGoalParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateProjectGoal, arg.ProjectID, arg.Title, arg.Description, arg.Priority, arg.Status, arg.MetricName, arg.MetricUnit)
}

// CreateProjectGoalCols gives typed, name-safe access to CreateProjectGoal's output columns.
var CreateProjectGoalCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	MetricName  metaquery.TextCol
	MetricUnit  metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	MetricName:  metaquery.NewTextCol("metric_name"),
	MetricUnit:  metaquery.NewTextCol("metric_unit"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaDeleteProjectConstraint = metaquery.Query{
	Name:   "DeleteProjectConstraint",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL:    `DELETE FROM zdx_project_constraints WHERE id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapDeleteProjectConstraint returns a metaquery.Builder over MetaDeleteProjectConstraint, pre-bound with typed arguments.
func WrapDeleteProjectConstraint(id int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteProjectConstraint, id)
}

var MetaDeleteProjectGoal = metaquery.Query{
	Name:   "DeleteProjectGoal",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL:    `DELETE FROM zdx_project_goals WHERE id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapDeleteProjectGoal returns a metaquery.Builder over MetaDeleteProjectGoal, pre-bound with typed arguments.
func WrapDeleteProjectGoal(id int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteProjectGoal, id)
}

var MetaGetProjectConstraint = metaquery.Query{
	Name:   "GetProjectConstraint",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL: `SELECT id, project_id, title, description, priority, status, created_at, updated_at
FROM zdx_project_constraints WHERE id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapGetProjectConstraint returns a metaquery.Builder over MetaGetProjectConstraint, pre-bound with typed arguments.
func WrapGetProjectConstraint(id int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetProjectConstraint, id)
}

// GetProjectConstraintCols gives typed, name-safe access to GetProjectConstraint's output columns.
var GetProjectConstraintCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaGetProjectGoal = metaquery.Query{
	Name:   "GetProjectGoal",
	Cmd:    ":one",
	Source: "goals.sql",
	SQL: `SELECT id, project_id, title, description, priority, status, metric_name, metric_unit, created_at, updated_at
FROM zdx_project_goals WHERE id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_name", OriginalName: "metric_name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_unit", OriginalName: "metric_unit", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapGetProjectGoal returns a metaquery.Builder over MetaGetProjectGoal, pre-bound with typed arguments.
func WrapGetProjectGoal(id int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetProjectGoal, id)
}

// GetProjectGoalCols gives typed, name-safe access to GetProjectGoal's output columns.
var GetProjectGoalCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	MetricName  metaquery.TextCol
	MetricUnit  metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	MetricName:  metaquery.NewTextCol("metric_name"),
	MetricUnit:  metaquery.NewTextCol("metric_unit"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaLinkGoalIssue = metaquery.Query{
	Name:   "LinkGoalIssue",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL: `INSERT INTO zdx_goal_issues (goal_id, issue_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "goal_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_goal_issues"},
}

// WrapLinkGoalIssue returns a metaquery.Builder over MetaLinkGoalIssue, pre-bound with typed arguments.
func WrapLinkGoalIssue(arg LinkGoalIssueParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaLinkGoalIssue, arg.GoalID, arg.IssueID)
}

var MetaListGoalIssues = metaquery.Query{
	Name:   "ListGoalIssues",
	Cmd:    ":many",
	Source: "goals.sql",
	SQL:    `SELECT issue_id FROM zdx_goal_issues WHERE goal_id = $1`,
	Columns: []metaquery.Column{
		{Name: "issue_id", OriginalName: "issue_id", GoType: "string"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "goal_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapListGoalIssues returns a metaquery.Builder over MetaListGoalIssues, pre-bound with typed arguments.
func WrapListGoalIssues(goalID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaListGoalIssues, goalID)
}

// ListGoalIssuesCols gives typed, name-safe access to ListGoalIssues's output columns.
var ListGoalIssuesCols = struct {
	IssueID metaquery.TextCol
}{
	IssueID: metaquery.NewTextCol("issue_id"),
}

var MetaListIssueGoals = metaquery.Query{
	Name:   "ListIssueGoals",
	Cmd:    ":many",
	Source: "goals.sql",
	SQL: `SELECT g.id, g.project_id, g.title, g.description, g.priority, g.status, g.metric_name, g.metric_unit, g.created_at, g.updated_at
FROM zdx_project_goals g
JOIN zdx_goal_issues gi ON gi.goal_id = g.id
WHERE gi.issue_id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_name", OriginalName: "metric_name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_unit", OriginalName: "metric_unit", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssueGoals returns a metaquery.Builder over MetaListIssueGoals, pre-bound with typed arguments.
func WrapListIssueGoals(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssueGoals, issueID)
}

// ListIssueGoalsCols gives typed, name-safe access to ListIssueGoals's output columns.
var ListIssueGoalsCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	MetricName  metaquery.TextCol
	MetricUnit  metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	MetricName:  metaquery.NewTextCol("metric_name"),
	MetricUnit:  metaquery.NewTextCol("metric_unit"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaListProjectConstraints = metaquery.Query{
	Name:   "ListProjectConstraints",
	Cmd:    ":many",
	Source: "goals.sql",
	SQL: `SELECT id, project_id, title, description, priority, status, created_at, updated_at
FROM zdx_project_constraints WHERE project_id = $1
ORDER BY priority, title`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_constraints"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapListProjectConstraints returns a metaquery.Builder over MetaListProjectConstraints, pre-bound with typed arguments.
func WrapListProjectConstraints(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaListProjectConstraints, projectID)
}

// ListProjectConstraintsCols gives typed, name-safe access to ListProjectConstraints's output columns.
var ListProjectConstraintsCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaListProjectGoals = metaquery.Query{
	Name:   "ListProjectGoals",
	Cmd:    ":many",
	Source: "goals.sql",
	SQL: `SELECT id, project_id, title, description, priority, status, metric_name, metric_unit, created_at, updated_at
FROM zdx_project_goals WHERE project_id = $1
ORDER BY priority, title`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "title", OriginalName: "title", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "description", OriginalName: "description", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_project_goals"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_name", OriginalName: "metric_name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "metric_unit", OriginalName: "metric_unit", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_project_goals"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
		{Name: "updated_at", OriginalName: "updated_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_project_goals"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapListProjectGoals returns a metaquery.Builder over MetaListProjectGoals, pre-bound with typed arguments.
func WrapListProjectGoals(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaListProjectGoals, projectID)
}

// ListProjectGoalsCols gives typed, name-safe access to ListProjectGoals's output columns.
var ListProjectGoalsCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Title       metaquery.TextCol
	Description metaquery.TextCol
	Priority    metaquery.IntCol
	Status      metaquery.TextCol
	MetricName  metaquery.TextCol
	MetricUnit  metaquery.TextCol
	CreatedAt   metaquery.TimeCol
	UpdatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Title:       metaquery.NewTextCol("title"),
	Description: metaquery.NewTextCol("description"),
	Priority:    metaquery.NewIntCol("priority"),
	Status:      metaquery.NewTextCol("status"),
	MetricName:  metaquery.NewTextCol("metric_name"),
	MetricUnit:  metaquery.NewTextCol("metric_unit"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
	UpdatedAt:   metaquery.NewTimeCol("updated_at"),
}

var MetaUnlinkGoalIssue = metaquery.Query{
	Name:   "UnlinkGoalIssue",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL:    `DELETE FROM zdx_goal_issues WHERE goal_id = $1 AND issue_id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "goal_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapUnlinkGoalIssue returns a metaquery.Builder over MetaUnlinkGoalIssue, pre-bound with typed arguments.
func WrapUnlinkGoalIssue(arg UnlinkGoalIssueParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUnlinkGoalIssue, arg.GoalID, arg.IssueID)
}

var MetaUpdateProjectConstraint = metaquery.Query{
	Name:   "UpdateProjectConstraint",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL: `UPDATE zdx_project_constraints
SET title       = $2,
    description = $3,
    priority    = $4,
    status      = $5,
    updated_at  = NOW()
WHERE id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "description", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 5, Name: "status", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapUpdateProjectConstraint returns a metaquery.Builder over MetaUpdateProjectConstraint, pre-bound with typed arguments.
func WrapUpdateProjectConstraint(arg UpdateProjectConstraintParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateProjectConstraint, arg.ID, arg.Title, arg.Description, arg.Priority, arg.Status)
}

var MetaUpdateProjectGoal = metaquery.Query{
	Name:   "UpdateProjectGoal",
	Cmd:    ":exec",
	Source: "goals.sql",
	SQL: `UPDATE zdx_project_goals
SET title       = $2,
    description = $3,
    priority    = $4,
    status      = $5,
    metric_name = $6,
    metric_unit = $7,
    updated_at  = NOW()
WHERE id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "title", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "description", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 5, Name: "status", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "metric_name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "metric_unit", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapUpdateProjectGoal returns a metaquery.Builder over MetaUpdateProjectGoal, pre-bound with typed arguments.
func WrapUpdateProjectGoal(arg UpdateProjectGoalParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateProjectGoal, arg.ID, arg.Title, arg.Description, arg.Priority, arg.Status, arg.MetricName, arg.MetricUnit)
}
