// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incomplete_report_side_effects.sql

package db

import (
	"context"
)

const insertSideEffectIfNew = `-- name: InsertSideEffectIfNew :one
INSERT INTO zdx_incomplete_report_side_effects (project_id, reason, evidence_fingerprint, action_type, meta)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, reason, evidence_fingerprint, action_type) DO NOTHING
RETURNING id, project_id, reason, evidence_fingerprint, action_type, meta, fired_at
`

type InsertSideEffectIfNewParams struct {
	ProjectID           int32  `db:"project_id" json:"project_id"`
	Reason              string `db:"reason" json:"reason"`
	EvidenceFingerprint string `db:"evidence_fingerprint" json:"evidence_fingerprint"`
	ActionType          string `db:"action_type" json:"action_type"`
	Meta                []byte `db:"meta" json:"meta"`
}

func (q *Queries) InsertSideEffectIfNew(ctx context.Context, arg InsertSideEffectIfNewParams) (ZdxIncompleteReportSideEffect, error) {
	row := q.db.QueryRow(ctx, insertSideEffectIfNew,
		arg.ProjectID,
		arg.Reason,
		arg.EvidenceFingerprint,
		arg.ActionType,
		arg.Meta,
	)
	var i ZdxIncompleteReportSideEffect
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Reason,
		&i.EvidenceFingerprint,
		&i.ActionType,
		&i.Meta,
		&i.FiredAt,
	)
	return i, err
}

const listSideEffects = `-- name: ListSideEffects :many
SELECT id, project_id, reason, evidence_fingerprint, action_type, meta, fired_at
FROM zdx_incomplete_report_side_effects
WHERE project_id = $1
ORDER BY fired_at DESC
`

func (q *Queries) ListSideEffects(ctx context.Context, projectID int32) ([]ZdxIncompleteReportSideEffect, error) {
	rows, err := q.db.Query(ctx, listSideEffects, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIncompleteReportSideEffect
	for rows.Next() {
		var i ZdxIncompleteReportSideEffect
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Reason,
			&i.EvidenceFingerprint,
			&i.ActionType,
			&i.Meta,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
