// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegrationToken = `-- name: CreateIntegrationToken :one
INSERT INTO zdx_integration_token (project_id, component, name, token_hash, token_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, component, name, token_prefix, created_at, revoked_at
`

type CreateIntegrationTokenParams struct {
	ProjectID   int32       `db:"project_id" json:"project_id"`
	Component   pgtype.Text `db:"component" json:"component"`
	Name        string      `db:"name" json:"name"`
	TokenHash   string      `db:"token_hash" json:"token_hash"`
	TokenPrefix string      `db:"token_prefix" json:"token_prefix"`
}

type CreateIntegrationTokenRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	Component   pgtype.Text        `db:"component" json:"component"`
	Name        string             `db:"name" json:"name"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) CreateIntegrationToken(ctx context.Context, arg CreateIntegrationTokenParams) (CreateIntegrationTokenRow, error) {
	row := q.db.QueryRow(ctx, createIntegrationToken,
		arg.ProjectID,
		arg.Component,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
	)
	var i CreateIntegrationTokenRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Component,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteIntegrationToken = `-- name: DeleteIntegrationToken :exec
DELETE FROM zdx_integration_token WHERE id = $1
`

func (q *Queries) DeleteIntegrationToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIntegrationToken, id)
	return err
}

const getIntegrationTokenByHash = `-- name: GetIntegrationTokenByHash :one
SELECT id, project_id, component, name, token_prefix, created_at, revoked_at
FROM zdx_integration_token
WHERE token_hash = $1
`

type GetIntegrationTokenByHashRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	Component   pgtype.Text        `db:"component" json:"component"`
	Name        string             `db:"name" json:"name"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) GetIntegrationTokenByHash(ctx context.Context, tokenHash string) (GetIntegrationTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getIntegrationTokenByHash, tokenHash)
	var i GetIntegrationTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Component,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listIntegrationTokens = `-- name: ListIntegrationTokens :many
SELECT id, project_id, component, name, token_prefix, created_at, revoked_at
FROM zdx_integration_token
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY created_at DESC
`

type ListIntegrationTokensRow struct {
	ID          int32              `db:"id" json:"id"`
	ProjectID   int32              `db:"project_id" json:"project_id"`
	Component   pgtype.Text        `db:"component" json:"component"`
	Name        string             `db:"name" json:"name"`
	TokenPrefix string             `db:"token_prefix" json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListIntegrationTokens(ctx context.Context, projectID pgtype.Int4) ([]ListIntegrationTokensRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationTokens, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationTokensRow
	for rows.Next() {
		var i ListIntegrationTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Component,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeIntegrationToken = `-- name: RevokeIntegrationToken :exec
UPDATE zdx_integration_token SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeIntegrationToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeIntegrationToken, id)
	return err
}
