// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_resolutions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addResolutionCommit = `-- name: AddResolutionCommit :exec
INSERT INTO zdx_issue_resolution_commits (resolution_id, sha, ord)
VALUES ($1, $2, $3)
`

type AddResolutionCommitParams struct {
	ResolutionID string `db:"resolution_id" json:"resolution_id"`
	Sha          string `db:"sha" json:"sha"`
	Ord          int32  `db:"ord" json:"ord"`
}

func (q *Queries) AddResolutionCommit(ctx context.Context, arg AddResolutionCommitParams) error {
	_, err := q.db.Exec(ctx, addResolutionCommit, arg.ResolutionID, arg.Sha, arg.Ord)
	return err
}

const countIssueResolutions = `-- name: CountIssueResolutions :one
SELECT count(*) FROM zdx_issue_resolutions WHERE issue_id = $1
`

func (q *Queries) CountIssueResolutions(ctx context.Context, issueID string) (int64, error) {
	row := q.db.QueryRow(ctx, countIssueResolutions, issueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssueResolution = `-- name: CreateIssueResolution :one
INSERT INTO zdx_issue_resolutions (id, issue_id, branch_of_origin, resolved_at, author, source, parent_resolution_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, issue_id, branch_of_origin, resolved_at, author, source, parent_resolution_id, created_at
`

type CreateIssueResolutionParams struct {
	ID                 string             `db:"id" json:"id"`
	IssueID            string             `db:"issue_id" json:"issue_id"`
	BranchOfOrigin     string             `db:"branch_of_origin" json:"branch_of_origin"`
	ResolvedAt         pgtype.Timestamptz `db:"resolved_at" json:"resolved_at"`
	Author             string             `db:"author" json:"author"`
	Source             string             `db:"source" json:"source"`
	ParentResolutionID pgtype.Text        `db:"parent_resolution_id" json:"parent_resolution_id"`
}

func (q *Queries) CreateIssueResolution(ctx context.Context, arg CreateIssueResolutionParams) (ZdxIssueResolution, error) {
	row := q.db.QueryRow(ctx, createIssueResolution,
		arg.ID,
		arg.IssueID,
		arg.BranchOfOrigin,
		arg.ResolvedAt,
		arg.Author,
		arg.Source,
		arg.ParentResolutionID,
	)
	var i ZdxIssueResolution
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.BranchOfOrigin,
		&i.ResolvedAt,
		&i.Author,
		&i.Source,
		&i.ParentResolutionID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIssueResolution = `-- name: DeleteIssueResolution :exec
DELETE FROM zdx_issue_resolutions WHERE id = $1
`

func (q *Queries) DeleteIssueResolution(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteIssueResolution, id)
	return err
}

const getIssueResolution = `-- name: GetIssueResolution :one
SELECT r.id, r.issue_id, r.branch_of_origin, r.resolved_at, r.author, r.source, r.parent_resolution_id, r.created_at
FROM zdx_issue_resolutions r
WHERE r.id = $1
`

func (q *Queries) GetIssueResolution(ctx context.Context, id string) (ZdxIssueResolution, error) {
	row := q.db.QueryRow(ctx, getIssueResolution, id)
	var i ZdxIssueResolution
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.BranchOfOrigin,
		&i.ResolvedAt,
		&i.Author,
		&i.Source,
		&i.ParentResolutionID,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueResolutions = `-- name: ListIssueResolutions :many
SELECT r.id, r.issue_id, r.branch_of_origin, r.resolved_at, r.author, r.source, r.parent_resolution_id, r.created_at
FROM zdx_issue_resolutions r
WHERE r.issue_id = $1
ORDER BY r.resolved_at DESC
`

func (q *Queries) ListIssueResolutions(ctx context.Context, issueID string) ([]ZdxIssueResolution, error) {
	rows, err := q.db.Query(ctx, listIssueResolutions, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssueResolution
	for rows.Next() {
		var i ZdxIssueResolution
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.BranchOfOrigin,
			&i.ResolvedAt,
			&i.Author,
			&i.Source,
			&i.ParentResolutionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolutionCommits = `-- name: ListResolutionCommits :many
SELECT resolution_id, sha, ord
FROM zdx_issue_resolution_commits
WHERE resolution_id = $1
ORDER BY ord
`

func (q *Queries) ListResolutionCommits(ctx context.Context, resolutionID string) ([]ZdxIssueResolutionCommit, error) {
	rows, err := q.db.Query(ctx, listResolutionCommits, resolutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssueResolutionCommit
	for rows.Next() {
		var i ZdxIssueResolutionCommit
		if err := rows.Scan(&i.ResolutionID, &i.Sha, &i.Ord); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolutionsByProject = `-- name: ListResolutionsByProject :many
SELECT r.id, r.issue_id, r.branch_of_origin, r.resolved_at, r.author, r.source, r.parent_resolution_id, r.created_at
FROM zdx_issue_resolutions r
JOIN zdx_issues i ON i.id = r.issue_id
WHERE i.project_id = $1
ORDER BY r.resolved_at DESC
`

func (q *Queries) ListResolutionsByProject(ctx context.Context, projectID int32) ([]ZdxIssueResolution, error) {
	rows, err := q.db.Query(ctx, listResolutionsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssueResolution
	for rows.Next() {
		var i ZdxIssueResolution
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.BranchOfOrigin,
			&i.ResolvedAt,
			&i.Author,
			&i.Source,
			&i.ParentResolutionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedNamedBranchesForIssue = `-- name: ListUnresolvedNamedBranchesForIssue :many
SELECT vb.name
FROM zdx_version_branches vb
WHERE vb.project_id = $1
  AND vb.role = 'named-release'
  AND vb.status = 'active'
  AND NOT EXISTS (
    SELECT 1 FROM zdx_issue_resolutions r
    WHERE r.issue_id = $2
      AND r.branch_of_origin = vb.name
  )
ORDER BY vb.name
`

type ListUnresolvedNamedBranchesForIssueParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	IssueID   string `db:"issue_id" json:"issue_id"`
}

func (q *Queries) ListUnresolvedNamedBranchesForIssue(ctx context.Context, arg ListUnresolvedNamedBranchesForIssueParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUnresolvedNamedBranchesForIssue, arg.ProjectID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
