// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_blocks.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaAddIssueBlock = metaquery.Query{
	Name:   "AddIssueBlock",
	Cmd:    ":exec",
	Source: "issue_blocks.sql",
	SQL: `INSERT INTO zdx_issue_blocks (issue_id, blocked_by_id, kind) VALUES ($1, $2, $3)
ON CONFLICT (issue_id, blocked_by_id) DO UPDATE SET kind = EXCLUDED.kind`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "kind", GoType: "string", DBType: "text", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_issue_blocks"},
}

// WrapAddIssueBlock returns a metaquery.Builder over MetaAddIssueBlock, pre-bound with typed arguments.
func WrapAddIssueBlock(arg AddIssueBlockParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaAddIssueBlock, arg.IssueID, arg.BlockedByID, arg.Kind)
}

var MetaListAncestorSequencingBlockers = metaquery.Query{
	Name:   "ListAncestorSequencingBlockers",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL: `WITH RECURSIVE ancestry(child_id, ancestor_id) AS (
  SELECT seed.id, seed.id FROM zdx_issues AS seed WHERE seed.project_id = $1
  UNION
  SELECT a.child_id, b.issue_id
  FROM ancestry a
  JOIN zdx_issue_blocks b ON b.blocked_by_id = a.ancestor_id
  WHERE b.kind = 'composition'
)
SELECT DISTINCT
  a.child_id      AS child_id,
  b.blocked_by_id AS blocker_id,
  a.ancestor_id   AS gated_ancestor
FROM ancestry a
JOIN zdx_issue_blocks b ON b.issue_id = a.ancestor_id
JOIN zdx_issues i        ON i.id = b.blocked_by_id
WHERE b.kind = 'sequencing'
  AND COALESCE(i.status, 'open') = 'open'`,
	Columns: []metaquery.Column{
		{Name: "child_id", OriginalName: "child_id", GoType: "string", DBType: "text", NotNull: true, Table: "ancestry"},
		{Name: "blocker_id", OriginalName: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_blocks"},
		{Name: "gated_ancestor", OriginalName: "ancestor_id", GoType: "string", DBType: "text", NotNull: true, Table: "ancestry"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapListAncestorSequencingBlockers returns a metaquery.Builder over MetaListAncestorSequencingBlockers, pre-bound with typed arguments.
func WrapListAncestorSequencingBlockers(projectID int32) *metaquery.Builder {
	return metaquery.Wrap(&MetaListAncestorSequencingBlockers, projectID)
}

// ListAncestorSequencingBlockersCols gives typed, name-safe access to ListAncestorSequencingBlockers's output columns.
var ListAncestorSequencingBlockersCols = struct {
	ChildID       metaquery.TextCol
	BlockerID     metaquery.TextCol
	GatedAncestor metaquery.TextCol
}{
	ChildID:       metaquery.NewTextCol("child_id"),
	BlockerID:     metaquery.NewTextCol("blocked_by_id"),
	GatedAncestor: metaquery.NewTextCol("ancestor_id"),
}

var MetaListIssueBlockers = metaquery.Query{
	Name:   "ListIssueBlockers",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL:    `SELECT blocked_by_id FROM zdx_issue_blocks WHERE issue_id = $1`,
	Columns: []metaquery.Column{
		{Name: "blocked_by_id", OriginalName: "blocked_by_id", GoType: "string"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssueBlockers returns a metaquery.Builder over MetaListIssueBlockers, pre-bound with typed arguments.
func WrapListIssueBlockers(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssueBlockers, issueID)
}

// ListIssueBlockersCols gives typed, name-safe access to ListIssueBlockers's output columns.
var ListIssueBlockersCols = struct {
	BlockedByID metaquery.TextCol
}{
	BlockedByID: metaquery.NewTextCol("blocked_by_id"),
}

var MetaListIssueBlockersWithStatus = metaquery.Query{
	Name:   "ListIssueBlockersWithStatus",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL: `SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status, b.kind
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_blocks"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issues"},
		{Name: "kind", OriginalName: "kind", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_blocks"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssueBlockersWithStatus returns a metaquery.Builder over MetaListIssueBlockersWithStatus, pre-bound with typed arguments.
func WrapListIssueBlockersWithStatus(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssueBlockersWithStatus, issueID)
}

// ListIssueBlockersWithStatusCols gives typed, name-safe access to ListIssueBlockersWithStatus's output columns.
var ListIssueBlockersWithStatusCols = struct {
	ID     metaquery.TextCol
	Status metaquery.TextCol
	Kind   metaquery.TextCol
}{
	ID:     metaquery.NewTextCol("blocked_by_id"),
	Status: metaquery.NewTextCol("status"),
	Kind:   metaquery.NewTextCol("kind"),
}

var MetaListIssueCompositionChildrenWithStatus = metaquery.Query{
	Name:   "ListIssueCompositionChildrenWithStatus",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL: `SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1 AND b.kind = 'composition'`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_blocks"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issues"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssueCompositionChildrenWithStatus returns a metaquery.Builder over MetaListIssueCompositionChildrenWithStatus, pre-bound with typed arguments.
func WrapListIssueCompositionChildrenWithStatus(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssueCompositionChildrenWithStatus, issueID)
}

// ListIssueCompositionChildrenWithStatusCols gives typed, name-safe access to ListIssueCompositionChildrenWithStatus's output columns.
var ListIssueCompositionChildrenWithStatusCols = struct {
	ID     metaquery.TextCol
	Status metaquery.TextCol
}{
	ID:     metaquery.NewTextCol("blocked_by_id"),
	Status: metaquery.NewTextCol("status"),
}

var MetaListIssueSequencingBlockersWithStatus = metaquery.Query{
	Name:   "ListIssueSequencingBlockersWithStatus",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL: `SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1 AND b.kind = 'sequencing'`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issue_blocks"},
		{Name: "status", OriginalName: "status", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_issues"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssueSequencingBlockersWithStatus returns a metaquery.Builder over MetaListIssueSequencingBlockersWithStatus, pre-bound with typed arguments.
func WrapListIssueSequencingBlockersWithStatus(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssueSequencingBlockersWithStatus, issueID)
}

// ListIssueSequencingBlockersWithStatusCols gives typed, name-safe access to ListIssueSequencingBlockersWithStatus's output columns.
var ListIssueSequencingBlockersWithStatusCols = struct {
	ID     metaquery.TextCol
	Status metaquery.TextCol
}{
	ID:     metaquery.NewTextCol("blocked_by_id"),
	Status: metaquery.NewTextCol("status"),
}

var MetaListIssuesBlockedBy = metaquery.Query{
	Name:   "ListIssuesBlockedBy",
	Cmd:    ":many",
	Source: "issue_blocks.sql",
	SQL:    `SELECT issue_id FROM zdx_issue_blocks WHERE blocked_by_id = $1`,
	Columns: []metaquery.Column{
		{Name: "issue_id", OriginalName: "issue_id", GoType: "string"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListIssuesBlockedBy returns a metaquery.Builder over MetaListIssuesBlockedBy, pre-bound with typed arguments.
func WrapListIssuesBlockedBy(blockedByID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaListIssuesBlockedBy, blockedByID)
}

// ListIssuesBlockedByCols gives typed, name-safe access to ListIssuesBlockedBy's output columns.
var ListIssuesBlockedByCols = struct {
	IssueID metaquery.TextCol
}{
	IssueID: metaquery.NewTextCol("issue_id"),
}

var MetaRemoveAllIssueBlocks = metaquery.Query{
	Name:   "RemoveAllIssueBlocks",
	Cmd:    ":exec",
	Source: "issue_blocks.sql",
	SQL:    `DELETE FROM zdx_issue_blocks WHERE issue_id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapRemoveAllIssueBlocks returns a metaquery.Builder over MetaRemoveAllIssueBlocks, pre-bound with typed arguments.
func WrapRemoveAllIssueBlocks(issueID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaRemoveAllIssueBlocks, issueID)
}

var MetaRemoveIssueBlock = metaquery.Query{
	Name:   "RemoveIssueBlock",
	Cmd:    ":exec",
	Source: "issue_blocks.sql",
	SQL:    `DELETE FROM zdx_issue_blocks WHERE issue_id = $1 AND blocked_by_id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "blocked_by_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapRemoveIssueBlock returns a metaquery.Builder over MetaRemoveIssueBlock, pre-bound with typed arguments.
func WrapRemoveIssueBlock(arg RemoveIssueBlockParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaRemoveIssueBlock, arg.IssueID, arg.BlockedByID)
}
