// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_blocks.sql

package db

import (
	"context"
)

const addIssueBlock = `-- name: AddIssueBlock :exec
INSERT INTO zdx_issue_blocks (issue_id, blocked_by_id, kind) VALUES ($1, $2, $3)
ON CONFLICT (issue_id, blocked_by_id) DO UPDATE SET kind = EXCLUDED.kind
`

type AddIssueBlockParams struct {
	IssueID     string `db:"issue_id" json:"issue_id"`
	BlockedByID string `db:"blocked_by_id" json:"blocked_by_id"`
	Kind        string `db:"kind" json:"kind"`
}

// kind: 'sequencing' (default) for "X waits for Y" deps; 'composition' for tracker → child relationships.
// ON CONFLICT updates kind so existing edges can be reclassified (e.g. backfilling pre-migration
// tracker edges from 'sequencing' to 'composition').
func (q *Queries) AddIssueBlock(ctx context.Context, arg AddIssueBlockParams) error {
	_, err := q.db.Exec(ctx, addIssueBlock, arg.IssueID, arg.BlockedByID, arg.Kind)
	return err
}

const listAncestorSequencingBlockers = `-- name: ListAncestorSequencingBlockers :many
WITH RECURSIVE ancestry(child_id, ancestor_id) AS (
  SELECT seed.id, seed.id FROM zdx_issues AS seed WHERE seed.project_id = $1
  UNION
  SELECT a.child_id, b.issue_id
  FROM ancestry a
  JOIN zdx_issue_blocks b ON b.blocked_by_id = a.ancestor_id
  WHERE b.kind = 'composition'
)
SELECT DISTINCT
  a.child_id      AS child_id,
  b.blocked_by_id AS blocker_id,
  a.ancestor_id   AS gated_ancestor
FROM ancestry a
JOIN zdx_issue_blocks b ON b.issue_id = a.ancestor_id
JOIN zdx_issues i        ON i.id = b.blocked_by_id
WHERE b.kind = 'sequencing'
  AND COALESCE(i.status, 'open') = 'open'
`

type ListAncestorSequencingBlockersRow struct {
	ChildID       string `db:"child_id" json:"child_id"`
	BlockerID     string `db:"blocker_id" json:"blocker_id"`
	GatedAncestor string `db:"gated_ancestor" json:"gated_ancestor"`
}

// For every issue in the project, walk up the composition chain (issue → parents)
// and return any open sequencing blockers found anywhere in the ancestry, INCLUDING
// the issue itself. Used by the queue's claim-check to gate composition children of
// a blocked tracker without per-leaf wiring.
//
// Composition edge layout (per --parent flow): (issue_id=parent, blocked_by_id=child).
// So to walk from a child up, recurse: child's parent = (rows where blocked_by_id = child).id_field=issue_id.
func (q *Queries) ListAncestorSequencingBlockers(ctx context.Context, projectID int32) ([]ListAncestorSequencingBlockersRow, error) {
	rows, err := q.db.Query(ctx, listAncestorSequencingBlockers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAncestorSequencingBlockersRow
	for rows.Next() {
		var i ListAncestorSequencingBlockersRow
		if err := rows.Scan(&i.ChildID, &i.BlockerID, &i.GatedAncestor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueBlockers = `-- name: ListIssueBlockers :many
SELECT blocked_by_id FROM zdx_issue_blocks WHERE issue_id = $1
`

func (q *Queries) ListIssueBlockers(ctx context.Context, issueID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listIssueBlockers, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocked_by_id string
		if err := rows.Scan(&blocked_by_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_by_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueBlockersWithStatus = `-- name: ListIssueBlockersWithStatus :many
SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status, b.kind
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1
`

type ListIssueBlockersWithStatusRow struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
	Kind   string `db:"kind" json:"kind"`
}

func (q *Queries) ListIssueBlockersWithStatus(ctx context.Context, issueID string) ([]ListIssueBlockersWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listIssueBlockersWithStatus, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueBlockersWithStatusRow
	for rows.Next() {
		var i ListIssueBlockersWithStatusRow
		if err := rows.Scan(&i.ID, &i.Status, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueCompositionChildrenWithStatus = `-- name: ListIssueCompositionChildrenWithStatus :many
SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1 AND b.kind = 'composition'
`

type ListIssueCompositionChildrenWithStatusRow struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) ListIssueCompositionChildrenWithStatus(ctx context.Context, issueID string) ([]ListIssueCompositionChildrenWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listIssueCompositionChildrenWithStatus, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueCompositionChildrenWithStatusRow
	for rows.Next() {
		var i ListIssueCompositionChildrenWithStatusRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSequencingBlockersWithStatus = `-- name: ListIssueSequencingBlockersWithStatus :many
SELECT b.blocked_by_id AS id, COALESCE(i.status, 'open') AS status
FROM zdx_issue_blocks b
LEFT JOIN zdx_issues i ON i.id = b.blocked_by_id
WHERE b.issue_id = $1 AND b.kind = 'sequencing'
`

type ListIssueSequencingBlockersWithStatusRow struct {
	ID     string `db:"id" json:"id"`
	Status string `db:"status" json:"status"`
}

func (q *Queries) ListIssueSequencingBlockersWithStatus(ctx context.Context, issueID string) ([]ListIssueSequencingBlockersWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listIssueSequencingBlockersWithStatus, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueSequencingBlockersWithStatusRow
	for rows.Next() {
		var i ListIssueSequencingBlockersWithStatusRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesBlockedBy = `-- name: ListIssuesBlockedBy :many
SELECT issue_id FROM zdx_issue_blocks WHERE blocked_by_id = $1
`

func (q *Queries) ListIssuesBlockedBy(ctx context.Context, blockedByID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listIssuesBlockedBy, blockedByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var issue_id string
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllIssueBlocks = `-- name: RemoveAllIssueBlocks :exec
DELETE FROM zdx_issue_blocks WHERE issue_id = $1
`

func (q *Queries) RemoveAllIssueBlocks(ctx context.Context, issueID string) error {
	_, err := q.db.Exec(ctx, removeAllIssueBlocks, issueID)
	return err
}

const removeIssueBlock = `-- name: RemoveIssueBlock :exec
DELETE FROM zdx_issue_blocks WHERE issue_id = $1 AND blocked_by_id = $2
`

type RemoveIssueBlockParams struct {
	IssueID     string `db:"issue_id" json:"issue_id"`
	BlockedByID string `db:"blocked_by_id" json:"blocked_by_id"`
}

func (q *Queries) RemoveIssueBlock(ctx context.Context, arg RemoveIssueBlockParams) error {
	_, err := q.db.Exec(ctx, removeIssueBlock, arg.IssueID, arg.BlockedByID)
	return err
}
