// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendIssueWork = `-- name: AppendIssueWork :exec
INSERT INTO zdx_issue_work (issue_id, agent, note) VALUES ($1, $2, $3)
`

type AppendIssueWorkParams struct {
	IssueID string `db:"issue_id" json:"issue_id"`
	Agent   string `db:"agent" json:"agent"`
	Note    string `db:"note" json:"note"`
}

func (q *Queries) AppendIssueWork(ctx context.Context, arg AppendIssueWorkParams) error {
	_, err := q.db.Exec(ctx, appendIssueWork, arg.IssueID, arg.Agent, arg.Note)
	return err
}

const closeIssue = `-- name: CloseIssue :exec
UPDATE zdx_issues SET status = 'closed', duplicate_of = $1, link_of = $2, closed_at = NOW(), updated_at = NOW() WHERE project_id = $3 AND id = $4
`

type CloseIssueParams struct {
	DuplicateOf string `db:"duplicate_of" json:"duplicate_of"`
	LinkOf      string `db:"link_of" json:"link_of"`
	ProjectID   int32  `db:"project_id" json:"project_id"`
	ID          string `db:"id" json:"id"`
}

func (q *Queries) CloseIssue(ctx context.Context, arg CloseIssueParams) error {
	_, err := q.db.Exec(ctx, closeIssue,
		arg.DuplicateOf,
		arg.LinkOf,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO zdx_issues (id, project_id, title, context, priority, component, issue_type, status, url, source_error_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
`

type CreateIssueParams struct {
	ID            string      `db:"id" json:"id"`
	ProjectID     int32       `db:"project_id" json:"project_id"`
	Title         string      `db:"title" json:"title"`
	Context       string      `db:"context" json:"context"`
	Priority      string      `db:"priority" json:"priority"`
	Component     string      `db:"component" json:"component"`
	IssueType     string      `db:"issue_type" json:"issue_type"`
	Status        string      `db:"status" json:"status"`
	Url           string      `db:"url" json:"url"`
	SourceErrorID pgtype.Int8 `db:"source_error_id" json:"source_error_id"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (ZdxIssue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Context,
		arg.Priority,
		arg.Component,
		arg.IssueType,
		arg.Status,
		arg.Url,
		arg.SourceErrorID,
	)
	var i ZdxIssue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Component,
		&i.Context,
		&i.CreatedAt,
		&i.IssueType,
		&i.DuplicateOf,
		&i.Url,
		&i.UpdatedAt,
		&i.SourceErrorID,
		&i.LinkOf,
		&i.ReopenCount,
		&i.ClosedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues WHERE project_id = $1 AND id = $2
`

type GetIssueParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (ZdxIssue, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ProjectID, arg.ID)
	var i ZdxIssue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Component,
		&i.Context,
		&i.CreatedAt,
		&i.IssueType,
		&i.DuplicateOf,
		&i.Url,
		&i.UpdatedAt,
		&i.SourceErrorID,
		&i.LinkOf,
		&i.ReopenCount,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueByAnyProject = `-- name: GetIssueByAnyProject :one
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues WHERE id = $1
`

func (q *Queries) GetIssueByAnyProject(ctx context.Context, id string) (ZdxIssue, error) {
	row := q.db.QueryRow(ctx, getIssueByAnyProject, id)
	var i ZdxIssue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Component,
		&i.Context,
		&i.CreatedAt,
		&i.IssueType,
		&i.DuplicateOf,
		&i.Url,
		&i.UpdatedAt,
		&i.SourceErrorID,
		&i.LinkOf,
		&i.ReopenCount,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueBySourceErrorID = `-- name: GetIssueBySourceErrorID :one
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues WHERE project_id = $1 AND source_error_id = $2
LIMIT 1
`

type GetIssueBySourceErrorIDParams struct {
	ProjectID     int32       `db:"project_id" json:"project_id"`
	SourceErrorID pgtype.Int8 `db:"source_error_id" json:"source_error_id"`
}

func (q *Queries) GetIssueBySourceErrorID(ctx context.Context, arg GetIssueBySourceErrorIDParams) (ZdxIssue, error) {
	row := q.db.QueryRow(ctx, getIssueBySourceErrorID, arg.ProjectID, arg.SourceErrorID)
	var i ZdxIssue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Status,
		&i.Priority,
		&i.Component,
		&i.Context,
		&i.CreatedAt,
		&i.IssueType,
		&i.DuplicateOf,
		&i.Url,
		&i.UpdatedAt,
		&i.SourceErrorID,
		&i.LinkOf,
		&i.ReopenCount,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueWork = `-- name: GetIssueWork :many
SELECT id, issue_id, agent, note, created_at FROM zdx_issue_work WHERE issue_id = $1 ORDER BY created_at
`

func (q *Queries) GetIssueWork(ctx context.Context, issueID string) ([]ZdxIssueWork, error) {
	rows, err := q.db.Query(ctx, getIssueWork, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssueWork
	for rows.Next() {
		var i ZdxIssueWork
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Agent,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues WHERE project_id = $1 ORDER BY updated_at DESC
`

func (q *Queries) ListIssues(ctx context.Context, projectID int32) ([]ZdxIssue, error) {
	rows, err := q.db.Query(ctx, listIssues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssue
	for rows.Next() {
		var i ZdxIssue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Component,
			&i.Context,
			&i.CreatedAt,
			&i.IssueType,
			&i.DuplicateOf,
			&i.Url,
			&i.UpdatedAt,
			&i.SourceErrorID,
			&i.LinkOf,
			&i.ReopenCount,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenIssues = `-- name: ListOpenIssues :many
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues WHERE project_id = $1 AND status = 'open' ORDER BY updated_at DESC
`

func (q *Queries) ListOpenIssues(ctx context.Context, projectID int32) ([]ZdxIssue, error) {
	rows, err := q.db.Query(ctx, listOpenIssues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssue
	for rows.Next() {
		var i ZdxIssue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Component,
			&i.Context,
			&i.CreatedAt,
			&i.IssueType,
			&i.DuplicateOf,
			&i.Url,
			&i.UpdatedAt,
			&i.SourceErrorID,
			&i.LinkOf,
			&i.ReopenCount,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenLinkedIssues = `-- name: ListOpenLinkedIssues :many
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues
WHERE project_id = $1
  AND status = 'open'
  AND (duplicate_of = $2 OR link_of = $2)
`

type ListOpenLinkedIssuesParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	TargetID  string `db:"target_id" json:"target_id"`
}

// Open issues whose duplicate_of or link_of targets the given issue. Used to
// cascade-close narrow-slice links (and full duplicates) when the target closes.
func (q *Queries) ListOpenLinkedIssues(ctx context.Context, arg ListOpenLinkedIssuesParams) ([]ZdxIssue, error) {
	rows, err := q.db.Query(ctx, listOpenLinkedIssues, arg.ProjectID, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssue
	for rows.Next() {
		var i ZdxIssue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Component,
			&i.Context,
			&i.CreatedAt,
			&i.IssueType,
			&i.DuplicateOf,
			&i.Url,
			&i.UpdatedAt,
			&i.SourceErrorID,
			&i.LinkOf,
			&i.ReopenCount,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorklogForProject = `-- name: ListWorklogForProject :many
SELECT w.id, w.issue_id, i.title AS issue_title, w.agent, w.note, w.created_at
FROM zdx_issue_work w
JOIN zdx_issues i ON i.id = w.issue_id
WHERE i.project_id = $1
ORDER BY w.created_at DESC
`

type ListWorklogForProjectRow struct {
	ID         int32              `db:"id" json:"id"`
	IssueID    string             `db:"issue_id" json:"issue_id"`
	IssueTitle string             `db:"issue_title" json:"issue_title"`
	Agent      string             `db:"agent" json:"agent"`
	Note       string             `db:"note" json:"note"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListWorklogForProject(ctx context.Context, projectID int32) ([]ListWorklogForProjectRow, error) {
	rows, err := q.db.Query(ctx, listWorklogForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorklogForProjectRow
	for rows.Next() {
		var i ListWorklogForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.IssueTitle,
			&i.Agent,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectStateSummary = `-- name: ProjectStateSummary :one
SELECT
  (SELECT count(*) FROM zdx_issues i WHERE i.project_id = $1 AND i.status = 'open') AS open_issues,
  (SELECT count(*) FROM zdx_issues i WHERE i.project_id = $1 AND i.status = 'wip') AS wip_issues,
  (SELECT count(*) FROM zdx_issues i WHERE i.project_id = $1 AND i.status = 'closed' AND i.created_at > NOW() - INTERVAL '30 days') AS recently_closed_issues,
  (SELECT count(*) FROM zdx_tasks t WHERE t.project_id = $1 AND t.status = 'ready') AS pending_tasks,
  (SELECT count(*) FROM zdx_tasks t WHERE t.project_id = $1 AND t.status = 'done') AS done_tasks,
  (SELECT count(*) FROM zdx_blocker_questions q WHERE q.project_id = $1 AND q.status = 'pending') AS pending_blockers
`

type ProjectStateSummaryRow struct {
	OpenIssues           int64 `db:"open_issues" json:"open_issues"`
	WipIssues            int64 `db:"wip_issues" json:"wip_issues"`
	RecentlyClosedIssues int64 `db:"recently_closed_issues" json:"recently_closed_issues"`
	PendingTasks         int64 `db:"pending_tasks" json:"pending_tasks"`
	DoneTasks            int64 `db:"done_tasks" json:"done_tasks"`
	PendingBlockers      int64 `db:"pending_blockers" json:"pending_blockers"`
}

func (q *Queries) ProjectStateSummary(ctx context.Context, projectID int32) (ProjectStateSummaryRow, error) {
	row := q.db.QueryRow(ctx, projectStateSummary, projectID)
	var i ProjectStateSummaryRow
	err := row.Scan(
		&i.OpenIssues,
		&i.WipIssues,
		&i.RecentlyClosedIssues,
		&i.PendingTasks,
		&i.DoneTasks,
		&i.PendingBlockers,
	)
	return i, err
}

const readyIssue = `-- name: ReadyIssue :exec
UPDATE zdx_issues SET status = 'open', closed_at = NULL, updated_at = NOW() WHERE project_id = $1 AND id = $2 AND status = 'wip'
`

type ReadyIssueParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) ReadyIssue(ctx context.Context, arg ReadyIssueParams) error {
	_, err := q.db.Exec(ctx, readyIssue, arg.ProjectID, arg.ID)
	return err
}

const reopenIssue = `-- name: ReopenIssue :exec
UPDATE zdx_issues
SET status = 'open',
    reopen_count = reopen_count + CASE WHEN status = 'closed' THEN 1 ELSE 0 END,
    closed_at = NULL,
    updated_at = NOW()
WHERE project_id = $1 AND id = $2
`

type ReopenIssueParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) ReopenIssue(ctx context.Context, arg ReopenIssueParams) error {
	_, err := q.db.Exec(ctx, reopenIssue, arg.ProjectID, arg.ID)
	return err
}

const searchIssues = `-- name: SearchIssues :many
SELECT id, project_id, title, status, priority, component, context, created_at, issue_type, duplicate_of, url, updated_at, source_error_id, link_of, reopen_count, closed_at
FROM zdx_issues
WHERE project_id = $1
  AND (title ILIKE '%' || $2::text || '%' OR context ILIKE '%' || $2::text || '%')
ORDER BY updated_at DESC
`

type SearchIssuesParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Query     string `db:"query" json:"query"`
}

func (q *Queries) SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]ZdxIssue, error) {
	rows, err := q.db.Query(ctx, searchIssues, arg.ProjectID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxIssue
	for rows.Next() {
		var i ZdxIssue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.Component,
			&i.Context,
			&i.CreatedAt,
			&i.IssueType,
			&i.DuplicateOf,
			&i.Url,
			&i.UpdatedAt,
			&i.SourceErrorID,
			&i.LinkOf,
			&i.ReopenCount,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setIssueField = `-- name: SetIssueField :exec
UPDATE zdx_issues
SET title      = CASE WHEN $1::text = 'title'      THEN $2::text ELSE title      END,
    context    = CASE WHEN $1::text = 'context'    THEN $2::text ELSE context    END,
    component  = CASE WHEN $1::text = 'component'  THEN $2::text ELSE component  END,
    issue_type = CASE WHEN $1::text = 'issue_type' THEN $2::text ELSE issue_type END,
    url        = CASE WHEN $1::text = 'url'        THEN $2::text ELSE url        END,
    updated_at = NOW()
WHERE project_id = $3 AND id = $4
`

type SetIssueFieldParams struct {
	Field     string `db:"field" json:"field"`
	Value     string `db:"value" json:"value"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) SetIssueField(ctx context.Context, arg SetIssueFieldParams) error {
	_, err := q.db.Exec(ctx, setIssueField,
		arg.Field,
		arg.Value,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const setIssuePriority = `-- name: SetIssuePriority :exec
UPDATE zdx_issues SET priority = $1, updated_at = NOW() WHERE project_id = $2 AND id = $3
`

type SetIssuePriorityParams struct {
	Priority  string `db:"priority" json:"priority"`
	ProjectID int32  `db:"project_id" json:"project_id"`
	ID        string `db:"id" json:"id"`
}

func (q *Queries) SetIssuePriority(ctx context.Context, arg SetIssuePriorityParams) error {
	_, err := q.db.Exec(ctx, setIssuePriority, arg.Priority, arg.ProjectID, arg.ID)
	return err
}

const topPriorityOpenIssues = `-- name: TopPriorityOpenIssues :many
SELECT id, title, priority
FROM zdx_issues
WHERE project_id = $1 AND status = 'open' AND priority != ''
ORDER BY priority, created_at
LIMIT 5
`

type TopPriorityOpenIssuesRow struct {
	ID       string `db:"id" json:"id"`
	Title    string `db:"title" json:"title"`
	Priority string `db:"priority" json:"priority"`
}

// metaquery: off
func (q *Queries) TopPriorityOpenIssues(ctx context.Context, projectID int32) ([]TopPriorityOpenIssuesRow, error) {
	rows, err := q.db.Query(ctx, topPriorityOpenIssues, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPriorityOpenIssuesRow
	for rows.Next() {
		var i TopPriorityOpenIssuesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Priority); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssue = `-- name: UpdateIssue :exec
UPDATE zdx_issues
SET title      = COALESCE(NULLIF($1, ''),      title),
    context    = COALESCE(NULLIF($2, ''),    context),
    priority   = COALESCE(NULLIF($3, ''),   priority),
    issue_type = COALESCE(NULLIF($4, ''), issue_type),
    updated_at = NOW()
WHERE project_id = $5 AND id = $6
`

type UpdateIssueParams struct {
	Title     interface{} `db:"title" json:"title"`
	Context   interface{} `db:"context" json:"context"`
	Priority  interface{} `db:"priority" json:"priority"`
	IssueType interface{} `db:"issue_type" json:"issue_type"`
	ProjectID int32       `db:"project_id" json:"project_id"`
	ID        string      `db:"id" json:"id"`
}

func (q *Queries) UpdateIssue(ctx context.Context, arg UpdateIssueParams) error {
	_, err := q.db.Exec(ctx, updateIssue,
		arg.Title,
		arg.Context,
		arg.Priority,
		arg.IssueType,
		arg.ProjectID,
		arg.ID,
	)
	return err
}
