// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCreateLLMConfig = metaquery.Query{
	Name:   "CreateLLMConfig",
	Cmd:    ":one",
	Source: "llm.sql",
	SQL: `INSERT INTO zdx_llm_configs (
    name, priority, type, url, embedding_model, api_key,
    agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, name, priority, type, url, embedding_model, api_key,
          agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "type", OriginalName: "type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "embedding_model", OriginalName: "embedding_model", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "api_key", OriginalName: "api_key", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "agent_type", OriginalName: "agent_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "model_low", OriginalName: "model_low", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_medium", OriginalName: "model_medium", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_high", OriginalName: "model_high", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_xhigh", OriginalName: "model_xhigh", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_max", OriginalName: "model_max", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "timeout_seconds", OriginalName: "timeout_seconds", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_llm_configs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 3, Name: "type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "url", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "embedding_model", GoType: "pgtype.Text", DBType: "text"},
		{Position: 6, Name: "api_key", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "agent_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 8, Name: "model_low", GoType: "pgtype.Text", DBType: "text"},
		{Position: 9, Name: "model_medium", GoType: "pgtype.Text", DBType: "text"},
		{Position: 10, Name: "model_high", GoType: "pgtype.Text", DBType: "text"},
		{Position: 11, Name: "model_xhigh", GoType: "pgtype.Text", DBType: "text"},
		{Position: 12, Name: "model_max", GoType: "pgtype.Text", DBType: "text"},
		{Position: 13, Name: "timeout_seconds", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_llm_configs"},
}

// WrapCreateLLMConfig returns a metaquery.Builder over MetaCreateLLMConfig, pre-bound with typed arguments.
func WrapCreateLLMConfig(arg CreateLLMConfigParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCreateLLMConfig, arg.Name, arg.Priority, arg.Type, arg.Url, arg.EmbeddingModel, arg.ApiKey, arg.AgentType, arg.ModelLow, arg.ModelMedium, arg.ModelHigh, arg.ModelXhigh, arg.ModelMax, arg.TimeoutSeconds)
}

// CreateLLMConfigCols gives typed, name-safe access to CreateLLMConfig's output columns.
var CreateLLMConfigCols = struct {
	ID             metaquery.IntCol
	Name           metaquery.TextCol
	Priority       metaquery.IntCol
	Type           metaquery.TextCol
	Url            metaquery.TextCol
	EmbeddingModel metaquery.TextCol
	ApiKey         metaquery.TextCol
	AgentType      metaquery.TextCol
	ModelLow       metaquery.TextCol
	ModelMedium    metaquery.TextCol
	ModelHigh      metaquery.TextCol
	ModelXhigh     metaquery.TextCol
	ModelMax       metaquery.TextCol
	TimeoutSeconds metaquery.IntCol
	CreatedAt      metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	Name:           metaquery.NewTextCol("name"),
	Priority:       metaquery.NewIntCol("priority"),
	Type:           metaquery.NewTextCol("type"),
	Url:            metaquery.NewTextCol("url"),
	EmbeddingModel: metaquery.NewTextCol("embedding_model"),
	ApiKey:         metaquery.NewTextCol("api_key"),
	AgentType:      metaquery.NewTextCol("agent_type"),
	ModelLow:       metaquery.NewTextCol("model_low"),
	ModelMedium:    metaquery.NewTextCol("model_medium"),
	ModelHigh:      metaquery.NewTextCol("model_high"),
	ModelXhigh:     metaquery.NewTextCol("model_xhigh"),
	ModelMax:       metaquery.NewTextCol("model_max"),
	TimeoutSeconds: metaquery.NewIntCol("timeout_seconds"),
	CreatedAt:      metaquery.NewTimeCol("created_at"),
}

var MetaDeleteLLMConfig = metaquery.Query{
	Name:   "DeleteLLMConfig",
	Cmd:    ":exec",
	Source: "llm.sql",
	SQL:    `DELETE FROM zdx_llm_configs WHERE id = $1`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapDeleteLLMConfig returns a metaquery.Builder over MetaDeleteLLMConfig, pre-bound with typed arguments.
func WrapDeleteLLMConfig(id int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteLLMConfig, id)
}

var MetaGetLLMConfigByID = metaquery.Query{
	Name:   "GetLLMConfigByID",
	Cmd:    ":one",
	Source: "llm.sql",
	SQL: `SELECT id, name, priority, type, url, embedding_model, api_key,
       agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds, created_at
FROM zdx_llm_configs
WHERE id = $1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "type", OriginalName: "type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "embedding_model", OriginalName: "embedding_model", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "api_key", OriginalName: "api_key", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "agent_type", OriginalName: "agent_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "model_low", OriginalName: "model_low", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_medium", OriginalName: "model_medium", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_high", OriginalName: "model_high", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_xhigh", OriginalName: "model_xhigh", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_max", OriginalName: "model_max", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "timeout_seconds", OriginalName: "timeout_seconds", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_llm_configs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapGetLLMConfigByID returns a metaquery.Builder over MetaGetLLMConfigByID, pre-bound with typed arguments.
func WrapGetLLMConfigByID(id int64) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetLLMConfigByID, id)
}

// GetLLMConfigByIDCols gives typed, name-safe access to GetLLMConfigByID's output columns.
var GetLLMConfigByIDCols = struct {
	ID             metaquery.IntCol
	Name           metaquery.TextCol
	Priority       metaquery.IntCol
	Type           metaquery.TextCol
	Url            metaquery.TextCol
	EmbeddingModel metaquery.TextCol
	ApiKey         metaquery.TextCol
	AgentType      metaquery.TextCol
	ModelLow       metaquery.TextCol
	ModelMedium    metaquery.TextCol
	ModelHigh      metaquery.TextCol
	ModelXhigh     metaquery.TextCol
	ModelMax       metaquery.TextCol
	TimeoutSeconds metaquery.IntCol
	CreatedAt      metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	Name:           metaquery.NewTextCol("name"),
	Priority:       metaquery.NewIntCol("priority"),
	Type:           metaquery.NewTextCol("type"),
	Url:            metaquery.NewTextCol("url"),
	EmbeddingModel: metaquery.NewTextCol("embedding_model"),
	ApiKey:         metaquery.NewTextCol("api_key"),
	AgentType:      metaquery.NewTextCol("agent_type"),
	ModelLow:       metaquery.NewTextCol("model_low"),
	ModelMedium:    metaquery.NewTextCol("model_medium"),
	ModelHigh:      metaquery.NewTextCol("model_high"),
	ModelXhigh:     metaquery.NewTextCol("model_xhigh"),
	ModelMax:       metaquery.NewTextCol("model_max"),
	TimeoutSeconds: metaquery.NewIntCol("timeout_seconds"),
	CreatedAt:      metaquery.NewTimeCol("created_at"),
}

var MetaGetPrimaryLLMConfigWithEmbedding = metaquery.Query{
	Name:   "GetPrimaryLLMConfigWithEmbedding",
	Cmd:    ":one",
	Source: "llm.sql",
	SQL: `SELECT id, name, priority, type, url, embedding_model, api_key,
       agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds, created_at
FROM zdx_llm_configs
WHERE agent_type <> 'claude'
  AND embedding_model IS NOT NULL
  AND embedding_model <> ''
ORDER BY priority ASC, id ASC
LIMIT 1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "type", OriginalName: "type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "embedding_model", OriginalName: "embedding_model", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "api_key", OriginalName: "api_key", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "agent_type", OriginalName: "agent_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "model_low", OriginalName: "model_low", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_medium", OriginalName: "model_medium", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_high", OriginalName: "model_high", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_xhigh", OriginalName: "model_xhigh", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_max", OriginalName: "model_max", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "timeout_seconds", OriginalName: "timeout_seconds", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_llm_configs"},
	},
}

// WrapGetPrimaryLLMConfigWithEmbedding returns a metaquery.Builder over MetaGetPrimaryLLMConfigWithEmbedding, pre-bound with typed arguments.
func WrapGetPrimaryLLMConfigWithEmbedding() *metaquery.Builder {
	return metaquery.Wrap(&MetaGetPrimaryLLMConfigWithEmbedding)
}

// GetPrimaryLLMConfigWithEmbeddingCols gives typed, name-safe access to GetPrimaryLLMConfigWithEmbedding's output columns.
var GetPrimaryLLMConfigWithEmbeddingCols = struct {
	ID             metaquery.IntCol
	Name           metaquery.TextCol
	Priority       metaquery.IntCol
	Type           metaquery.TextCol
	Url            metaquery.TextCol
	EmbeddingModel metaquery.TextCol
	ApiKey         metaquery.TextCol
	AgentType      metaquery.TextCol
	ModelLow       metaquery.TextCol
	ModelMedium    metaquery.TextCol
	ModelHigh      metaquery.TextCol
	ModelXhigh     metaquery.TextCol
	ModelMax       metaquery.TextCol
	TimeoutSeconds metaquery.IntCol
	CreatedAt      metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	Name:           metaquery.NewTextCol("name"),
	Priority:       metaquery.NewIntCol("priority"),
	Type:           metaquery.NewTextCol("type"),
	Url:            metaquery.NewTextCol("url"),
	EmbeddingModel: metaquery.NewTextCol("embedding_model"),
	ApiKey:         metaquery.NewTextCol("api_key"),
	AgentType:      metaquery.NewTextCol("agent_type"),
	ModelLow:       metaquery.NewTextCol("model_low"),
	ModelMedium:    metaquery.NewTextCol("model_medium"),
	ModelHigh:      metaquery.NewTextCol("model_high"),
	ModelXhigh:     metaquery.NewTextCol("model_xhigh"),
	ModelMax:       metaquery.NewTextCol("model_max"),
	TimeoutSeconds: metaquery.NewIntCol("timeout_seconds"),
	CreatedAt:      metaquery.NewTimeCol("created_at"),
}

var MetaListLLMConfigs = metaquery.Query{
	Name:   "ListLLMConfigs",
	Cmd:    ":many",
	Source: "llm.sql",
	SQL: `SELECT id, name, priority, type, url, embedding_model, api_key,
       agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds, created_at
FROM zdx_llm_configs
ORDER BY priority ASC, id ASC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "type", OriginalName: "type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "embedding_model", OriginalName: "embedding_model", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "api_key", OriginalName: "api_key", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "agent_type", OriginalName: "agent_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "model_low", OriginalName: "model_low", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_medium", OriginalName: "model_medium", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_high", OriginalName: "model_high", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_xhigh", OriginalName: "model_xhigh", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_max", OriginalName: "model_max", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "timeout_seconds", OriginalName: "timeout_seconds", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_llm_configs"},
	},
}

// WrapListLLMConfigs returns a metaquery.Builder over MetaListLLMConfigs, pre-bound with typed arguments.
func WrapListLLMConfigs() *metaquery.Builder {
	return metaquery.Wrap(&MetaListLLMConfigs)
}

// ListLLMConfigsCols gives typed, name-safe access to ListLLMConfigs's output columns.
var ListLLMConfigsCols = struct {
	ID             metaquery.IntCol
	Name           metaquery.TextCol
	Priority       metaquery.IntCol
	Type           metaquery.TextCol
	Url            metaquery.TextCol
	EmbeddingModel metaquery.TextCol
	ApiKey         metaquery.TextCol
	AgentType      metaquery.TextCol
	ModelLow       metaquery.TextCol
	ModelMedium    metaquery.TextCol
	ModelHigh      metaquery.TextCol
	ModelXhigh     metaquery.TextCol
	ModelMax       metaquery.TextCol
	TimeoutSeconds metaquery.IntCol
	CreatedAt      metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	Name:           metaquery.NewTextCol("name"),
	Priority:       metaquery.NewIntCol("priority"),
	Type:           metaquery.NewTextCol("type"),
	Url:            metaquery.NewTextCol("url"),
	EmbeddingModel: metaquery.NewTextCol("embedding_model"),
	ApiKey:         metaquery.NewTextCol("api_key"),
	AgentType:      metaquery.NewTextCol("agent_type"),
	ModelLow:       metaquery.NewTextCol("model_low"),
	ModelMedium:    metaquery.NewTextCol("model_medium"),
	ModelHigh:      metaquery.NewTextCol("model_high"),
	ModelXhigh:     metaquery.NewTextCol("model_xhigh"),
	ModelMax:       metaquery.NewTextCol("model_max"),
	TimeoutSeconds: metaquery.NewIntCol("timeout_seconds"),
	CreatedAt:      metaquery.NewTimeCol("created_at"),
}

var MetaNextLLMConfigPriority = metaquery.Query{
	Name:   "NextLLMConfigPriority",
	Cmd:    ":one",
	Source: "llm.sql",
	SQL:    `SELECT COALESCE(MAX(priority), 0) + 1 AS next_priority FROM zdx_llm_configs`,
	Columns: []metaquery.Column{
		{Name: "next_priority", OriginalName: "next_priority", GoType: "int32"},
	},
}

// WrapNextLLMConfigPriority returns a metaquery.Builder over MetaNextLLMConfigPriority, pre-bound with typed arguments.
func WrapNextLLMConfigPriority() *metaquery.Builder {
	return metaquery.Wrap(&MetaNextLLMConfigPriority)
}

// NextLLMConfigPriorityCols gives typed, name-safe access to NextLLMConfigPriority's output columns.
var NextLLMConfigPriorityCols = struct {
	NextPriority metaquery.IntCol
}{
	NextPriority: metaquery.NewIntCol("next_priority"),
}

var MetaUpdateLLMConfig = metaquery.Query{
	Name:   "UpdateLLMConfig",
	Cmd:    ":one",
	Source: "llm.sql",
	SQL: `UPDATE zdx_llm_configs
SET name            = $1,
    type            = $2,
    url             = $3,
    embedding_model = $4,
    api_key         = $5,
    agent_type      = $6,
    model_low       = $7,
    model_medium    = $8,
    model_high      = $9,
    model_xhigh     = $10,
    model_max       = $11,
    timeout_seconds = $12
WHERE id = $13
RETURNING id, name, priority, type, url, embedding_model, api_key,
          agent_type, model_low, model_medium, model_high, model_xhigh, model_max, timeout_seconds, created_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "name", OriginalName: "name", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "priority", OriginalName: "priority", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "type", OriginalName: "type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "url", OriginalName: "url", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "embedding_model", OriginalName: "embedding_model", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "api_key", OriginalName: "api_key", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "agent_type", OriginalName: "agent_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "model_low", OriginalName: "model_low", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_medium", OriginalName: "model_medium", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_high", OriginalName: "model_high", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_xhigh", OriginalName: "model_xhigh", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "model_max", OriginalName: "model_max", GoType: "pgtype.Text", DBType: "text", Table: "zdx_llm_configs"},
		{Name: "timeout_seconds", OriginalName: "timeout_seconds", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_llm_configs"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_llm_configs"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "name", GoType: "string", DBType: "text", NotNull: true},
		{Position: 2, Name: "type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "url", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "embedding_model", GoType: "pgtype.Text", DBType: "text"},
		{Position: 5, Name: "api_key", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "agent_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "model_low", GoType: "pgtype.Text", DBType: "text"},
		{Position: 8, Name: "model_medium", GoType: "pgtype.Text", DBType: "text"},
		{Position: 9, Name: "model_high", GoType: "pgtype.Text", DBType: "text"},
		{Position: 10, Name: "model_xhigh", GoType: "pgtype.Text", DBType: "text"},
		{Position: 11, Name: "model_max", GoType: "pgtype.Text", DBType: "text"},
		{Position: 12, Name: "timeout_seconds", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 13, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapUpdateLLMConfig returns a metaquery.Builder over MetaUpdateLLMConfig, pre-bound with typed arguments.
func WrapUpdateLLMConfig(arg UpdateLLMConfigParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateLLMConfig, arg.Name, arg.Type, arg.Url, arg.EmbeddingModel, arg.ApiKey, arg.AgentType, arg.ModelLow, arg.ModelMedium, arg.ModelHigh, arg.ModelXhigh, arg.ModelMax, arg.TimeoutSeconds, arg.ID)
}

// UpdateLLMConfigCols gives typed, name-safe access to UpdateLLMConfig's output columns.
var UpdateLLMConfigCols = struct {
	ID             metaquery.IntCol
	Name           metaquery.TextCol
	Priority       metaquery.IntCol
	Type           metaquery.TextCol
	Url            metaquery.TextCol
	EmbeddingModel metaquery.TextCol
	ApiKey         metaquery.TextCol
	AgentType      metaquery.TextCol
	ModelLow       metaquery.TextCol
	ModelMedium    metaquery.TextCol
	ModelHigh      metaquery.TextCol
	ModelXhigh     metaquery.TextCol
	ModelMax       metaquery.TextCol
	TimeoutSeconds metaquery.IntCol
	CreatedAt      metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	Name:           metaquery.NewTextCol("name"),
	Priority:       metaquery.NewIntCol("priority"),
	Type:           metaquery.NewTextCol("type"),
	Url:            metaquery.NewTextCol("url"),
	EmbeddingModel: metaquery.NewTextCol("embedding_model"),
	ApiKey:         metaquery.NewTextCol("api_key"),
	AgentType:      metaquery.NewTextCol("agent_type"),
	ModelLow:       metaquery.NewTextCol("model_low"),
	ModelMedium:    metaquery.NewTextCol("model_medium"),
	ModelHigh:      metaquery.NewTextCol("model_high"),
	ModelXhigh:     metaquery.NewTextCol("model_xhigh"),
	ModelMax:       metaquery.NewTextCol("model_max"),
	TimeoutSeconds: metaquery.NewIntCol("timeout_seconds"),
	CreatedAt:      metaquery.NewTimeCol("created_at"),
}

var MetaUpdateLLMConfigPriority = metaquery.Query{
	Name:   "UpdateLLMConfigPriority",
	Cmd:    ":exec",
	Source: "llm.sql",
	SQL:    `UPDATE zdx_llm_configs SET priority = $1 WHERE id = $2`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "priority", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "id", GoType: "int64", DBType: "pg_catalog.int8", NotNull: true},
	},
}

// WrapUpdateLLMConfigPriority returns a metaquery.Builder over MetaUpdateLLMConfigPriority, pre-bound with typed arguments.
func WrapUpdateLLMConfigPriority(arg UpdateLLMConfigPriorityParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaUpdateLLMConfigPriority, arg.Priority, arg.ID)
}
