// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_events.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
	"github.com/jackc/pgx/v5/pgtype"
)

var _ = metaquery.Query{}

var MetaDeleteLogEventsOlderThan = metaquery.Query{
	Name:   "DeleteLogEventsOlderThan",
	Cmd:    ":execrows",
	Source: "log_events.sql",
	SQL: `DELETE FROM zdx_log_events
WHERE created_at < $1::timestamptz`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "cutoff", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true},
	},
}

// WrapDeleteLogEventsOlderThan returns a metaquery.Builder over MetaDeleteLogEventsOlderThan, pre-bound with typed arguments.
func WrapDeleteLogEventsOlderThan(cutoff pgtype.Timestamptz) *metaquery.Builder {
	return metaquery.Wrap(&MetaDeleteLogEventsOlderThan, cutoff)
}

var MetaInsertLogEvent = metaquery.Query{
	Name:   "InsertLogEvent",
	Cmd:    ":exec",
	Source: "log_events.sql",
	SQL: `INSERT INTO zdx_log_events (project_id, component, environment, level, message, source, context_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "pg_catalog.int4"},
		{Position: 2, Name: "component", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "environment", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "level", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "message", GoType: "string", DBType: "text", NotNull: true},
		{Position: 6, Name: "source", GoType: "string", DBType: "text", NotNull: true},
		{Position: 7, Name: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true},
	},
	Table: &metaquery.Table{Name: "zdx_log_events"},
}

// WrapInsertLogEvent returns a metaquery.Builder over MetaInsertLogEvent, pre-bound with typed arguments.
func WrapInsertLogEvent(arg InsertLogEventParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaInsertLogEvent, arg.ProjectID, arg.Component, arg.Environment, arg.Level, arg.Message, arg.Source, arg.ContextJson)
}

var MetaListLogEvents = metaquery.Query{
	Name:   "ListLogEvents",
	Cmd:    ":many",
	Source: "log_events.sql",
	SQL: `SELECT id, project_id, component, environment, level, message, source, context_json, created_at
FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_log_events"},
		{Name: "project_id", OriginalName: "project_id", GoType: "pgtype.Int4", DBType: "int4", Table: "zdx_log_events"},
		{Name: "component", OriginalName: "component", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_log_events"},
		{Name: "environment", OriginalName: "environment", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_log_events"},
		{Name: "level", OriginalName: "level", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_log_events"},
		{Name: "message", OriginalName: "message", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_log_events"},
		{Name: "source", OriginalName: "source", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_log_events"},
		{Name: "context_json", OriginalName: "context_json", GoType: "[]byte", DBType: "jsonb", NotNull: true, Table: "zdx_log_events"},
		{Name: "created_at", OriginalName: "created_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_log_events"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
		{Position: 2, Name: "tag_filter", GoType: "[]byte", DBType: "jsonb"},
		{Position: 3, Name: "since", GoType: "pgtype.Timestamptz", DBType: "timestamptz"},
		{Position: 4, Name: "until", GoType: "pgtype.Timestamptz", DBType: "timestamptz"},
	},
}

// WrapListLogEvents returns a metaquery.Builder over MetaListLogEvents, pre-bound with typed arguments.
func WrapListLogEvents(arg ListLogEventsParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListLogEvents, arg.ProjectID, arg.TagFilter, arg.Since, arg.Until)
}

// ListLogEventsCols gives typed, name-safe access to ListLogEvents's output columns.
var ListLogEventsCols = struct {
	ID          metaquery.IntCol
	ProjectID   metaquery.IntCol
	Component   metaquery.TextCol
	Environment metaquery.TextCol
	Level       metaquery.TextCol
	Message     metaquery.TextCol
	Source      metaquery.TextCol
	ContextJson metaquery.BytesCol
	CreatedAt   metaquery.TimeCol
}{
	ID:          metaquery.NewIntCol("id"),
	ProjectID:   metaquery.NewIntCol("project_id"),
	Component:   metaquery.NewTextCol("component"),
	Environment: metaquery.NewTextCol("environment"),
	Level:       metaquery.NewTextCol("level"),
	Message:     metaquery.NewTextCol("message"),
	Source:      metaquery.NewTextCol("source"),
	ContextJson: metaquery.NewBytesCol("context_json"),
	CreatedAt:   metaquery.NewTimeCol("created_at"),
}

var MetaListLogEventsDistinctTagKeys = metaquery.Query{
	Name:   "ListLogEventsDistinctTagKeys",
	Cmd:    ":many",
	Source: "log_events.sql",
	SQL: `SELECT DISTINCT k AS tag_key
FROM zdx_log_events, jsonb_object_keys(context_json) AS k
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY tag_key`,
	Columns: []metaquery.Column{
		{Name: "tag_key", OriginalName: "tag_key", GoType: "pgtype.Text"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
	},
}

// WrapListLogEventsDistinctTagKeys returns a metaquery.Builder over MetaListLogEventsDistinctTagKeys, pre-bound with typed arguments.
func WrapListLogEventsDistinctTagKeys(projectID pgtype.Int4) *metaquery.Builder {
	return metaquery.Wrap(&MetaListLogEventsDistinctTagKeys, projectID)
}

// ListLogEventsDistinctTagKeysCols gives typed, name-safe access to ListLogEventsDistinctTagKeys's output columns.
var ListLogEventsDistinctTagKeysCols = struct {
	TagKey metaquery.TextCol
}{
	TagKey: metaquery.NewTextCol("tag_key"),
}

var MetaListLogEventsDistinctTagValues = metaquery.Query{
	Name:   "ListLogEventsDistinctTagValues",
	Cmd:    ":many",
	Source: "log_events.sql",
	SQL: `SELECT DISTINCT context_json->>@tag_key::text AS tag_value
FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND context_json ? $2::text
  AND context_json->>@tag_key::text IS NOT NULL
ORDER BY tag_value`,
	Columns: []metaquery.Column{
		{Name: "tag_value", OriginalName: "tag_value", GoType: "interface{}"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "pgtype.Int4", DBType: "int4"},
		{Position: 2, Name: "tag_key", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListLogEventsDistinctTagValues returns a metaquery.Builder over MetaListLogEventsDistinctTagValues, pre-bound with typed arguments.
func WrapListLogEventsDistinctTagValues(arg ListLogEventsDistinctTagValuesParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListLogEventsDistinctTagValues, arg.ProjectID, arg.TagKey)
}

// ListLogEventsDistinctTagValuesCols gives typed, name-safe access to ListLogEventsDistinctTagValues's output columns.
var ListLogEventsDistinctTagValuesCols = struct {
	TagValue metaquery.AnyCol
}{
	TagValue: metaquery.NewAnyCol("tag_value"),
}
