// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLogEvents = `-- name: CountLogEvents :one
SELECT count(*) FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
`

type CountLogEventsParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
}

func (q *Queries) CountLogEvents(ctx context.Context, arg CountLogEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLogEvents,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLogEventsOlderThan = `-- name: DeleteLogEventsOlderThan :execrows
DELETE FROM zdx_log_events
WHERE created_at < $1::timestamptz
`

func (q *Queries) DeleteLogEventsOlderThan(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLogEventsOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertLogEvent = `-- name: InsertLogEvent :exec
INSERT INTO zdx_log_events (project_id, component, environment, level, message, source, context_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLogEventParams struct {
	ProjectID   pgtype.Int4 `db:"project_id" json:"project_id"`
	Component   string      `db:"component" json:"component"`
	Environment string      `db:"environment" json:"environment"`
	Level       string      `db:"level" json:"level"`
	Message     string      `db:"message" json:"message"`
	Source      string      `db:"source" json:"source"`
	ContextJson []byte      `db:"context_json" json:"context_json"`
}

func (q *Queries) InsertLogEvent(ctx context.Context, arg InsertLogEventParams) error {
	_, err := q.db.Exec(ctx, insertLogEvent,
		arg.ProjectID,
		arg.Component,
		arg.Environment,
		arg.Level,
		arg.Message,
		arg.Source,
		arg.ContextJson,
	)
	return err
}

const listLogEvents = `-- name: ListLogEvents :many
SELECT id, project_id, component, environment, level, message, source, context_json, created_at
FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type ListLogEventsParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
	Off       int32              `db:"off" json:"off"`
	Lim       int32              `db:"lim" json:"lim"`
}

func (q *Queries) ListLogEvents(ctx context.Context, arg ListLogEventsParams) ([]ZdxLogEvent, error) {
	rows, err := q.db.Query(ctx, listLogEvents,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxLogEvent
	for rows.Next() {
		var i ZdxLogEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Component,
			&i.Environment,
			&i.Level,
			&i.Message,
			&i.Source,
			&i.ContextJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEventsDistinctTagKeys = `-- name: ListLogEventsDistinctTagKeys :many
SELECT DISTINCT k AS tag_key
FROM zdx_log_events, jsonb_object_keys(context_json) AS k
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY tag_key
`

func (q *Queries) ListLogEventsDistinctTagKeys(ctx context.Context, projectID pgtype.Int4) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listLogEventsDistinctTagKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var tag_key pgtype.Text
		if err := rows.Scan(&tag_key); err != nil {
			return nil, err
		}
		items = append(items, tag_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEventsDistinctTagValues = `-- name: ListLogEventsDistinctTagValues :many
SELECT DISTINCT context_json->>@tag_key::text AS tag_value
FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND context_json ? $2::text
  AND context_json->>@tag_key::text IS NOT NULL
ORDER BY tag_value
`

type ListLogEventsDistinctTagValuesParams struct {
	ProjectID pgtype.Int4 `db:"project_id" json:"project_id"`
	TagKey    string      `db:"tag_key" json:"tag_key"`
}

func (q *Queries) ListLogEventsDistinctTagValues(ctx context.Context, arg ListLogEventsDistinctTagValuesParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, listLogEventsDistinctTagValues, arg.ProjectID, arg.TagKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var tag_value interface{}
		if err := rows.Scan(&tag_value); err != nil {
			return nil, err
		}
		items = append(items, tag_value)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEventsGrouped = `-- name: ListLogEventsGrouped :many
SELECT
  context_json->>@group_key::text AS group_value,
  count(*)::int AS entry_count,
  min(created_at) AS first_seen,
  max(created_at) AS last_seen
FROM zdx_log_events
WHERE ($1::int IS NULL OR project_id = $1)
  AND ($2::jsonb IS NULL OR context_json @> $2::jsonb)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
  AND context_json ? $5::text
GROUP BY group_value
ORDER BY entry_count DESC
`

type ListLogEventsGroupedParams struct {
	ProjectID pgtype.Int4        `db:"project_id" json:"project_id"`
	TagFilter []byte             `db:"tag_filter" json:"tag_filter"`
	Since     pgtype.Timestamptz `db:"since" json:"since"`
	Until     pgtype.Timestamptz `db:"until" json:"until"`
	GroupKey  string             `db:"group_key" json:"group_key"`
}

type ListLogEventsGroupedRow struct {
	GroupValue interface{} `db:"group_value" json:"group_value"`
	EntryCount int32       `db:"entry_count" json:"entry_count"`
	FirstSeen  interface{} `db:"first_seen" json:"first_seen"`
	LastSeen   interface{} `db:"last_seen" json:"last_seen"`
}

func (q *Queries) ListLogEventsGrouped(ctx context.Context, arg ListLogEventsGroupedParams) ([]ListLogEventsGroupedRow, error) {
	rows, err := q.db.Query(ctx, listLogEventsGrouped,
		arg.ProjectID,
		arg.TagFilter,
		arg.Since,
		arg.Until,
		arg.GroupKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventsGroupedRow
	for rows.Next() {
		var i ListLogEventsGroupedRow
		if err := rows.Scan(
			&i.GroupValue,
			&i.EntryCount,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
