// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePattern = `-- name: DeletePattern :exec
DELETE FROM zdx_patterns
WHERE project_id = $1 AND id = $2
`

type DeletePatternParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int32 `db:"id" json:"id"`
}

func (q *Queries) DeletePattern(ctx context.Context, arg DeletePatternParams) error {
	_, err := q.db.Exec(ctx, deletePattern, arg.ProjectID, arg.ID)
	return err
}

const getPattern = `-- name: GetPattern :one
SELECT id, project_id, name, description, code_refs, created_at, updated_at
FROM zdx_patterns
WHERE project_id = $1 AND id = $2
`

type GetPatternParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int32 `db:"id" json:"id"`
}

func (q *Queries) GetPattern(ctx context.Context, arg GetPatternParams) (ZdxPattern, error) {
	row := q.db.QueryRow(ctx, getPattern, arg.ProjectID, arg.ID)
	var i ZdxPattern
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CodeRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPattern = `-- name: InsertPattern :one
INSERT INTO zdx_patterns (project_id, name, description, code_refs)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, name, description, code_refs, created_at, updated_at
`

type InsertPatternParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	CodeRefs    []byte `db:"code_refs" json:"code_refs"`
}

func (q *Queries) InsertPattern(ctx context.Context, arg InsertPatternParams) (ZdxPattern, error) {
	row := q.db.QueryRow(ctx, insertPattern,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.CodeRefs,
	)
	var i ZdxPattern
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CodeRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPatterns = `-- name: ListPatterns :many
SELECT id, project_id, name, description, code_refs, created_at, updated_at
FROM zdx_patterns
WHERE project_id = $1
ORDER BY name
`

func (q *Queries) ListPatterns(ctx context.Context, projectID int32) ([]ZdxPattern, error) {
	rows, err := q.db.Query(ctx, listPatterns, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxPattern
	for rows.Next() {
		var i ZdxPattern
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CodeRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatterns = `-- name: SearchPatterns :many
SELECT id, project_id, name, description, code_refs, created_at, updated_at
FROM zdx_patterns
WHERE project_id = $1
  AND (name ILIKE '%' || $2 || '%' OR description ILIKE '%' || $2 || '%')
ORDER BY name
LIMIT $3
`

type SearchPatternsParams struct {
	ProjectID int32       `db:"project_id" json:"project_id"`
	Column2   pgtype.Text `db:"column_2" json:"column_2"`
	Limit     int32       `db:"limit" json:"limit"`
}

// metaquery: off
func (q *Queries) SearchPatterns(ctx context.Context, arg SearchPatternsParams) ([]ZdxPattern, error) {
	rows, err := q.db.Query(ctx, searchPatterns, arg.ProjectID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxPattern
	for rows.Next() {
		var i ZdxPattern
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.CodeRefs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePattern = `-- name: UpdatePattern :one
UPDATE zdx_patterns
SET name        = $3,
    description = $4,
    code_refs   = $5,
    updated_at  = NOW()
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, name, description, code_refs, created_at, updated_at
`

type UpdatePatternParams struct {
	ProjectID   int32  `db:"project_id" json:"project_id"`
	ID          int32  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	CodeRefs    []byte `db:"code_refs" json:"code_refs"`
}

func (q *Queries) UpdatePattern(ctx context.Context, arg UpdatePatternParams) (ZdxPattern, error) {
	row := q.db.QueryRow(ctx, updatePattern,
		arg.ProjectID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CodeRefs,
	)
	var i ZdxPattern
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.CodeRefs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
