// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO zdx_projects (slug, name) VALUES ($1, $2)
RETURNING id, slug, name, created_at
`

type CreateProjectParams struct {
	Slug string `db:"slug" json:"slug"`
	Name string `db:"name" json:"name"`
}

type CreateProjectRow struct {
	ID        int32              `db:"id" json:"id"`
	Slug      string             `db:"slug" json:"slug"`
	Name      string             `db:"name" json:"name"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Slug, arg.Name)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, slug, name, created_at, git_url, git_branch, git_token, stage, classification, upstream_url, upstream_credentials, git_enabled, title, description, priority FROM zdx_projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int32) (ZdxProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i ZdxProject
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.GitUrl,
		&i.GitBranch,
		&i.GitToken,
		&i.Stage,
		&i.Classification,
		&i.UpstreamUrl,
		&i.UpstreamCredentials,
		&i.GitEnabled,
		&i.Title,
		&i.Description,
		&i.Priority,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, slug, name, created_at, git_url, git_branch, git_token, stage, classification, upstream_url, upstream_credentials, git_enabled, title, description, priority FROM zdx_projects WHERE slug = $1
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (ZdxProject, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i ZdxProject
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.GitUrl,
		&i.GitBranch,
		&i.GitToken,
		&i.Stage,
		&i.Classification,
		&i.UpstreamUrl,
		&i.UpstreamCredentials,
		&i.GitEnabled,
		&i.Title,
		&i.Description,
		&i.Priority,
	)
	return i, err
}

const getProjectGitConfig = `-- name: GetProjectGitConfig :one
SELECT slug, git_url, git_branch, git_token FROM zdx_projects WHERE slug = $1
`

type GetProjectGitConfigRow struct {
	Slug      string `db:"slug" json:"slug"`
	GitUrl    string `db:"git_url" json:"git_url"`
	GitBranch string `db:"git_branch" json:"git_branch"`
	GitToken  string `db:"git_token" json:"git_token"`
}

func (q *Queries) GetProjectGitConfig(ctx context.Context, slug string) (GetProjectGitConfigRow, error) {
	row := q.db.QueryRow(ctx, getProjectGitConfig, slug)
	var i GetProjectGitConfigRow
	err := row.Scan(
		&i.Slug,
		&i.GitUrl,
		&i.GitBranch,
		&i.GitToken,
	)
	return i, err
}

const getProjectProxyConfig = `-- name: GetProjectProxyConfig :one
SELECT slug, upstream_url, upstream_credentials, git_enabled FROM zdx_projects WHERE slug = $1
`

type GetProjectProxyConfigRow struct {
	Slug                string `db:"slug" json:"slug"`
	UpstreamUrl         string `db:"upstream_url" json:"upstream_url"`
	UpstreamCredentials string `db:"upstream_credentials" json:"upstream_credentials"`
	GitEnabled          bool   `db:"git_enabled" json:"git_enabled"`
}

func (q *Queries) GetProjectProxyConfig(ctx context.Context, slug string) (GetProjectProxyConfigRow, error) {
	row := q.db.QueryRow(ctx, getProjectProxyConfig, slug)
	var i GetProjectProxyConfigRow
	err := row.Scan(
		&i.Slug,
		&i.UpstreamUrl,
		&i.UpstreamCredentials,
		&i.GitEnabled,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, slug, name, created_at, git_url, git_branch, git_token, stage, classification, upstream_url, upstream_credentials, git_enabled, title, description, priority FROM zdx_projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]ZdxProject, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxProject
	for rows.Next() {
		var i ZdxProject
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.GitUrl,
			&i.GitBranch,
			&i.GitToken,
			&i.Stage,
			&i.Classification,
			&i.UpstreamUrl,
			&i.UpstreamCredentials,
			&i.GitEnabled,
			&i.Title,
			&i.Description,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByPriority = `-- name: ListProjectsByPriority :many
SELECT id, slug, name, created_at, git_url, git_branch, git_token, stage, classification, upstream_url, upstream_credentials, git_enabled, title, description, priority FROM zdx_projects ORDER BY priority, name
`

// Used by the cross-project claim path so generateSoloQueue runs first
// against the highest-priority project and the persisted queue is
// freshest where it matters most. Tie-break by name for stable order.
func (q *Queries) ListProjectsByPriority(ctx context.Context) ([]ZdxProject, error) {
	rows, err := q.db.Query(ctx, listProjectsByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxProject
	for rows.Next() {
		var i ZdxProject
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.GitUrl,
			&i.GitBranch,
			&i.GitToken,
			&i.Stage,
			&i.Classification,
			&i.UpstreamUrl,
			&i.UpstreamCredentials,
			&i.GitEnabled,
			&i.Title,
			&i.Description,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextID = `-- name: NextID :one
INSERT INTO zdx_id_seq (kind, next_val) VALUES ($1, 2)
ON CONFLICT (kind) DO UPDATE SET next_val = zdx_id_seq.next_val + 1
RETURNING next_val - 1 AS val
`

func (q *Queries) NextID(ctx context.Context, kind string) (int32, error) {
	row := q.db.QueryRow(ctx, nextID, kind)
	var val int32
	err := row.Scan(&val)
	return val, err
}

const setProjectGitConfig = `-- name: SetProjectGitConfig :exec
UPDATE zdx_projects SET git_url = $1, git_branch = $2, git_token = $3 WHERE slug = $4
`

type SetProjectGitConfigParams struct {
	GitUrl    string `db:"git_url" json:"git_url"`
	GitBranch string `db:"git_branch" json:"git_branch"`
	GitToken  string `db:"git_token" json:"git_token"`
	Slug      string `db:"slug" json:"slug"`
}

func (q *Queries) SetProjectGitConfig(ctx context.Context, arg SetProjectGitConfigParams) error {
	_, err := q.db.Exec(ctx, setProjectGitConfig,
		arg.GitUrl,
		arg.GitBranch,
		arg.GitToken,
		arg.Slug,
	)
	return err
}

const setProjectPriority = `-- name: SetProjectPriority :exec
UPDATE zdx_projects SET priority = $1 WHERE slug = $2
`

type SetProjectPriorityParams struct {
	Priority int32  `db:"priority" json:"priority"`
	Slug     string `db:"slug" json:"slug"`
}

func (q *Queries) SetProjectPriority(ctx context.Context, arg SetProjectPriorityParams) error {
	_, err := q.db.Exec(ctx, setProjectPriority, arg.Priority, arg.Slug)
	return err
}

const setProjectProxyConfig = `-- name: SetProjectProxyConfig :exec
UPDATE zdx_projects SET upstream_url = $1, upstream_credentials = $2, git_enabled = $3 WHERE slug = $4
`

type SetProjectProxyConfigParams struct {
	UpstreamUrl         string `db:"upstream_url" json:"upstream_url"`
	UpstreamCredentials string `db:"upstream_credentials" json:"upstream_credentials"`
	GitEnabled          bool   `db:"git_enabled" json:"git_enabled"`
	Slug                string `db:"slug" json:"slug"`
}

func (q *Queries) SetProjectProxyConfig(ctx context.Context, arg SetProjectProxyConfigParams) error {
	_, err := q.db.Exec(ctx, setProjectProxyConfig,
		arg.UpstreamUrl,
		arg.UpstreamCredentials,
		arg.GitEnabled,
		arg.Slug,
	)
	return err
}

const setProjectStage = `-- name: SetProjectStage :exec
UPDATE zdx_projects SET stage = $1 WHERE slug = $2
`

type SetProjectStageParams struct {
	Stage string `db:"stage" json:"stage"`
	Slug  string `db:"slug" json:"slug"`
}

func (q *Queries) SetProjectStage(ctx context.Context, arg SetProjectStageParams) error {
	_, err := q.db.Exec(ctx, setProjectStage, arg.Stage, arg.Slug)
	return err
}

const setProjectVision = `-- name: SetProjectVision :exec
UPDATE zdx_projects SET title = $1, description = $2 WHERE slug = $3
`

type SetProjectVisionParams struct {
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Slug        string `db:"slug" json:"slug"`
}

func (q *Queries) SetProjectVision(ctx context.Context, arg SetProjectVisionParams) error {
	_, err := q.db.Exec(ctx, setProjectVision, arg.Title, arg.Description, arg.Slug)
	return err
}
