// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qa.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const answerQuestion = `-- name: AnswerQuestion :one
UPDATE zdx_questions
SET answer     = $3,
    updated_at = NOW()
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
`

type AnswerQuestionParams struct {
	ProjectID int32       `db:"project_id" json:"project_id"`
	ID        int32       `db:"id" json:"id"`
	Answer    pgtype.Text `db:"answer" json:"answer"`
}

func (q *Queries) AnswerQuestion(ctx context.Context, arg AnswerQuestionParams) (ZdxQuestion, error) {
	row := q.db.QueryRow(ctx, answerQuestion, arg.ProjectID, arg.ID, arg.Answer)
	var i ZdxQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentQuestionID,
		&i.OwnerUserID,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1 AND id = $2
`

type GetQuestionParams struct {
	ProjectID int32 `db:"project_id" json:"project_id"`
	ID        int32 `db:"id" json:"id"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (ZdxQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.ProjectID, arg.ID)
	var i ZdxQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentQuestionID,
		&i.OwnerUserID,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO zdx_questions (project_id, category, question, parent_question_id, owner_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
`

type InsertQuestionParams struct {
	ProjectID        int32       `db:"project_id" json:"project_id"`
	Category         string      `db:"category" json:"category"`
	Question         string      `db:"question" json:"question"`
	ParentQuestionID pgtype.Int4 `db:"parent_question_id" json:"parent_question_id"`
	OwnerUserID      pgtype.Int4 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (ZdxQuestion, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.ProjectID,
		arg.Category,
		arg.Question,
		arg.ParentQuestionID,
		arg.OwnerUserID,
	)
	var i ZdxQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentQuestionID,
		&i.OwnerUserID,
	)
	return i, err
}

const linkQuestionTask = `-- name: LinkQuestionTask :exec
INSERT INTO zdx_question_tasks (question_id, task_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkQuestionTaskParams struct {
	QuestionID int32  `db:"question_id" json:"question_id"`
	TaskID     string `db:"task_id" json:"task_id"`
}

func (q *Queries) LinkQuestionTask(ctx context.Context, arg LinkQuestionTaskParams) error {
	_, err := q.db.Exec(ctx, linkQuestionTask, arg.QuestionID, arg.TaskID)
	return err
}

const listChildQuestions = `-- name: ListChildQuestions :many
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1 AND parent_question_id = $2
ORDER BY created_at
`

type ListChildQuestionsParams struct {
	ProjectID        int32       `db:"project_id" json:"project_id"`
	ParentQuestionID pgtype.Int4 `db:"parent_question_id" json:"parent_question_id"`
}

func (q *Queries) ListChildQuestions(ctx context.Context, arg ListChildQuestionsParams) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, listChildQuestions, arg.ProjectID, arg.ParentQuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1
ORDER BY created_at
`

func (q *Queries) ListQuestions(ctx context.Context, projectID int32) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByOwner = `-- name: ListQuestionsByOwner :many
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1 AND owner_user_id = $2 AND answer IS NULL
ORDER BY created_at
`

type ListQuestionsByOwnerParams struct {
	ProjectID   int32       `db:"project_id" json:"project_id"`
	OwnerUserID pgtype.Int4 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) ListQuestionsByOwner(ctx context.Context, arg ListQuestionsByOwnerParams) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsByOwner, arg.ProjectID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByTask = `-- name: ListQuestionsByTask :many
SELECT q.id, q.project_id, q.category, q.question, q.answer, q.created_at, q.updated_at, q.parent_question_id, q.owner_user_id
FROM zdx_questions q
JOIN zdx_question_tasks qt ON qt.question_id = q.id
WHERE qt.task_id = $1
ORDER BY qt.created_at
`

func (q *Queries) ListQuestionsByTask(ctx context.Context, taskID string) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestionsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByQuestion = `-- name: ListTasksByQuestion :many
SELECT t.id, t.issue, t.title, t.text, t.status, t.feature, t.reason,
       t.created_at, t.updated_at, t.test_plan, t.test_refs, t.task_group, t.target_branch
FROM zdx_tasks t
JOIN zdx_question_tasks qt ON qt.task_id = t.id
WHERE qt.question_id = $1
ORDER BY qt.created_at
`

type ListTasksByQuestionRow struct {
	ID           string             `db:"id" json:"id"`
	Issue        string             `db:"issue" json:"issue"`
	Title        string             `db:"title" json:"title"`
	Text         string             `db:"text" json:"text"`
	Status       string             `db:"status" json:"status"`
	Feature      string             `db:"feature" json:"feature"`
	Reason       string             `db:"reason" json:"reason"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TestPlan     string             `db:"test_plan" json:"test_plan"`
	TestRefs     string             `db:"test_refs" json:"test_refs"`
	TaskGroup    string             `db:"task_group" json:"task_group"`
	TargetBranch string             `db:"target_branch" json:"target_branch"`
}

func (q *Queries) ListTasksByQuestion(ctx context.Context, questionID int32) ([]ListTasksByQuestionRow, error) {
	rows, err := q.db.Query(ctx, listTasksByQuestion, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByQuestionRow
	for rows.Next() {
		var i ListTasksByQuestionRow
		if err := rows.Scan(
			&i.ID,
			&i.Issue,
			&i.Title,
			&i.Text,
			&i.Status,
			&i.Feature,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestPlan,
			&i.TestRefs,
			&i.TaskGroup,
			&i.TargetBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnansweredQuestions = `-- name: ListUnansweredQuestions :many
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1 AND answer IS NULL
ORDER BY created_at
`

func (q *Queries) ListUnansweredQuestions(ctx context.Context, projectID int32) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, listUnansweredQuestions, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchQuestions = `-- name: SearchQuestions :many
SELECT id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
FROM zdx_questions
WHERE project_id = $1
  AND (question ILIKE '%' || $2::text || '%' OR answer ILIKE '%' || $2::text || '%')
ORDER BY created_at DESC
LIMIT 10
`

type SearchQuestionsParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	Query     string `db:"query" json:"query"`
}

// metaquery: off
func (q *Queries) SearchQuestions(ctx context.Context, arg SearchQuestionsParams) ([]ZdxQuestion, error) {
	rows, err := q.db.Query(ctx, searchQuestions, arg.ProjectID, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxQuestion
	for rows.Next() {
		var i ZdxQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Category,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentQuestionID,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkQuestionTask = `-- name: UnlinkQuestionTask :exec
DELETE FROM zdx_question_tasks
WHERE question_id = $1 AND task_id = $2
`

type UnlinkQuestionTaskParams struct {
	QuestionID int32  `db:"question_id" json:"question_id"`
	TaskID     string `db:"task_id" json:"task_id"`
}

func (q *Queries) UnlinkQuestionTask(ctx context.Context, arg UnlinkQuestionTaskParams) error {
	_, err := q.db.Exec(ctx, unlinkQuestionTask, arg.QuestionID, arg.TaskID)
	return err
}

const updateQuestionOwner = `-- name: UpdateQuestionOwner :one
UPDATE zdx_questions
SET owner_user_id = $3,
    updated_at    = NOW()
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, category, question, answer, created_at, updated_at, parent_question_id, owner_user_id
`

type UpdateQuestionOwnerParams struct {
	ProjectID   int32       `db:"project_id" json:"project_id"`
	ID          int32       `db:"id" json:"id"`
	OwnerUserID pgtype.Int4 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) UpdateQuestionOwner(ctx context.Context, arg UpdateQuestionOwnerParams) (ZdxQuestion, error) {
	row := q.db.QueryRow(ctx, updateQuestionOwner, arg.ProjectID, arg.ID, arg.OwnerUserID)
	var i ZdxQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Category,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentQuestionID,
		&i.OwnerUserID,
	)
	return i, err
}
