// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddComment(ctx context.Context, arg AddCommentParams) (AddCommentRow, error)
	AddRevision(ctx context.Context, arg AddRevisionParams) error
	AddSpec(ctx context.Context, arg AddSpecParams) (AddSpecRow, error)
	AddThemeBlocker(ctx context.Context, arg AddThemeBlockerParams) error
	AnswerBlockerQuestion(ctx context.Context, arg AnswerBlockerQuestionParams) error
	AnswerQuestion(ctx context.Context, arg AnswerQuestionParams) (ZdxQuestion, error)
	AppendIssueWork(ctx context.Context, arg AppendIssueWorkParams) error
	AttachCodeRefToIssue(ctx context.Context, arg AttachCodeRefToIssueParams) error
	AttachCodeRefToTask(ctx context.Context, arg AttachCodeRefToTaskParams) error
	AttachFileToIssue(ctx context.Context, arg AttachFileToIssueParams) error
	CloseIssue(ctx context.Context, arg CloseIssueParams) error
	CountApiKeys(ctx context.Context) (int32, error)
	CountClaudeEvents(ctx context.Context, sessionPk int64) (int64, error)
	CountUnreadForRole(ctx context.Context, arg CountUnreadForRoleParams) (int32, error)
	// Counts comments on targets where the user has previously commented,
	// excluding the user's own comments, that are newer than the user's last read.
	CountUnreadResponsesForUser(ctx context.Context, arg CountUnreadResponsesForUserParams) (int32, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ZdxApiKey, error)
	CreateClaudeEvent(ctx context.Context, arg CreateClaudeEventParams) error
	CreateClaudeSession(ctx context.Context, arg CreateClaudeSessionParams) (ZdxClaudeSession, error)
	CreateCodeRef(ctx context.Context, arg CreateCodeRefParams) (ZdxCodeRef, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (ZdxFile, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (ZdxIssue, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (ZdxTask, error)
	CreateTheme(ctx context.Context, arg CreateThemeParams) (ZdxTheme, error)
	CreateTodo(ctx context.Context, arg CreateTodoParams) (ZdxTodo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error)
	DeferSpec(ctx context.Context, id int32) error
	DeleteCodeRef(ctx context.Context, arg DeleteCodeRefParams) error
	DeleteErrorReports(ctx context.Context, projectID pgtype.Int4) error
	DeleteFeature(ctx context.Context, id int32) error
	DeleteTask(ctx context.Context, id string) error
	// Will fail at the DB level (RESTRICT) if spec_tests rows reference this test.
	// Call ListSpecsCoveredByTest first to surface what breaks.
	DeleteTest(ctx context.Context, id int32) error
	DeleteTodosForProject(ctx context.Context, projectID int32) error
	DetachCodeRefFromIssue(ctx context.Context, arg DetachCodeRefFromIssueParams) error
	DetachCodeRefFromTask(ctx context.Context, arg DetachCodeRefFromTaskParams) error
	GetApiKeyByToken(ctx context.Context, token string) (ZdxApiKey, error)
	GetApiKeyUserRole(ctx context.Context, token string) (string, error)
	GetBlockerQuestion(ctx context.Context, arg GetBlockerQuestionParams) (ZdxBlockerQuestion, error)
	GetClaudeSession(ctx context.Context, arg GetClaudeSessionParams) (ZdxClaudeSession, error)
	GetClaudeSessionBySessionID(ctx context.Context, arg GetClaudeSessionBySessionIDParams) (ZdxClaudeSession, error)
	GetCodeRef(ctx context.Context, arg GetCodeRefParams) (ZdxCodeRef, error)
	GetCommentRead(ctx context.Context, arg GetCommentReadParams) (pgtype.Timestamptz, error)
	GetFeature(ctx context.Context, arg GetFeatureParams) (ZdxFeature, error)
	GetFile(ctx context.Context, id int32) (ZdxFile, error)
	GetIssue(ctx context.Context, arg GetIssueParams) (ZdxIssue, error)
	GetIssueFiles(ctx context.Context, issueID string) ([]GetIssueFilesRow, error)
	GetIssueWork(ctx context.Context, issueID string) ([]ZdxIssueWork, error)
	GetLLMConfig(ctx context.Context) (ZdxLlmConfig, error)
	GetLatestJournalEntry(ctx context.Context, arg GetLatestJournalEntryParams) (ZdxJournalEntry, error)
	GetPlanByFeature(ctx context.Context, featureID int32) (ZdxPlan, error)
	GetProjectBySlug(ctx context.Context, slug string) (ZdxProject, error)
	GetProjectGitConfig(ctx context.Context, slug string) (GetProjectGitConfigRow, error)
	GetQuestion(ctx context.Context, arg GetQuestionParams) (ZdxQuestion, error)
	GetState(ctx context.Context, arg GetStateParams) (string, error)
	GetTest(ctx context.Context, arg GetTestParams) (ZdxTest, error)
	GetThemeByID(ctx context.Context, arg GetThemeByIDParams) (ZdxTheme, error)
	GetThemeByName(ctx context.Context, arg GetThemeByNameParams) (ZdxTheme, error)
	GetUserByEmail(ctx context.Context, email string) (ZdxUser, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	HasUnreadCommentsForTarget(ctx context.Context, arg HasUnreadCommentsForTargetParams) (bool, error)
	InsertBlockerQuestion(ctx context.Context, arg InsertBlockerQuestionParams) (ZdxBlockerQuestion, error)
	InsertErrorReport(ctx context.Context, arg InsertErrorReportParams) (ZdxErrorReport, error)
	InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (ZdxJournalEntry, error)
	InsertQuestion(ctx context.Context, arg InsertQuestionParams) (ZdxQuestion, error)
	InsertSlowQuery(ctx context.Context, arg InsertSlowQueryParams) (ZdxSlowQuery, error)
	InsertTestResultHistory(ctx context.Context, arg InsertTestResultHistoryParams) error
	LinkSpecTest(ctx context.Context, arg LinkSpecTestParams) error
	ListBlockerQuestions(ctx context.Context, projectID int32) ([]ZdxBlockerQuestion, error)
	ListBlockerQuestionsByTarget(ctx context.Context, arg ListBlockerQuestionsByTargetParams) ([]ZdxBlockerQuestion, error)
	ListClaudeEvents(ctx context.Context, sessionPk int64) ([]ZdxClaudeEvent, error)
	ListClaudeEventsPaginated(ctx context.Context, arg ListClaudeEventsPaginatedParams) ([]ZdxClaudeEvent, error)
	ListClaudeSessions(ctx context.Context, projectID int32) ([]ZdxClaudeSession, error)
	ListCodeRefsByIssue(ctx context.Context, issueID string) ([]ZdxCodeRef, error)
	ListCodeRefsByTask(ctx context.Context, taskID string) ([]ZdxCodeRef, error)
	ListComments(ctx context.Context, arg ListCommentsParams) ([]ListCommentsRow, error)
	ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]ListCommentsByAuthorRow, error)
	ListErrorReports(ctx context.Context, projectID pgtype.Int4) ([]ZdxErrorReport, error)
	ListFeatures(ctx context.Context, projectID int32) ([]ZdxFeature, error)
	ListIssues(ctx context.Context, projectID int32) ([]ZdxIssue, error)
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]ZdxJournalEntry, error)
	ListOpenIssues(ctx context.Context, projectID int32) ([]ZdxIssue, error)
	ListPendingBlockerQuestions(ctx context.Context, projectID int32) ([]ZdxBlockerQuestion, error)
	ListProjects(ctx context.Context) ([]ZdxProject, error)
	ListQuestions(ctx context.Context, projectID int32) ([]ZdxQuestion, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]ZdxRevision, error)
	ListSlowQueries(ctx context.Context, projectID pgtype.Int4) ([]ZdxSlowQuery, error)
	ListSpecs(ctx context.Context, featureID int32) ([]ZdxSpec, error)
	// Used to show what breaks if a test is deleted.
	ListSpecsCoveredByTest(ctx context.Context, testID int32) ([]ListSpecsCoveredByTestRow, error)
	ListSpecsForProject(ctx context.Context, projectID int32) ([]ZdxSpec, error)
	// Features not reviewed in more than @stale_days days (or never reviewed).
	ListStaleFeatures(ctx context.Context, arg ListStaleFeaturesParams) ([]ZdxFeature, error)
	ListTasks(ctx context.Context, projectID int32) ([]ZdxTask, error)
	ListTasksByFeature(ctx context.Context, arg ListTasksByFeatureParams) ([]ZdxTask, error)
	ListTasksByIssue(ctx context.Context, arg ListTasksByIssueParams) ([]ZdxTask, error)
	ListTests(ctx context.Context, projectID int32) ([]ZdxTest, error)
	ListTestsByLayer(ctx context.Context, arg ListTestsByLayerParams) ([]ZdxTest, error)
	ListTestsForSpec(ctx context.Context, specID int32) ([]ZdxTest, error)
	ListThemes(ctx context.Context, projectID int32) ([]ListThemesRow, error)
	ListTimed(ctx context.Context, projectID int32) ([]ZdxTimed, error)
	ListTodos(ctx context.Context, projectID int32) ([]ZdxTodo, error)
	// Specs that have no entries in zdx_spec_tests (no test coverage) and are not deferred.
	ListUncoveredSpecs(ctx context.Context, projectID int32) ([]ListUncoveredSpecsRow, error)
	ListWorklogForProject(ctx context.Context, projectID int32) ([]ListWorklogForProjectRow, error)
	MarkFeatureReviewed(ctx context.Context, arg MarkFeatureReviewedParams) error
	MarkTaskDone(ctx context.Context, arg MarkTaskDoneParams) error
	MarkTaskUndone(ctx context.Context, id string) error
	NextID(ctx context.Context, arg NextIDParams) (int32, error)
	RemoveThemeBlocker(ctx context.Context, arg RemoveThemeBlockerParams) error
	ReopenIssue(ctx context.Context, arg ReopenIssueParams) error
	SearchIssues(ctx context.Context, arg SearchIssuesParams) ([]ZdxIssue, error)
	SetIssueField(ctx context.Context, arg SetIssueFieldParams) error
	SetIssuePriority(ctx context.Context, arg SetIssuePriorityParams) error
	SetProjectGitConfig(ctx context.Context, arg SetProjectGitConfigParams) error
	SetState(ctx context.Context, arg SetStateParams) error
	TouchApiKey(ctx context.Context, id int32) error
	UndeferSpec(ctx context.Context, id int32) error
	UnlinkSpecTest(ctx context.Context, arg UnlinkSpecTestParams) error
	UpdateFeatureField(ctx context.Context, arg UpdateFeatureFieldParams) error
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) error
	UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	UpdateThemeStatus(ctx context.Context, arg UpdateThemeStatusParams) error
	UpsertCommentRead(ctx context.Context, arg UpsertCommentReadParams) error
	UpsertFeature(ctx context.Context, arg UpsertFeatureParams) (ZdxFeature, error)
	UpsertLLMConfig(ctx context.Context, arg UpsertLLMConfigParams) (ZdxLlmConfig, error)
	UpsertPlan(ctx context.Context, arg UpsertPlanParams) (ZdxPlan, error)
	UpsertTest(ctx context.Context, arg UpsertTestParams) (ZdxTest, error)
	UpsertTestResult(ctx context.Context, arg UpsertTestResultParams) error
	UpsertTimed(ctx context.Context, arg UpsertTimedParams) error
}

var _ Querier = (*Queries)(nil)
