// Code generated by sqlc-go-codegen-metaquery. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package db

import (
	"github.com/iodesystems/sqlc-go-codegen-metaquery/metaquery"
)

var _ = metaquery.Query{}

var MetaCountReservationsForTodo = metaquery.Query{
	Name:   "CountReservationsForTodo",
	Cmd:    ":one",
	Source: "reservations.sql",
	SQL: `SELECT count(*)::int AS claim_count
FROM zdx_reservations r
JOIN zdx_todos t ON r.target_type = 'todo' AND r.target_id = t.id::text
WHERE r.project_id = $1
  AND t.project_id = $1
  AND t.id = $2`,
	Columns: []metaquery.Column{
		{Name: "claim_count", OriginalName: "claim_count", GoType: "int32"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "todo_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
	},
}

// WrapCountReservationsForTodo returns a metaquery.Builder over MetaCountReservationsForTodo, pre-bound with typed arguments.
func WrapCountReservationsForTodo(arg CountReservationsForTodoParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaCountReservationsForTodo, arg.ProjectID, arg.TodoID)
}

// CountReservationsForTodoCols gives typed, name-safe access to CountReservationsForTodo's output columns.
var CountReservationsForTodoCols = struct {
	ClaimCount metaquery.IntCol
}{
	ClaimCount: metaquery.NewIntCol("claim_count"),
}

var MetaExpireTaskLeaseForTest = metaquery.Query{
	Name:   "ExpireTaskLeaseForTest",
	Cmd:    ":exec",
	Source: "reservations.sql",
	SQL: `UPDATE zdx_reservations
SET lease_expires_at = NOW() - interval '1 minute'
WHERE target_type = 'task'
  AND target_id = $1
  AND released_at IS NULL`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "task_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapExpireTaskLeaseForTest returns a metaquery.Builder over MetaExpireTaskLeaseForTest, pre-bound with typed arguments.
func WrapExpireTaskLeaseForTest(taskID string) *metaquery.Builder {
	return metaquery.Wrap(&MetaExpireTaskLeaseForTest, taskID)
}

var MetaGetActiveIssueReservation = metaquery.Query{
	Name:   "GetActiveIssueReservation",
	Cmd:    ":one",
	Source: "reservations.sql",
	SQL: `SELECT id, project_id, target_type, target_id, claimed_by, claimed_at, released_at, lease_expires_at
FROM zdx_reservations
WHERE project_id = $1
  AND target_type = 'issue'
  AND target_id = $2
  AND released_at IS NULL
  AND lease_expires_at > NOW()
ORDER BY claimed_at DESC
LIMIT 1`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapGetActiveIssueReservation returns a metaquery.Builder over MetaGetActiveIssueReservation, pre-bound with typed arguments.
func WrapGetActiveIssueReservation(arg GetActiveIssueReservationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaGetActiveIssueReservation, arg.ProjectID, arg.TargetID)
}

// GetActiveIssueReservationCols gives typed, name-safe access to GetActiveIssueReservation's output columns.
var GetActiveIssueReservationCols = struct {
	ID             metaquery.IntCol
	ProjectID      metaquery.IntCol
	TargetType     metaquery.TextCol
	TargetID       metaquery.TextCol
	ClaimedBy      metaquery.TextCol
	ClaimedAt      metaquery.TimeCol
	ReleasedAt     metaquery.TimeCol
	LeaseExpiresAt metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	ProjectID:      metaquery.NewIntCol("project_id"),
	TargetType:     metaquery.NewTextCol("target_type"),
	TargetID:       metaquery.NewTextCol("target_id"),
	ClaimedBy:      metaquery.NewTextCol("claimed_by"),
	ClaimedAt:      metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:     metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt: metaquery.NewTimeCol("lease_expires_at"),
}

var MetaInsertReservation = metaquery.Query{
	Name:   "InsertReservation",
	Cmd:    ":one",
	Source: "reservations.sql",
	SQL: `INSERT INTO zdx_reservations (project_id, target_type, target_id, claimed_by, claimed_at, lease_expires_at)
VALUES ($1, $2, $3, $4, NOW(), $5)
RETURNING id, project_id, target_type, target_id, claimed_by, claimed_at, released_at, lease_expires_at`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "claimed_by", GoType: "string", DBType: "text", NotNull: true},
		{Position: 5, Name: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "pg_catalog.timestamptz"},
	},
	Table: &metaquery.Table{Name: "zdx_reservations"},
}

// WrapInsertReservation returns a metaquery.Builder over MetaInsertReservation, pre-bound with typed arguments.
func WrapInsertReservation(arg InsertReservationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaInsertReservation, arg.ProjectID, arg.TargetType, arg.TargetID, arg.ClaimedBy, arg.LeaseExpiresAt)
}

// InsertReservationCols gives typed, name-safe access to InsertReservation's output columns.
var InsertReservationCols = struct {
	ID             metaquery.IntCol
	ProjectID      metaquery.IntCol
	TargetType     metaquery.TextCol
	TargetID       metaquery.TextCol
	ClaimedBy      metaquery.TextCol
	ClaimedAt      metaquery.TimeCol
	ReleasedAt     metaquery.TimeCol
	LeaseExpiresAt metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	ProjectID:      metaquery.NewIntCol("project_id"),
	TargetType:     metaquery.NewTextCol("target_type"),
	TargetID:       metaquery.NewTextCol("target_id"),
	ClaimedBy:      metaquery.NewTextCol("claimed_by"),
	ClaimedAt:      metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:     metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt: metaquery.NewTimeCol("lease_expires_at"),
}

var MetaListReservationsByIssue = metaquery.Query{
	Name:   "ListReservationsByIssue",
	Cmd:    ":many",
	Source: "reservations.sql",
	SQL: `SELECT
  r.id,
  r.target_type,
  r.target_id,
  r.claimed_by,
  r.claimed_at,
  r.released_at,
  r.lease_expires_at,
  t.text AS todo_text,
  cs.id AS session_id,
  cs.status AS session_status,
  cs.closed_at AS session_closed_at,
  cs.header AS session_header,
  cs.alias AS session_alias
FROM zdx_reservations r
JOIN zdx_todos t ON r.target_type = 'todo' AND r.target_id = t.id::text AND t.project_id = $1
LEFT JOIN zdx_claude_sessions cs ON cs.todo_id = t.id AND cs.project_id = $1
WHERE r.project_id = $1
  AND t.target_type = 'issue'
  AND t.target_id = $2
ORDER BY r.claimed_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "todo_text", OriginalName: "text", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_todos"},
		{Name: "session_id", OriginalName: "id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_claude_sessions"},
		{Name: "session_status", OriginalName: "status", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
		{Name: "session_closed_at", OriginalName: "closed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_claude_sessions"},
		{Name: "session_header", OriginalName: "header", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
		{Name: "session_alias", OriginalName: "alias", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListReservationsByIssue returns a metaquery.Builder over MetaListReservationsByIssue, pre-bound with typed arguments.
func WrapListReservationsByIssue(arg ListReservationsByIssueParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListReservationsByIssue, arg.ProjectID, arg.IssueID)
}

// ListReservationsByIssueCols gives typed, name-safe access to ListReservationsByIssue's output columns.
var ListReservationsByIssueCols = struct {
	ID              metaquery.IntCol
	TargetType      metaquery.TextCol
	TargetID        metaquery.TextCol
	ClaimedBy       metaquery.TextCol
	ClaimedAt       metaquery.TimeCol
	ReleasedAt      metaquery.TimeCol
	LeaseExpiresAt  metaquery.TimeCol
	TodoText        metaquery.TextCol
	SessionID       metaquery.IntCol
	SessionStatus   metaquery.TextCol
	SessionClosedAt metaquery.TimeCol
	SessionHeader   metaquery.TextCol
	SessionAlias    metaquery.TextCol
}{
	ID:              metaquery.NewIntCol("id"),
	TargetType:      metaquery.NewTextCol("target_type"),
	TargetID:        metaquery.NewTextCol("target_id"),
	ClaimedBy:       metaquery.NewTextCol("claimed_by"),
	ClaimedAt:       metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:      metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt:  metaquery.NewTimeCol("lease_expires_at"),
	TodoText:        metaquery.NewTextCol("text"),
	SessionID:       metaquery.NewIntCol("id"),
	SessionStatus:   metaquery.NewTextCol("status"),
	SessionClosedAt: metaquery.NewTimeCol("closed_at"),
	SessionHeader:   metaquery.NewTextCol("header"),
	SessionAlias:    metaquery.NewTextCol("alias"),
}

var MetaListReservationsByIssueID = metaquery.Query{
	Name:   "ListReservationsByIssueID",
	Cmd:    ":many",
	Source: "reservations.sql",
	SQL: `SELECT id, project_id, target_type, target_id, claimed_by, claimed_at, released_at, lease_expires_at
FROM zdx_reservations
WHERE project_id = $1
  AND target_type = 'issue'
  AND target_id = $2
ORDER BY claimed_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "issue_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListReservationsByIssueID returns a metaquery.Builder over MetaListReservationsByIssueID, pre-bound with typed arguments.
func WrapListReservationsByIssueID(arg ListReservationsByIssueIDParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListReservationsByIssueID, arg.ProjectID, arg.IssueID)
}

// ListReservationsByIssueIDCols gives typed, name-safe access to ListReservationsByIssueID's output columns.
var ListReservationsByIssueIDCols = struct {
	ID             metaquery.IntCol
	ProjectID      metaquery.IntCol
	TargetType     metaquery.TextCol
	TargetID       metaquery.TextCol
	ClaimedBy      metaquery.TextCol
	ClaimedAt      metaquery.TimeCol
	ReleasedAt     metaquery.TimeCol
	LeaseExpiresAt metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	ProjectID:      metaquery.NewIntCol("project_id"),
	TargetType:     metaquery.NewTextCol("target_type"),
	TargetID:       metaquery.NewTextCol("target_id"),
	ClaimedBy:      metaquery.NewTextCol("claimed_by"),
	ClaimedAt:      metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:     metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt: metaquery.NewTimeCol("lease_expires_at"),
}

var MetaListReservationsByTaskID = metaquery.Query{
	Name:   "ListReservationsByTaskID",
	Cmd:    ":many",
	Source: "reservations.sql",
	SQL: `SELECT id, project_id, target_type, target_id, claimed_by, claimed_at, released_at, lease_expires_at
FROM zdx_reservations
WHERE project_id = $1
  AND target_type = 'task'
  AND target_id = $2
ORDER BY claimed_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "task_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListReservationsByTaskID returns a metaquery.Builder over MetaListReservationsByTaskID, pre-bound with typed arguments.
func WrapListReservationsByTaskID(arg ListReservationsByTaskIDParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListReservationsByTaskID, arg.ProjectID, arg.TaskID)
}

// ListReservationsByTaskIDCols gives typed, name-safe access to ListReservationsByTaskID's output columns.
var ListReservationsByTaskIDCols = struct {
	ID             metaquery.IntCol
	ProjectID      metaquery.IntCol
	TargetType     metaquery.TextCol
	TargetID       metaquery.TextCol
	ClaimedBy      metaquery.TextCol
	ClaimedAt      metaquery.TimeCol
	ReleasedAt     metaquery.TimeCol
	LeaseExpiresAt metaquery.TimeCol
}{
	ID:             metaquery.NewIntCol("id"),
	ProjectID:      metaquery.NewIntCol("project_id"),
	TargetType:     metaquery.NewTextCol("target_type"),
	TargetID:       metaquery.NewTextCol("target_id"),
	ClaimedBy:      metaquery.NewTextCol("claimed_by"),
	ClaimedAt:      metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:     metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt: metaquery.NewTimeCol("lease_expires_at"),
}

var MetaListReservationsByTodoKey = metaquery.Query{
	Name:   "ListReservationsByTodoKey",
	Cmd:    ":many",
	Source: "reservations.sql",
	SQL: `SELECT
  r.id,
  r.target_type,
  r.target_id,
  r.claimed_by,
  r.claimed_at,
  r.released_at,
  r.lease_expires_at,
  cs.id AS session_id,
  cs.status AS session_status,
  cs.closed_at AS session_closed_at,
  cs.header AS session_header,
  cs.alias AS session_alias
FROM zdx_reservations r
JOIN zdx_todos t ON r.target_type = 'todo' AND r.target_id = t.id::text
LEFT JOIN zdx_claude_sessions cs ON cs.todo_id = t.id AND cs.project_id = r.project_id
WHERE r.project_id = $1
  AND t.project_id = $1
  AND t.key = $2
ORDER BY r.claimed_at DESC`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_at", OriginalName: "claimed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", NotNull: true, Table: "zdx_reservations"},
		{Name: "released_at", OriginalName: "released_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "lease_expires_at", OriginalName: "lease_expires_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_reservations"},
		{Name: "session_id", OriginalName: "id", GoType: "pgtype.Int8", DBType: "int8", Table: "zdx_claude_sessions"},
		{Name: "session_status", OriginalName: "status", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
		{Name: "session_closed_at", OriginalName: "closed_at", GoType: "pgtype.Timestamptz", DBType: "timestamptz", Table: "zdx_claude_sessions"},
		{Name: "session_header", OriginalName: "header", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
		{Name: "session_alias", OriginalName: "alias", GoType: "pgtype.Text", DBType: "text", Table: "zdx_claude_sessions"},
	},
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "key", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapListReservationsByTodoKey returns a metaquery.Builder over MetaListReservationsByTodoKey, pre-bound with typed arguments.
func WrapListReservationsByTodoKey(arg ListReservationsByTodoKeyParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaListReservationsByTodoKey, arg.ProjectID, arg.Key)
}

// ListReservationsByTodoKeyCols gives typed, name-safe access to ListReservationsByTodoKey's output columns.
var ListReservationsByTodoKeyCols = struct {
	ID              metaquery.IntCol
	TargetType      metaquery.TextCol
	TargetID        metaquery.TextCol
	ClaimedBy       metaquery.TextCol
	ClaimedAt       metaquery.TimeCol
	ReleasedAt      metaquery.TimeCol
	LeaseExpiresAt  metaquery.TimeCol
	SessionID       metaquery.IntCol
	SessionStatus   metaquery.TextCol
	SessionClosedAt metaquery.TimeCol
	SessionHeader   metaquery.TextCol
	SessionAlias    metaquery.TextCol
}{
	ID:              metaquery.NewIntCol("id"),
	TargetType:      metaquery.NewTextCol("target_type"),
	TargetID:        metaquery.NewTextCol("target_id"),
	ClaimedBy:       metaquery.NewTextCol("claimed_by"),
	ClaimedAt:       metaquery.NewTimeCol("claimed_at"),
	ReleasedAt:      metaquery.NewTimeCol("released_at"),
	LeaseExpiresAt:  metaquery.NewTimeCol("lease_expires_at"),
	SessionID:       metaquery.NewIntCol("id"),
	SessionStatus:   metaquery.NewTextCol("status"),
	SessionClosedAt: metaquery.NewTimeCol("closed_at"),
	SessionHeader:   metaquery.NewTextCol("header"),
	SessionAlias:    metaquery.NewTextCol("alias"),
}

var MetaReleaseExpiredReservations = metaquery.Query{
	Name:   "ReleaseExpiredReservations",
	Cmd:    ":many",
	Source: "reservations.sql",
	SQL: `UPDATE zdx_reservations
SET released_at = NOW()
WHERE lease_expires_at < NOW()
  AND released_at IS NULL
RETURNING id, project_id, target_type, target_id, claimed_by`,
	Columns: []metaquery.Column{
		{Name: "id", OriginalName: "id", GoType: "int64", DBType: "int8", NotNull: true, Table: "zdx_reservations"},
		{Name: "project_id", OriginalName: "project_id", GoType: "int32", DBType: "int4", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_type", OriginalName: "target_type", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "target_id", OriginalName: "target_id", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
		{Name: "claimed_by", OriginalName: "claimed_by", GoType: "string", DBType: "text", NotNull: true, Table: "zdx_reservations"},
	},
}

// WrapReleaseExpiredReservations returns a metaquery.Builder over MetaReleaseExpiredReservations, pre-bound with typed arguments.
func WrapReleaseExpiredReservations() *metaquery.Builder {
	return metaquery.Wrap(&MetaReleaseExpiredReservations)
}

// ReleaseExpiredReservationsCols gives typed, name-safe access to ReleaseExpiredReservations's output columns.
var ReleaseExpiredReservationsCols = struct {
	ID         metaquery.IntCol
	ProjectID  metaquery.IntCol
	TargetType metaquery.TextCol
	TargetID   metaquery.TextCol
	ClaimedBy  metaquery.TextCol
}{
	ID:         metaquery.NewIntCol("id"),
	ProjectID:  metaquery.NewIntCol("project_id"),
	TargetType: metaquery.NewTextCol("target_type"),
	TargetID:   metaquery.NewTextCol("target_id"),
	ClaimedBy:  metaquery.NewTextCol("claimed_by"),
}

var MetaReleaseReservation = metaquery.Query{
	Name:   "ReleaseReservation",
	Cmd:    ":exec",
	Source: "reservations.sql",
	SQL: `UPDATE zdx_reservations SET released_at = NOW()
WHERE project_id = $1
  AND target_type = $2
  AND target_id = $3
  AND released_at IS NULL`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 2, Name: "target_type", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapReleaseReservation returns a metaquery.Builder over MetaReleaseReservation, pre-bound with typed arguments.
func WrapReleaseReservation(arg ReleaseReservationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaReleaseReservation, arg.ProjectID, arg.TargetType, arg.TargetID)
}

var MetaRenewIssueReservation = metaquery.Query{
	Name:   "RenewIssueReservation",
	Cmd:    ":exec",
	Source: "reservations.sql",
	SQL: `UPDATE zdx_reservations
SET lease_expires_at = NOW() + $1::interval
WHERE project_id = $2
  AND target_type = 'issue'
  AND target_id = $3
  AND claimed_by = $4
  AND released_at IS NULL`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "lease_duration", GoType: "pgtype.Interval", DBType: "interval", NotNull: true},
		{Position: 2, Name: "project_id", GoType: "int32", DBType: "pg_catalog.int4", NotNull: true},
		{Position: 3, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 4, Name: "claimed_by", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapRenewIssueReservation returns a metaquery.Builder over MetaRenewIssueReservation, pre-bound with typed arguments.
func WrapRenewIssueReservation(arg RenewIssueReservationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaRenewIssueReservation, arg.LeaseDuration, arg.ProjectID, arg.TargetID, arg.ClaimedBy)
}

var MetaRenewTaskReservation = metaquery.Query{
	Name:   "RenewTaskReservation",
	Cmd:    ":exec",
	Source: "reservations.sql",
	SQL: `UPDATE zdx_reservations
SET lease_expires_at = NOW() + $1::interval
WHERE target_type = 'task'
  AND target_id = $2
  AND claimed_by = $3
  AND released_at IS NULL`,
	Args: []metaquery.Arg{
		{Position: 1, Name: "lease_duration", GoType: "pgtype.Interval", DBType: "interval", NotNull: true},
		{Position: 2, Name: "target_id", GoType: "string", DBType: "text", NotNull: true},
		{Position: 3, Name: "claimed_by", GoType: "string", DBType: "text", NotNull: true},
	},
}

// WrapRenewTaskReservation returns a metaquery.Builder over MetaRenewTaskReservation, pre-bound with typed arguments.
func WrapRenewTaskReservation(arg RenewTaskReservationParams) *metaquery.Builder {
	return metaquery.Wrap(&MetaRenewTaskReservation, arg.LeaseDuration, arg.TargetID, arg.ClaimedBy)
}
