// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_audit_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionAuditEvent = `-- name: CreateSessionAuditEvent :exec
INSERT INTO zdx_session_audit_events (session_pk, agent_id, todo_id, turn_id, event_type, payload, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateSessionAuditEventParams struct {
	SessionPk  int64              `db:"session_pk" json:"session_pk"`
	AgentID    string             `db:"agent_id" json:"agent_id"`
	TodoID     pgtype.Int4        `db:"todo_id" json:"todo_id"`
	TurnID     string             `db:"turn_id" json:"turn_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	Payload    []byte             `db:"payload" json:"payload"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) CreateSessionAuditEvent(ctx context.Context, arg CreateSessionAuditEventParams) error {
	_, err := q.db.Exec(ctx, createSessionAuditEvent,
		arg.SessionPk,
		arg.AgentID,
		arg.TodoID,
		arg.TurnID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}

const listAgentAuditEvents = `-- name: ListAgentAuditEvents :many
SELECT id, session_pk, agent_id, todo_id, turn_id, event_type, payload, occurred_at
FROM zdx_session_audit_events
WHERE agent_id = $1
ORDER BY occurred_at
LIMIT 200
`

func (q *Queries) ListAgentAuditEvents(ctx context.Context, agentID string) ([]ZdxSessionAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAgentAuditEvents, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxSessionAuditEvent
	for rows.Next() {
		var i ZdxSessionAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionPk,
			&i.AgentID,
			&i.TodoID,
			&i.TurnID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAuditEvents = `-- name: ListSessionAuditEvents :many
SELECT id, session_pk, agent_id, todo_id, turn_id, event_type, payload, occurred_at
FROM zdx_session_audit_events
WHERE session_pk = $1
ORDER BY occurred_at
`

func (q *Queries) ListSessionAuditEvents(ctx context.Context, sessionPk int64) ([]ZdxSessionAuditEvent, error) {
	rows, err := q.db.Query(ctx, listSessionAuditEvents, sessionPk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZdxSessionAuditEvent
	for rows.Next() {
		var i ZdxSessionAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionPk,
			&i.AgentID,
			&i.TodoID,
			&i.TurnID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
