// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTaskReview = `-- name: GetTaskReview :one
SELECT id, project_id, task_id, reviewer_role, reviewer_user_id, verdict, body, created_at, updated_at
FROM zdx_task_reviews
WHERE id = $1
`

func (q *Queries) GetTaskReview(ctx context.Context, id int32) (ZdxTaskReview, error) {
	row := q.db.QueryRow(ctx, getTaskReview, id)
	var i ZdxTaskReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.ReviewerRole,
		&i.ReviewerUserID,
		&i.Verdict,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskReviewByTask = `-- name: GetTaskReviewByTask :one
SELECT id, project_id, task_id, reviewer_role, reviewer_user_id, verdict, body, created_at, updated_at
FROM zdx_task_reviews
WHERE project_id = $1 AND task_id = $2 AND reviewer_role = $3
`

type GetTaskReviewByTaskParams struct {
	ProjectID    int32  `db:"project_id" json:"project_id"`
	TaskID       string `db:"task_id" json:"task_id"`
	ReviewerRole string `db:"reviewer_role" json:"reviewer_role"`
}

func (q *Queries) GetTaskReviewByTask(ctx context.Context, arg GetTaskReviewByTaskParams) (ZdxTaskReview, error) {
	row := q.db.QueryRow(ctx, getTaskReviewByTask, arg.ProjectID, arg.TaskID, arg.ReviewerRole)
	var i ZdxTaskReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.ReviewerRole,
		&i.ReviewerUserID,
		&i.Verdict,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskReviews = `-- name: ListTaskReviews :many
SELECT r.id, r.project_id, r.task_id, r.reviewer_role, r.reviewer_user_id, r.verdict, r.body, r.created_at, r.updated_at,
       u.email AS reviewer_email
FROM zdx_task_reviews r
LEFT JOIN zdx_users u ON u.id = r.reviewer_user_id
WHERE r.project_id = $1 AND r.task_id = $2
ORDER BY r.created_at ASC
`

type ListTaskReviewsParams struct {
	ProjectID int32  `db:"project_id" json:"project_id"`
	TaskID    string `db:"task_id" json:"task_id"`
}

type ListTaskReviewsRow struct {
	ID             int32              `db:"id" json:"id"`
	ProjectID      int32              `db:"project_id" json:"project_id"`
	TaskID         string             `db:"task_id" json:"task_id"`
	ReviewerRole   string             `db:"reviewer_role" json:"reviewer_role"`
	ReviewerUserID pgtype.Int4        `db:"reviewer_user_id" json:"reviewer_user_id"`
	Verdict        string             `db:"verdict" json:"verdict"`
	Body           string             `db:"body" json:"body"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ReviewerEmail  pgtype.Text        `db:"reviewer_email" json:"reviewer_email"`
}

func (q *Queries) ListTaskReviews(ctx context.Context, arg ListTaskReviewsParams) ([]ListTaskReviewsRow, error) {
	rows, err := q.db.Query(ctx, listTaskReviews, arg.ProjectID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskReviewsRow
	for rows.Next() {
		var i ListTaskReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.ReviewerRole,
			&i.ReviewerUserID,
			&i.Verdict,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewerEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTaskReview = `-- name: UpsertTaskReview :one
INSERT INTO zdx_task_reviews (project_id, task_id, reviewer_role, reviewer_user_id, verdict, body)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (project_id, task_id, reviewer_role) DO UPDATE
    SET verdict          = EXCLUDED.verdict,
        body             = EXCLUDED.body,
        reviewer_user_id = EXCLUDED.reviewer_user_id,
        updated_at       = NOW()
RETURNING id, project_id, task_id, reviewer_role, reviewer_user_id, verdict, body, created_at, updated_at
`

type UpsertTaskReviewParams struct {
	ProjectID      int32       `db:"project_id" json:"project_id"`
	TaskID         string      `db:"task_id" json:"task_id"`
	ReviewerRole   string      `db:"reviewer_role" json:"reviewer_role"`
	ReviewerUserID pgtype.Int4 `db:"reviewer_user_id" json:"reviewer_user_id"`
	Verdict        string      `db:"verdict" json:"verdict"`
	Body           string      `db:"body" json:"body"`
}

func (q *Queries) UpsertTaskReview(ctx context.Context, arg UpsertTaskReviewParams) (ZdxTaskReview, error) {
	row := q.db.QueryRow(ctx, upsertTaskReview,
		arg.ProjectID,
		arg.TaskID,
		arg.ReviewerRole,
		arg.ReviewerUserID,
		arg.Verdict,
		arg.Body,
	)
	var i ZdxTaskReview
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.ReviewerRole,
		&i.ReviewerUserID,
		&i.Verdict,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
