// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: timing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTimed = `-- name: CountTimed :one
SELECT count(*) FROM zdx_timed WHERE ($1::int IS NULL OR project_id = $1)
`

func (q *Queries) CountTimed(ctx context.Context, projectID pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, countTimed, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listTimed = `-- name: ListTimed :many
SELECT id, project_id, name, duration_ms, count, total_ms, source, context_json, created_at
FROM zdx_timed
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY duration_ms DESC
`

type ListTimedRow struct {
	ID          int64              `db:"id" json:"id"`
	ProjectID   pgtype.Int4        `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	DurationMs  int32              `db:"duration_ms" json:"duration_ms"`
	Count       int32              `db:"count" json:"count"`
	TotalMs     int64              `db:"total_ms" json:"total_ms"`
	Source      string             `db:"source" json:"source"`
	ContextJson string             `db:"context_json" json:"context_json"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTimed(ctx context.Context, projectID pgtype.Int4) ([]ListTimedRow, error) {
	rows, err := q.db.Query(ctx, listTimed, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimedRow
	for rows.Next() {
		var i ListTimedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DurationMs,
			&i.Count,
			&i.TotalMs,
			&i.Source,
			&i.ContextJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimedPaginated = `-- name: ListTimedPaginated :many
SELECT id, project_id, name, duration_ms, count, total_ms, source, context_json, created_at
FROM zdx_timed
WHERE ($1::int IS NULL OR project_id = $1)
ORDER BY duration_ms DESC
LIMIT $3 OFFSET $2
`

type ListTimedPaginatedParams struct {
	ProjectID pgtype.Int4 `db:"project_id" json:"project_id"`
	Off       int32       `db:"off" json:"off"`
	Lim       int32       `db:"lim" json:"lim"`
}

type ListTimedPaginatedRow struct {
	ID          int64              `db:"id" json:"id"`
	ProjectID   pgtype.Int4        `db:"project_id" json:"project_id"`
	Name        string             `db:"name" json:"name"`
	DurationMs  int32              `db:"duration_ms" json:"duration_ms"`
	Count       int32              `db:"count" json:"count"`
	TotalMs     int64              `db:"total_ms" json:"total_ms"`
	Source      string             `db:"source" json:"source"`
	ContextJson string             `db:"context_json" json:"context_json"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTimedPaginated(ctx context.Context, arg ListTimedPaginatedParams) ([]ListTimedPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listTimedPaginated, arg.ProjectID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTimedPaginatedRow
	for rows.Next() {
		var i ListTimedPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DurationMs,
			&i.Count,
			&i.TotalMs,
			&i.Source,
			&i.ContextJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTimed = `-- name: UpsertTimed :exec
INSERT INTO zdx_timed (project_id, name, duration_ms, source, context_json, count, total_ms)
VALUES ($1, $2, $3, $4, $5, 1, $3)
ON CONFLICT (COALESCE(project_id, 0), name)
DO UPDATE SET
  duration_ms  = GREATEST(zdx_timed.duration_ms, EXCLUDED.duration_ms),
  source       = CASE WHEN EXCLUDED.duration_ms > zdx_timed.duration_ms THEN EXCLUDED.source ELSE zdx_timed.source END,
  context_json = CASE WHEN EXCLUDED.duration_ms > zdx_timed.duration_ms THEN EXCLUDED.context_json ELSE zdx_timed.context_json END,
  count        = zdx_timed.count + 1,
  total_ms     = zdx_timed.total_ms + EXCLUDED.duration_ms,
  created_at   = NOW()
`

type UpsertTimedParams struct {
	ProjectID   pgtype.Int4 `db:"project_id" json:"project_id"`
	Name        string      `db:"name" json:"name"`
	DurationMs  int32       `db:"duration_ms" json:"duration_ms"`
	Source      string      `db:"source" json:"source"`
	ContextJson string      `db:"context_json" json:"context_json"`
}

func (q *Queries) UpsertTimed(ctx context.Context, arg UpsertTimedParams) error {
	_, err := q.db.Exec(ctx, upsertTimed,
		arg.ProjectID,
		arg.Name,
		arg.DurationMs,
		arg.Source,
		arg.ContextJson,
	)
	return err
}
